#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   The implementation is messy (issue #350): on Windows, with _MSC_VER,
   we have to define Py_LIMITED_API even before including pyconfig.h.
   In that case, we guess what pyconfig.h will do to the macros above,
   and check our guess after the #include.

   Note that on Windows, with CPython 3.x, you need >= 3.5 and virtualenv
   version >= 16.0.0.  With older versions of either, you don't get a
   copy of PYTHON3.DLL in the virtualenv.  We can't check the version of
   CPython *before* we even include pyconfig.h.  ffi.set_source() puts
   a ``#define _CFFI_NO_LIMITED_API'' at the start of this file if it is
   running on Windows < 3.5, as an attempt at fixing it, but that's
   arguably wrong because it may not be the target version of Python.
   Still better than nothing I guess.  As another workaround, you can
   remove the definition of Py_LIMITED_API here.

   See also 'py_limited_api' in cffi/setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  ifdef _MSC_VER
#    if !defined(_DEBUG) && !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#    include <pyconfig.h>
     /* sanity-check: Py_LIMITED_API will cause crashes if any of these
        are also defined.  Normally, the Python file PC/pyconfig.h does not
        cause any of these to be defined, with the exception that _DEBUG
        causes Py_DEBUG.  Double-check that. */
#    ifdef Py_LIMITED_API
#      if defined(Py_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_DEBUG, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_TRACE_REFS)
#        error "pyconfig.h unexpectedly defines Py_TRACE_REFS, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_REF_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_REF_DEBUG, but Py_LIMITED_API is set"
#      endif
#    endif
#  else
#    include <pyconfig.h>
#    if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>

/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#if PY_MAJOR_VERSION >= 3
# define PyInt_FromLong PyLong_FromLong
#endif

#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyInt_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyInt_FromLong((long)x) :                                    \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyInt_FromLong((long)x) :                                    \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(unsigned int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

union _cffi_union_alignment_u {
    unsigned char m_char;
    unsigned short m_short;
    unsigned int m_int;
    unsigned long m_long;
    unsigned long long m_longlong;
    float m_float;
    double m_double;
    long double m_longdouble;
};

struct _cffi_freeme_s {
    struct _cffi_freeme_s *next;
    union _cffi_union_alignment_u alignment;
};

_CFFI_UNUSED_FN static int
_cffi_convert_array_argument(struct _cffi_ctypedescr *ctptr, PyObject *arg,
                             char **output_data, Py_ssize_t datasize,
                             struct _cffi_freeme_s **freeme)
{
    char *p;
    if (datasize < 0)
        return -1;

    p = *output_data;
    if (p == NULL) {
        struct _cffi_freeme_s *fp = (struct _cffi_freeme_s *)PyObject_Malloc(
            offsetof(struct _cffi_freeme_s, alignment) + (size_t)datasize);
        if (fp == NULL)
            return -1;
        fp->next = *freeme;
        *freeme = fp;
        p = *output_data = (char *)&fp->alignment;
    }
    memset((void *)p, 0, (size_t)datasize);
    return _cffi_convert_array_from_object(p, ctptr, arg);
}

_CFFI_UNUSED_FN static void
_cffi_free_array_arguments(struct _cffi_freeme_s *freeme)
{
    do {
        void *p = (void *)freeme;
        freeme = freeme->next;
        PyObject_Free(p);
    } while (freeme != NULL);
}

/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/

void f_run_eval(double *data,double *x,double *y,double *u,double *p,double Dt){

data[0] = -p[39]*x[0] - y[36] + u[16] + 1; 

}

void g_run_eval(double *data,double *x,double *y,double *u,double *p,double Dt){

data[0] = -0.16980890270283108*y[7] - 0.042452225675707771*y[6] + 0.16980890270283108*y[9] + 0.042452225675707771*y[8] + 0.0039215686274509812*y[1] + 0.0009803921568627453*y[0] - 0.0019607843137254906*y[3] - 0.00049019607843137265*y[2] - 0.0019607843137254906*y[5] - 0.00049019607843137265*y[4] - y[30]; 
data[1] = -0.042452225675707771*y[7] + 0.16980890270283108*y[6] + 0.042452225675707771*y[9] - 0.16980890270283108*y[8] + 0.0009803921568627453*y[1] - 0.0039215686274509812*y[0] - 0.00049019607843137265*y[3] + 0.0019607843137254906*y[2] - 0.00049019607843137265*y[5] + 0.0019607843137254906*y[4] - y[33]; 
data[2] = -0.16980890270283108*y[9] - 0.042452225675707771*y[8] + 0.16980890270283108*y[11] + 0.042452225675707771*y[10] - 0.0019607843137254906*y[1] - 0.00049019607843137265*y[0] + 0.0039215686274509812*y[3] + 0.0009803921568627453*y[2] - 0.0019607843137254906*y[5] - 0.00049019607843137265*y[4] - y[31]; 
data[3] = -0.042452225675707771*y[9] + 0.16980890270283108*y[8] + 0.042452225675707771*y[11] - 0.16980890270283108*y[10] - 0.00049019607843137265*y[1] + 0.0019607843137254906*y[0] + 0.0009803921568627453*y[3] - 0.0039215686274509812*y[2] - 0.00049019607843137265*y[5] + 0.0019607843137254906*y[4] - y[34]; 
data[4] = 0.16980890270283108*y[7] + 0.042452225675707771*y[6] - 0.16980890270283108*y[11] - 0.042452225675707771*y[10] - 0.0019607843137254906*y[1] - 0.00049019607843137265*y[0] - 0.0019607843137254906*y[3] - 0.00049019607843137265*y[2] + 0.0039215686274509812*y[5] + 0.0009803921568627453*y[4] - y[32]; 
data[5] = 0.042452225675707771*y[7] - 0.16980890270283108*y[6] - 0.042452225675707771*y[11] + 0.16980890270283108*y[10] - 0.00049019607843137265*y[1] + 0.0019607843137254906*y[0] - 0.00049019607843137265*y[3] + 0.0019607843137254906*y[2] + 0.0009803921568627453*y[5] - 0.0039215686274509812*y[4] - y[35]; 
data[6] = -y[7]*(p[1] - 14.70588235294117) + y[6]*p[0] + 3.6764705882352926*y[6] - y[9]*p[3] + y[8]*p[2] - y[11]*p[5] + y[10]*p[4] - y[13]*(p[7] + 14.70588235294117) + y[12]*p[6] - 3.6764705882352926*y[12] + y[15]*p[1] - y[14]*p[0] + y[17]*p[3] - y[16]*p[2] + y[19]*p[5] - y[18]*p[4] + y[21]*p[7] - y[20]*p[6] - 0.16980890270283108*y[1] - 0.042452225675707771*y[0] + 0.16980890270283108*y[5] + 0.042452225675707771*y[4]; 
data[7] = y[7]*p[0] + 3.6764705882352926*y[7] + y[6]*(p[1] - 14.70588235294117) + y[9]*p[2] + y[8]*p[3] + y[11]*p[4] + y[10]*p[5] + y[13]*p[6] - 3.6764705882352926*y[13] + y[12]*(p[7] + 14.70588235294117) - y[15]*p[0] - y[14]*p[1] - y[17]*p[2] - y[16]*p[3] - y[19]*p[4] - y[18]*p[5] - y[21]*p[6] - y[20]*p[7] - 0.042452225675707771*y[1] + 0.16980890270283108*y[0] + 0.042452225675707771*y[5] - 0.16980890270283108*y[4]; 
data[8] = -y[7]*p[9] + y[6]*p[8] - y[9]*(p[11] - 14.70588235294117) + y[8]*p[10] + 3.6764705882352926*y[8] - y[11]*p[13] + y[10]*p[12] - y[13]*(p[15] + 14.70588235294117) + y[12]*p[14] - 3.6764705882352926*y[12] + y[15]*p[9] - y[14]*p[8] + y[17]*p[11] - y[16]*p[10] + y[19]*p[13] - y[18]*p[12] + y[21]*p[15] - y[20]*p[14] + 0.16980890270283108*y[1] + 0.042452225675707771*y[0] - 0.16980890270283108*y[3] - 0.042452225675707771*y[2]; 
data[9] = y[7]*p[8] + y[6]*p[9] + y[9]*p[10] + 3.6764705882352926*y[9] + y[8]*(p[11] - 14.70588235294117) + y[11]*p[12] + y[10]*p[13] + y[13]*p[14] - 3.6764705882352926*y[13] + y[12]*(p[15] + 14.70588235294117) - y[15]*p[8] - y[14]*p[9] - y[17]*p[10] - y[16]*p[11] - y[19]*p[12] - y[18]*p[13] - y[21]*p[14] - y[20]*p[15] + 0.042452225675707771*y[1] - 0.16980890270283108*y[0] - 0.042452225675707771*y[3] + 0.16980890270283108*y[2]; 
data[10] = -y[7]*p[17] + y[6]*p[16] - y[9]*p[19] + y[8]*p[18] - y[11]*(p[21] - 14.70588235294117) + y[10]*p[20] + 3.6764705882352926*y[10] - y[13]*(p[23] + 14.70588235294117) + y[12]*p[22] - 3.6764705882352926*y[12] + y[15]*p[17] - y[14]*p[16] + y[17]*p[19] - y[16]*p[18] + y[19]*p[21] - y[18]*p[20] + y[21]*p[23] - y[20]*p[22] + 0.16980890270283108*y[3] + 0.042452225675707771*y[2] - 0.16980890270283108*y[5] - 0.042452225675707771*y[4]; 
data[11] = y[7]*p[16] + y[6]*p[17] + y[9]*p[18] + y[8]*p[19] + y[11]*p[20] + 3.6764705882352926*y[11] + y[10]*(p[21] - 14.70588235294117) + y[13]*p[22] - 3.6764705882352926*y[13] + y[12]*(p[23] + 14.70588235294117) - y[15]*p[16] - y[14]*p[17] - y[17]*p[18] - y[16]*p[19] - y[19]*p[20] - y[18]*p[21] - y[21]*p[22] - y[20]*p[23] + 0.042452225675707771*y[3] - 0.16980890270283108*y[2] - 0.042452225675707771*y[5] + 0.16980890270283108*y[4]; 
data[12] = -y[7]*(p[25] + 14.70588235294117) + y[6]*p[24] - 3.6764705882352926*y[6] - y[9]*(p[27] + 14.70588235294117) + y[8]*p[26] - 3.6764705882352926*y[8] - y[11]*(p[29] + 14.70588235294117) + y[10]*p[28] - 3.6764705882352926*y[10] - y[13]*(p[31] + p[33] - 44.117647058823508) + y[12]*p[30] + y[12]*p[32] + 11.029411764705877*y[12] + y[15]*p[25] - y[14]*p[24] + y[17]*p[27] - y[16]*p[26] + y[19]*p[29] - y[18]*p[28] + y[21]*p[31] - y[20]*p[30]; 
data[13] = y[7]*p[24] - 3.6764705882352926*y[7] + y[6]*(p[25] + 14.70588235294117) + y[9]*p[26] - 3.6764705882352926*y[9] + y[8]*(p[27] + 14.70588235294117) + y[11]*p[28] - 3.6764705882352926*y[11] + y[10]*(p[29] + 14.70588235294117) + y[13]*p[30] + y[13]*p[32] + 11.029411764705877*y[13] + y[12]*(p[31] + p[33] - 44.117647058823508) - y[15]*p[24] - y[14]*p[25] - y[17]*p[26] - y[16]*p[27] - y[19]*p[28] - y[18]*p[29] - y[21]*p[30] - y[20]*p[31]; 
data[14] = y[7]*p[1] - y[6]*p[0] + y[9]*p[3] - y[8]*p[2] + y[11]*p[5] - y[10]*p[4] + y[13]*p[7] - y[12]*p[6] - y[15]*p[1] + y[14]*p[0] - y[17]*p[3] + y[16]*p[2] - y[19]*p[5] + y[18]*p[4] - y[21]*p[7] + y[20]*p[6] - y[22]; 
data[15] = -y[7]*p[0] - y[6]*p[1] - y[9]*p[2] - y[8]*p[3] - y[11]*p[4] - y[10]*p[5] - y[13]*p[6] - y[12]*p[7] + y[15]*p[0] + y[14]*p[1] + y[17]*p[2] + y[16]*p[3] + y[19]*p[4] + y[18]*p[5] + y[21]*p[6] + y[20]*p[7] - y[23]; 
data[16] = y[7]*p[9] - y[6]*p[8] + y[9]*p[11] - y[8]*p[10] + y[11]*p[13] - y[10]*p[12] + y[13]*p[15] - y[12]*p[14] - y[15]*p[9] + y[14]*p[8] - y[17]*p[11] + y[16]*p[10] - y[19]*p[13] + y[18]*p[12] - y[21]*p[15] + y[20]*p[14] - y[24]; 
data[17] = -y[7]*p[8] - y[6]*p[9] - y[9]*p[10] - y[8]*p[11] - y[11]*p[12] - y[10]*p[13] - y[13]*p[14] - y[12]*p[15] + y[15]*p[8] + y[14]*p[9] + y[17]*p[10] + y[16]*p[11] + y[19]*p[12] + y[18]*p[13] + y[21]*p[14] + y[20]*p[15] - y[25]; 
data[18] = y[7]*p[17] - y[6]*p[16] + y[9]*p[19] - y[8]*p[18] + y[11]*p[21] - y[10]*p[20] + y[13]*p[23] - y[12]*p[22] - y[15]*p[17] + y[14]*p[16] - y[17]*p[19] + y[16]*p[18] - y[19]*p[21] + y[18]*p[20] - y[21]*p[23] + y[20]*p[22] - y[26]; 
data[19] = -y[7]*p[16] - y[6]*p[17] - y[9]*p[18] - y[8]*p[19] - y[11]*p[20] - y[10]*p[21] - y[13]*p[22] - y[12]*p[23] + y[15]*p[16] + y[14]*p[17] + y[17]*p[18] + y[16]*p[19] + y[19]*p[20] + y[18]*p[21] + y[21]*p[22] + y[20]*p[23] - y[27]; 
data[20] = y[7]*p[25] - y[6]*p[24] + y[9]*p[27] - y[8]*p[26] + y[11]*p[29] - y[10]*p[28] + y[13]*p[31] - y[12]*p[30] - y[15]*p[25] + y[14]*p[24] - y[17]*p[27] + y[16]*p[26] - y[19]*p[29] + y[18]*p[28] - y[21]*p[31] + y[20]*p[30] - y[28]; 
data[21] = -y[7]*p[24] - y[6]*p[25] - y[9]*p[26] - y[8]*p[27] - y[11]*p[28] - y[10]*p[29] - y[13]*p[30] - y[12]*p[31] + y[15]*p[24] + y[14]*p[25] + y[17]*p[26] + y[16]*p[27] + y[19]*p[28] + y[18]*p[29] + y[21]*p[30] + y[20]*p[31] - y[29]; 
data[22] = p[34]*(pow(y[15], 2)*u[2] - 2*y[15]*y[21]*u[2] + pow(y[14], 2)*u[2] - 2*y[14]*y[20]*u[2] + pow(y[21], 2)*u[2] + pow(y[20], 2)*u[2] + u[0] + (y[15]*y[23] + y[14]*y[22] - y[21]*y[23] - y[20]*y[22])*((sqrt(pow(y[15], 2) + pow(y[14], 2)) < 0.69999999999999996) ? (
   1.0/(sqrt(pow(y[15], 2) + pow(y[14], 2)) + 0.29999999999999999)
)
: (
   1.0
))); 
data[23] = p[34]*(pow(y[17], 2)*u[6] - 2*y[17]*y[21]*u[6] + pow(y[16], 2)*u[6] - 2*y[16]*y[20]*u[6] + pow(y[21], 2)*u[6] + pow(y[20], 2)*u[6] + u[4] + (y[17]*y[25] + y[16]*y[24] - y[21]*y[25] - y[20]*y[24])*((sqrt(pow(y[17], 2) + pow(y[16], 2)) < 0.69999999999999996) ? (
   1.0/(sqrt(pow(y[17], 2) + pow(y[16], 2)) + 0.29999999999999999)
)
: (
   1.0
))); 
data[24] = p[34]*(pow(y[19], 2)*u[10] - 2*y[19]*y[21]*u[10] + pow(y[18], 2)*u[10] - 2*y[18]*y[20]*u[10] + pow(y[21], 2)*u[10] + pow(y[20], 2)*u[10] + u[8] + (y[19]*y[27] + y[18]*y[26] - y[21]*y[27] - y[20]*y[26])*((sqrt(pow(y[19], 2) + pow(y[18], 2)) < 0.69999999999999996) ? (
   1.0/(sqrt(pow(y[19], 2) + pow(y[18], 2)) + 0.29999999999999999)
)
: (
   1.0
))); 
data[25] = p[34]*(-1.0*pow(y[15], 2)*u[3] + 2.0*y[15]*y[21]*u[3] - 1.0*pow(y[14], 2)*u[3] + 2.0*y[14]*y[20]*u[3] - 1.0*pow(y[21], 2)*u[3] - 1.0*pow(y[20], 2)*u[3] + u[1] + (y[15]*y[22] - y[14]*y[23] - y[21]*y[22] + y[20]*y[23])*((sqrt(pow(y[15], 2) + pow(y[14], 2)) < 0.69999999999999996) ? (
   1.0/(sqrt(pow(y[15], 2) + pow(y[14], 2)) + 0.29999999999999999)
)
: (
   1.0
))); 
data[26] = p[34]*(-1.0*pow(y[17], 2)*u[7] + 2.0*y[17]*y[21]*u[7] - 1.0*pow(y[16], 2)*u[7] + 2.0*y[16]*y[20]*u[7] - 1.0*pow(y[21], 2)*u[7] - 1.0*pow(y[20], 2)*u[7] + u[5] + (y[17]*y[24] - y[16]*y[25] - y[21]*y[24] + y[20]*y[25])*((sqrt(pow(y[17], 2) + pow(y[16], 2)) < 0.69999999999999996) ? (
   1.0/(sqrt(pow(y[17], 2) + pow(y[16], 2)) + 0.29999999999999999)
)
: (
   1.0
))); 
data[27] = p[34]*(-1.0*pow(y[19], 2)*u[11] + 2.0*y[19]*y[21]*u[11] - 1.0*pow(y[18], 2)*u[11] + 2.0*y[18]*y[20]*u[11] - 1.0*pow(y[21], 2)*u[11] - 1.0*pow(y[20], 2)*u[11] + u[9] + (y[19]*y[26] - y[18]*y[27] - y[21]*y[26] + y[20]*y[27])*((sqrt(pow(y[19], 2) + pow(y[18], 2)) < 0.69999999999999996) ? (
   1.0/(sqrt(pow(y[19], 2) + pow(y[18], 2)) + 0.29999999999999999)
)
: (
   1.0
))); 
data[28] = y[22] + y[24] + y[26] + y[28]; 
data[29] = y[23] + y[25] + y[27] + y[29]; 
data[30] = -p[36]*y[30] - y[0] + 1.0*p[35]*y[33] + u[12]*cos(u[15]); 
data[31] = -p[36]*y[31] - y[2] + 1.0*p[35]*y[34] + u[13]*cos(u[15] - 2.0943951023931953); 
data[32] = -p[36]*y[32] - y[4] + 1.0*p[35]*y[35] + u[14]*cos(u[15] - 4.1887902047863905); 
data[33] = -1.0*p[36]*y[33] - 1.0*y[1] - 1.0*p[35]*y[30] + 1.0*u[12]*sin(u[15]); 
data[34] = -1.0*p[36]*y[34] - 1.0*y[3] - 1.0*p[35]*y[31] + 1.0*u[13]*sin(u[15] - 2.0943951023931953); 
data[35] = -1.0*p[36]*y[35] - 1.0*y[5] - 1.0*p[35]*y[32] + 1.0*u[14]*sin(u[15] - 4.1887902047863905); 
data[36] = 1.0 - y[36]; 
data[37] = p[38]*x[0] + p[37]*(1 - y[36]) - y[37]; 

}

void h_eval(double *data,double *x,double *y,double *u,double *p,double Dt){

data[0] = -y[7]*p[1] + y[6]*p[0] - y[9]*p[3] + y[8]*p[2] - y[11]*p[5] + y[10]*p[4] - y[13]*p[7] + y[12]*p[6] + y[15]*p[1] - y[14]*p[0] + y[17]*p[3] - y[16]*p[2] + y[19]*p[5] - y[18]*p[4] + y[21]*p[7] - y[20]*p[6]; 
data[1] = y[7]*p[0] + y[6]*p[1] + y[9]*p[2] + y[8]*p[3] + y[11]*p[4] + y[10]*p[5] + y[13]*p[6] + y[12]*p[7] - y[15]*p[0] - y[14]*p[1] - y[17]*p[2] - y[16]*p[3] - y[19]*p[4] - y[18]*p[5] - y[21]*p[6] - y[20]*p[7]; 
data[2] = -y[7]*p[9] + y[6]*p[8] - y[9]*p[11] + y[8]*p[10] - y[11]*p[13] + y[10]*p[12] - y[13]*p[15] + y[12]*p[14] + y[15]*p[9] - y[14]*p[8] + y[17]*p[11] - y[16]*p[10] + y[19]*p[13] - y[18]*p[12] + y[21]*p[15] - y[20]*p[14]; 
data[3] = y[7]*p[8] + y[6]*p[9] + y[9]*p[10] + y[8]*p[11] + y[11]*p[12] + y[10]*p[13] + y[13]*p[14] + y[12]*p[15] - y[15]*p[8] - y[14]*p[9] - y[17]*p[10] - y[16]*p[11] - y[19]*p[12] - y[18]*p[13] - y[21]*p[14] - y[20]*p[15]; 
data[4] = -y[7]*p[17] + y[6]*p[16] - y[9]*p[19] + y[8]*p[18] - y[11]*p[21] + y[10]*p[20] - y[13]*p[23] + y[12]*p[22] + y[15]*p[17] - y[14]*p[16] + y[17]*p[19] - y[16]*p[18] + y[19]*p[21] - y[18]*p[20] + y[21]*p[23] - y[20]*p[22]; 
data[5] = y[7]*p[16] + y[6]*p[17] + y[9]*p[18] + y[8]*p[19] + y[11]*p[20] + y[10]*p[21] + y[13]*p[22] + y[12]*p[23] - y[15]*p[16] - y[14]*p[17] - y[17]*p[18] - y[16]*p[19] - y[19]*p[20] - y[18]*p[21] - y[21]*p[22] - y[20]*p[23]; 
data[6] = -y[7]*p[25] + y[6]*p[24] - y[9]*p[27] + y[8]*p[26] - y[11]*p[29] + y[10]*p[28] - y[13]*p[31] + y[12]*p[30] + y[15]*p[25] - y[14]*p[24] + y[17]*p[27] - y[16]*p[26] + y[19]*p[29] - y[18]*p[28] + y[21]*p[31] - y[20]*p[30]; 
data[7] = y[7]*p[24] + y[6]*p[25] + y[9]*p[26] + y[8]*p[27] + y[11]*p[28] + y[10]*p[29] + y[13]*p[30] + y[12]*p[31] - y[15]*p[24] - y[14]*p[25] - y[17]*p[26] - y[16]*p[27] - y[19]*p[28] - y[18]*p[29] - y[21]*p[30] - y[20]*p[31]; 
data[8] = -0.16980890270283108*y[7] - 0.042452225675707771*y[6] + 0.16980890270283108*y[9] + 0.042452225675707771*y[8] + 0.0039215686274509812*y[1] + 0.0009803921568627453*y[0] - 0.0019607843137254906*y[3] - 0.00049019607843137265*y[2] - 0.0019607843137254906*y[5] - 0.00049019607843137265*y[4]; 
data[9] = -0.042452225675707771*y[7] + 0.16980890270283108*y[6] + 0.042452225675707771*y[9] - 0.16980890270283108*y[8] + 0.0009803921568627453*y[1] - 0.0039215686274509812*y[0] - 0.00049019607843137265*y[3] + 0.0019607843137254906*y[2] - 0.00049019607843137265*y[5] + 0.0019607843137254906*y[4]; 
data[10] = -0.16980890270283108*y[9] - 0.042452225675707771*y[8] + 0.16980890270283108*y[11] + 0.042452225675707771*y[10] - 0.0019607843137254906*y[1] - 0.00049019607843137265*y[0] + 0.0039215686274509812*y[3] + 0.0009803921568627453*y[2] - 0.0019607843137254906*y[5] - 0.00049019607843137265*y[4]; 
data[11] = -0.042452225675707771*y[9] + 0.16980890270283108*y[8] + 0.042452225675707771*y[11] - 0.16980890270283108*y[10] - 0.00049019607843137265*y[1] + 0.0019607843137254906*y[0] + 0.0009803921568627453*y[3] - 0.0039215686274509812*y[2] - 0.00049019607843137265*y[5] + 0.0019607843137254906*y[4]; 
data[12] = 0.16980890270283108*y[7] + 0.042452225675707771*y[6] - 0.16980890270283108*y[11] - 0.042452225675707771*y[10] - 0.0019607843137254906*y[1] - 0.00049019607843137265*y[0] - 0.0019607843137254906*y[3] - 0.00049019607843137265*y[2] + 0.0039215686274509812*y[5] + 0.0009803921568627453*y[4]; 
data[13] = 0.042452225675707771*y[7] - 0.16980890270283108*y[6] - 0.042452225675707771*y[11] + 0.16980890270283108*y[10] - 0.00049019607843137265*y[1] + 0.0019607843137254906*y[0] - 0.00049019607843137265*y[3] + 0.0019607843137254906*y[2] + 0.0009803921568627453*y[5] - 0.0039215686274509812*y[4]; 
data[14] = 14.70588235294117*y[7] + 3.6764705882352926*y[6] - 14.70588235294117*y[13] - 3.6764705882352926*y[12] - 0.16980890270283108*y[1] - 0.042452225675707771*y[0] + 0.16980890270283108*y[5] + 0.042452225675707771*y[4]; 
data[15] = 3.6764705882352926*y[7] - 14.70588235294117*y[6] - 3.6764705882352926*y[13] + 14.70588235294117*y[12] - 0.042452225675707771*y[1] + 0.16980890270283108*y[0] + 0.042452225675707771*y[5] - 0.16980890270283108*y[4]; 
data[16] = 14.70588235294117*y[9] + 3.6764705882352926*y[8] - 14.70588235294117*y[13] - 3.6764705882352926*y[12] + 0.16980890270283108*y[1] + 0.042452225675707771*y[0] - 0.16980890270283108*y[3] - 0.042452225675707771*y[2]; 
data[17] = 3.6764705882352926*y[9] - 14.70588235294117*y[8] - 3.6764705882352926*y[13] + 14.70588235294117*y[12] + 0.042452225675707771*y[1] - 0.16980890270283108*y[0] - 0.042452225675707771*y[3] + 0.16980890270283108*y[2]; 
data[18] = 14.70588235294117*y[11] + 3.6764705882352926*y[10] - 14.70588235294117*y[13] - 3.6764705882352926*y[12] + 0.16980890270283108*y[3] + 0.042452225675707771*y[2] - 0.16980890270283108*y[5] - 0.042452225675707771*y[4]; 
data[19] = 3.6764705882352926*y[11] - 14.70588235294117*y[10] - 3.6764705882352926*y[13] + 14.70588235294117*y[12] + 0.042452225675707771*y[3] - 0.16980890270283108*y[2] - 0.042452225675707771*y[5] + 0.16980890270283108*y[4]; 
data[20] = -14.70588235294117*y[7] - 3.6764705882352926*y[6] - 14.70588235294117*y[9] - 3.6764705882352926*y[8] - 14.70588235294117*y[11] - 3.6764705882352926*y[10] + 44.117647058823508*y[13] + 11.029411764705877*y[12]; 
data[21] = -3.6764705882352926*y[7] + 14.70588235294117*y[6] - 3.6764705882352926*y[9] + 14.70588235294117*y[8] - 3.6764705882352926*y[11] + 14.70588235294117*y[10] + 11.029411764705877*y[13] - 44.117647058823508*y[12]; 
data[22] = sqrt(pow(y[15], 2) + pow(y[14], 2)); 
data[23] = sqrt(pow(y[17], 2) + pow(y[16], 2)); 
data[24] = sqrt(pow(y[19], 2) + pow(y[18], 2)); 
data[25] = sqrt(1.0*pow(y[33], 2) + pow(y[30], 2)); 
data[26] = sqrt(1.0*pow(y[34], 2) + pow(y[31], 2)); 
data[27] = sqrt(1.0*pow(y[35], 2) + pow(y[32], 2)); 
data[28] = 1.0*y[1]*y[33] + y[0]*y[30] + 1.0*y[3]*y[34] + y[2]*y[31] + 1.0*y[5]*y[35] + y[4]*y[32]; 
data[29] = 1.0*y[1]*y[30] - 1.0*y[0]*y[33] + 1.0*y[3]*y[31] - 1.0*y[2]*y[34] + 1.0*y[5]*y[32] - 1.0*y[4]*y[35]; 
data[30] = x[0]; 
data[31] = u[16]; 

}

void de_jac_run_up_eval(double *data,double *x,double *y,double *u,double *p,double Dt){

data[0] = -p[39]; 
data[280] = p[0] + 3.6764705882352926; 
data[281] = 14.70588235294117 - p[1]; 
data[282] = p[2]; 
data[283] = -p[3]; 
data[284] = p[4]; 
data[285] = -p[5]; 
data[286] = p[6] - 3.6764705882352926; 
data[287] = -p[7] - 14.70588235294117; 
data[288] = -p[0]; 
data[289] = p[1]; 
data[290] = -p[2]; 
data[291] = p[3]; 
data[292] = -p[4]; 
data[293] = p[5]; 
data[294] = -p[6]; 
data[295] = p[7]; 
data[319] = p[1] - 14.70588235294117; 
data[320] = p[0] + 3.6764705882352926; 
data[321] = p[3]; 
data[322] = p[2]; 
data[323] = p[5]; 
data[324] = p[4]; 
data[325] = p[7] + 14.70588235294117; 
data[326] = p[6] - 3.6764705882352926; 
data[327] = -p[1]; 
data[328] = -p[0]; 
data[329] = -p[3]; 
data[330] = -p[2]; 
data[331] = -p[5]; 
data[332] = -p[4]; 
data[333] = -p[7]; 
data[334] = -p[6]; 
data[358] = p[8]; 
data[359] = -p[9]; 
data[360] = p[10] + 3.6764705882352926; 
data[361] = 14.70588235294117 - p[11]; 
data[362] = p[12]; 
data[363] = -p[13]; 
data[364] = p[14] - 3.6764705882352926; 
data[365] = -p[15] - 14.70588235294117; 
data[366] = -p[8]; 
data[367] = p[9]; 
data[368] = -p[10]; 
data[369] = p[11]; 
data[370] = -p[12]; 
data[371] = p[13]; 
data[372] = -p[14]; 
data[373] = p[15]; 
data[397] = p[9]; 
data[398] = p[8]; 
data[399] = p[11] - 14.70588235294117; 
data[400] = p[10] + 3.6764705882352926; 
data[401] = p[13]; 
data[402] = p[12]; 
data[403] = p[15] + 14.70588235294117; 
data[404] = p[14] - 3.6764705882352926; 
data[405] = -p[9]; 
data[406] = -p[8]; 
data[407] = -p[11]; 
data[408] = -p[10]; 
data[409] = -p[13]; 
data[410] = -p[12]; 
data[411] = -p[15]; 
data[412] = -p[14]; 
data[436] = p[16]; 
data[437] = -p[17]; 
data[438] = p[18]; 
data[439] = -p[19]; 
data[440] = p[20] + 3.6764705882352926; 
data[441] = 14.70588235294117 - p[21]; 
data[442] = p[22] - 3.6764705882352926; 
data[443] = -p[23] - 14.70588235294117; 
data[444] = -p[16]; 
data[445] = p[17]; 
data[446] = -p[18]; 
data[447] = p[19]; 
data[448] = -p[20]; 
data[449] = p[21]; 
data[450] = -p[22]; 
data[451] = p[23]; 
data[475] = p[17]; 
data[476] = p[16]; 
data[477] = p[19]; 
data[478] = p[18]; 
data[479] = p[21] - 14.70588235294117; 
data[480] = p[20] + 3.6764705882352926; 
data[481] = p[23] + 14.70588235294117; 
data[482] = p[22] - 3.6764705882352926; 
data[483] = -p[17]; 
data[484] = -p[16]; 
data[485] = -p[19]; 
data[486] = -p[18]; 
data[487] = -p[21]; 
data[488] = -p[20]; 
data[489] = -p[23]; 
data[490] = -p[22]; 
data[514] = p[24] - 3.6764705882352926; 
data[515] = -p[25] - 14.70588235294117; 
data[516] = p[26] - 3.6764705882352926; 
data[517] = -p[27] - 14.70588235294117; 
data[518] = p[28] - 3.6764705882352926; 
data[519] = -p[29] - 14.70588235294117; 
data[520] = p[30] + p[32] + 11.029411764705877; 
data[521] = -p[31] - p[33] + 44.117647058823508; 
data[522] = -p[24]; 
data[523] = p[25]; 
data[524] = -p[26]; 
data[525] = p[27]; 
data[526] = -p[28]; 
data[527] = p[29]; 
data[528] = -p[30]; 
data[529] = p[31]; 
data[553] = p[25] + 14.70588235294117; 
data[554] = p[24] - 3.6764705882352926; 
data[555] = p[27] + 14.70588235294117; 
data[556] = p[26] - 3.6764705882352926; 
data[557] = p[29] + 14.70588235294117; 
data[558] = p[28] - 3.6764705882352926; 
data[559] = p[31] + p[33] - 44.117647058823508; 
data[560] = p[30] + p[32] + 11.029411764705877; 
data[561] = -p[25]; 
data[562] = -p[24]; 
data[563] = -p[27]; 
data[564] = -p[26]; 
data[565] = -p[29]; 
data[566] = -p[28]; 
data[567] = -p[31]; 
data[568] = -p[30]; 
data[592] = -p[0]; 
data[593] = p[1]; 
data[594] = -p[2]; 
data[595] = p[3]; 
data[596] = -p[4]; 
data[597] = p[5]; 
data[598] = -p[6]; 
data[599] = p[7]; 
data[600] = p[0]; 
data[601] = -p[1]; 
data[602] = p[2]; 
data[603] = -p[3]; 
data[604] = p[4]; 
data[605] = -p[5]; 
data[606] = p[6]; 
data[607] = -p[7]; 
data[631] = -p[1]; 
data[632] = -p[0]; 
data[633] = -p[3]; 
data[634] = -p[2]; 
data[635] = -p[5]; 
data[636] = -p[4]; 
data[637] = -p[7]; 
data[638] = -p[6]; 
data[639] = p[1]; 
data[640] = p[0]; 
data[641] = p[3]; 
data[642] = p[2]; 
data[643] = p[5]; 
data[644] = p[4]; 
data[645] = p[7]; 
data[646] = p[6]; 
data[670] = -p[8]; 
data[671] = p[9]; 
data[672] = -p[10]; 
data[673] = p[11]; 
data[674] = -p[12]; 
data[675] = p[13]; 
data[676] = -p[14]; 
data[677] = p[15]; 
data[678] = p[8]; 
data[679] = -p[9]; 
data[680] = p[10]; 
data[681] = -p[11]; 
data[682] = p[12]; 
data[683] = -p[13]; 
data[684] = p[14]; 
data[685] = -p[15]; 
data[709] = -p[9]; 
data[710] = -p[8]; 
data[711] = -p[11]; 
data[712] = -p[10]; 
data[713] = -p[13]; 
data[714] = -p[12]; 
data[715] = -p[15]; 
data[716] = -p[14]; 
data[717] = p[9]; 
data[718] = p[8]; 
data[719] = p[11]; 
data[720] = p[10]; 
data[721] = p[13]; 
data[722] = p[12]; 
data[723] = p[15]; 
data[724] = p[14]; 
data[748] = -p[16]; 
data[749] = p[17]; 
data[750] = -p[18]; 
data[751] = p[19]; 
data[752] = -p[20]; 
data[753] = p[21]; 
data[754] = -p[22]; 
data[755] = p[23]; 
data[756] = p[16]; 
data[757] = -p[17]; 
data[758] = p[18]; 
data[759] = -p[19]; 
data[760] = p[20]; 
data[761] = -p[21]; 
data[762] = p[22]; 
data[763] = -p[23]; 
data[787] = -p[17]; 
data[788] = -p[16]; 
data[789] = -p[19]; 
data[790] = -p[18]; 
data[791] = -p[21]; 
data[792] = -p[20]; 
data[793] = -p[23]; 
data[794] = -p[22]; 
data[795] = p[17]; 
data[796] = p[16]; 
data[797] = p[19]; 
data[798] = p[18]; 
data[799] = p[21]; 
data[800] = p[20]; 
data[801] = p[23]; 
data[802] = p[22]; 
data[826] = -p[24]; 
data[827] = p[25]; 
data[828] = -p[26]; 
data[829] = p[27]; 
data[830] = -p[28]; 
data[831] = p[29]; 
data[832] = -p[30]; 
data[833] = p[31]; 
data[834] = p[24]; 
data[835] = -p[25]; 
data[836] = p[26]; 
data[837] = -p[27]; 
data[838] = p[28]; 
data[839] = -p[29]; 
data[840] = p[30]; 
data[841] = -p[31]; 
data[865] = -p[25]; 
data[866] = -p[24]; 
data[867] = -p[27]; 
data[868] = -p[26]; 
data[869] = -p[29]; 
data[870] = -p[28]; 
data[871] = -p[31]; 
data[872] = -p[30]; 
data[873] = p[25]; 
data[874] = p[24]; 
data[875] = p[27]; 
data[876] = p[26]; 
data[877] = p[29]; 
data[878] = p[28]; 
data[879] = p[31]; 
data[880] = p[30]; 
data[1240] = -p[36]; 
data[1243] = 1.0*p[35]; 
data[1280] = -p[36]; 
data[1283] = 1.0*p[35]; 
data[1320] = -p[36]; 
data[1323] = 1.0*p[35]; 
data[1357] = -1.0*p[35]; 
data[1360] = -1.0*p[36]; 
data[1397] = -1.0*p[35]; 
data[1400] = -1.0*p[36]; 
data[1437] = -1.0*p[35]; 
data[1440] = -1.0*p[36]; 
data[1482] = p[38]; 
data[1519] = -p[37]; 

}

void de_jac_run_xy_eval(double *data,double *x,double *y,double *u,double *p,double Dt){

data[912] = p[34]*(2*y[14]*u[2] - 2*y[20]*u[2] + y[22]*((sqrt(pow(y[15], 2) + pow(y[14], 2)) < 0.69999999999999996) ? (
   1.0/(sqrt(pow(y[15], 2) + pow(y[14], 2)) + 0.29999999999999999)
)
: (
   1.0
)) + (y[15]*y[23] + y[14]*y[22] - y[21]*y[23] - y[20]*y[22])*((sqrt(pow(y[15], 2) + pow(y[14], 2)) < 0.69999999999999996) ? (
   -1.0*y[14]*pow(pow(y[15], 2) + pow(y[14], 2), -0.5)/pow(sqrt(pow(y[15], 2) + pow(y[14], 2)) + 0.29999999999999999, 2)
)
: (
   0
))); 
data[913] = p[34]*(2*y[15]*u[2] - 2*y[21]*u[2] + y[23]*((sqrt(pow(y[15], 2) + pow(y[14], 2)) < 0.69999999999999996) ? (
   1.0/(sqrt(pow(y[15], 2) + pow(y[14], 2)) + 0.29999999999999999)
)
: (
   1.0
)) + (y[15]*y[23] + y[14]*y[22] - y[21]*y[23] - y[20]*y[22])*((sqrt(pow(y[15], 2) + pow(y[14], 2)) < 0.69999999999999996) ? (
   -1.0*y[15]*pow(pow(y[15], 2) + pow(y[14], 2), -0.5)/pow(sqrt(pow(y[15], 2) + pow(y[14], 2)) + 0.29999999999999999, 2)
)
: (
   0
))); 
data[918] = p[34]*(-2*y[14]*u[2] + 2*y[20]*u[2] - y[22]*((sqrt(pow(y[15], 2) + pow(y[14], 2)) < 0.69999999999999996) ? (
   1.0/(sqrt(pow(y[15], 2) + pow(y[14], 2)) + 0.29999999999999999)
)
: (
   1.0
))); 
data[919] = p[34]*(-2*y[15]*u[2] + 2*y[21]*u[2] - y[23]*((sqrt(pow(y[15], 2) + pow(y[14], 2)) < 0.69999999999999996) ? (
   1.0/(sqrt(pow(y[15], 2) + pow(y[14], 2)) + 0.29999999999999999)
)
: (
   1.0
))); 
data[920] = p[34]*(y[14] - y[20])*((sqrt(pow(y[15], 2) + pow(y[14], 2)) < 0.69999999999999996) ? (
   1.0/(sqrt(pow(y[15], 2) + pow(y[14], 2)) + 0.29999999999999999)
)
: (
   1.0
)); 
data[921] = p[34]*(y[15] - y[21])*((sqrt(pow(y[15], 2) + pow(y[14], 2)) < 0.69999999999999996) ? (
   1.0/(sqrt(pow(y[15], 2) + pow(y[14], 2)) + 0.29999999999999999)
)
: (
   1.0
)); 
data[953] = p[34]*(2*y[16]*u[6] - 2*y[20]*u[6] + y[24]*((sqrt(pow(y[17], 2) + pow(y[16], 2)) < 0.69999999999999996) ? (
   1.0/(sqrt(pow(y[17], 2) + pow(y[16], 2)) + 0.29999999999999999)
)
: (
   1.0
)) + (y[17]*y[25] + y[16]*y[24] - y[21]*y[25] - y[20]*y[24])*((sqrt(pow(y[17], 2) + pow(y[16], 2)) < 0.69999999999999996) ? (
   -1.0*y[16]*pow(pow(y[17], 2) + pow(y[16], 2), -0.5)/pow(sqrt(pow(y[17], 2) + pow(y[16], 2)) + 0.29999999999999999, 2)
)
: (
   0
))); 
data[954] = p[34]*(2*y[17]*u[6] - 2*y[21]*u[6] + y[25]*((sqrt(pow(y[17], 2) + pow(y[16], 2)) < 0.69999999999999996) ? (
   1.0/(sqrt(pow(y[17], 2) + pow(y[16], 2)) + 0.29999999999999999)
)
: (
   1.0
)) + (y[17]*y[25] + y[16]*y[24] - y[21]*y[25] - y[20]*y[24])*((sqrt(pow(y[17], 2) + pow(y[16], 2)) < 0.69999999999999996) ? (
   -1.0*y[17]*pow(pow(y[17], 2) + pow(y[16], 2), -0.5)/pow(sqrt(pow(y[17], 2) + pow(y[16], 2)) + 0.29999999999999999, 2)
)
: (
   0
))); 
data[957] = p[34]*(-2*y[16]*u[6] + 2*y[20]*u[6] - y[24]*((sqrt(pow(y[17], 2) + pow(y[16], 2)) < 0.69999999999999996) ? (
   1.0/(sqrt(pow(y[17], 2) + pow(y[16], 2)) + 0.29999999999999999)
)
: (
   1.0
))); 
data[958] = p[34]*(-2*y[17]*u[6] + 2*y[21]*u[6] - y[25]*((sqrt(pow(y[17], 2) + pow(y[16], 2)) < 0.69999999999999996) ? (
   1.0/(sqrt(pow(y[17], 2) + pow(y[16], 2)) + 0.29999999999999999)
)
: (
   1.0
))); 
data[961] = p[34]*(y[16] - y[20])*((sqrt(pow(y[17], 2) + pow(y[16], 2)) < 0.69999999999999996) ? (
   1.0/(sqrt(pow(y[17], 2) + pow(y[16], 2)) + 0.29999999999999999)
)
: (
   1.0
)); 
data[962] = p[34]*(y[17] - y[21])*((sqrt(pow(y[17], 2) + pow(y[16], 2)) < 0.69999999999999996) ? (
   1.0/(sqrt(pow(y[17], 2) + pow(y[16], 2)) + 0.29999999999999999)
)
: (
   1.0
)); 
data[994] = p[34]*(2*y[18]*u[10] - 2*y[20]*u[10] + y[26]*((sqrt(pow(y[19], 2) + pow(y[18], 2)) < 0.69999999999999996) ? (
   1.0/(sqrt(pow(y[19], 2) + pow(y[18], 2)) + 0.29999999999999999)
)
: (
   1.0
)) + (y[19]*y[27] + y[18]*y[26] - y[21]*y[27] - y[20]*y[26])*((sqrt(pow(y[19], 2) + pow(y[18], 2)) < 0.69999999999999996) ? (
   -1.0*y[18]*pow(pow(y[19], 2) + pow(y[18], 2), -0.5)/pow(sqrt(pow(y[19], 2) + pow(y[18], 2)) + 0.29999999999999999, 2)
)
: (
   0
))); 
data[995] = p[34]*(2*y[19]*u[10] - 2*y[21]*u[10] + y[27]*((sqrt(pow(y[19], 2) + pow(y[18], 2)) < 0.69999999999999996) ? (
   1.0/(sqrt(pow(y[19], 2) + pow(y[18], 2)) + 0.29999999999999999)
)
: (
   1.0
)) + (y[19]*y[27] + y[18]*y[26] - y[21]*y[27] - y[20]*y[26])*((sqrt(pow(y[19], 2) + pow(y[18], 2)) < 0.69999999999999996) ? (
   -1.0*y[19]*pow(pow(y[19], 2) + pow(y[18], 2), -0.5)/pow(sqrt(pow(y[19], 2) + pow(y[18], 2)) + 0.29999999999999999, 2)
)
: (
   0
))); 
data[996] = p[34]*(-2*y[18]*u[10] + 2*y[20]*u[10] - y[26]*((sqrt(pow(y[19], 2) + pow(y[18], 2)) < 0.69999999999999996) ? (
   1.0/(sqrt(pow(y[19], 2) + pow(y[18], 2)) + 0.29999999999999999)
)
: (
   1.0
))); 
data[997] = p[34]*(-2*y[19]*u[10] + 2*y[21]*u[10] - y[27]*((sqrt(pow(y[19], 2) + pow(y[18], 2)) < 0.69999999999999996) ? (
   1.0/(sqrt(pow(y[19], 2) + pow(y[18], 2)) + 0.29999999999999999)
)
: (
   1.0
))); 
data[1002] = p[34]*(y[18] - y[20])*((sqrt(pow(y[19], 2) + pow(y[18], 2)) < 0.69999999999999996) ? (
   1.0/(sqrt(pow(y[19], 2) + pow(y[18], 2)) + 0.29999999999999999)
)
: (
   1.0
)); 
data[1003] = p[34]*(y[19] - y[21])*((sqrt(pow(y[19], 2) + pow(y[18], 2)) < 0.69999999999999996) ? (
   1.0/(sqrt(pow(y[19], 2) + pow(y[18], 2)) + 0.29999999999999999)
)
: (
   1.0
)); 
data[1029] = p[34]*(-2.0*y[14]*u[3] + 2.0*y[20]*u[3] - y[23]*((sqrt(pow(y[15], 2) + pow(y[14], 2)) < 0.69999999999999996) ? (
   1.0/(sqrt(pow(y[15], 2) + pow(y[14], 2)) + 0.29999999999999999)
)
: (
   1.0
)) + (y[15]*y[22] - y[14]*y[23] - y[21]*y[22] + y[20]*y[23])*((sqrt(pow(y[15], 2) + pow(y[14], 2)) < 0.69999999999999996) ? (
   -1.0*y[14]*pow(pow(y[15], 2) + pow(y[14], 2), -0.5)/pow(sqrt(pow(y[15], 2) + pow(y[14], 2)) + 0.29999999999999999, 2)
)
: (
   0
))); 
data[1030] = p[34]*(-2.0*y[15]*u[3] + 2.0*y[21]*u[3] + y[22]*((sqrt(pow(y[15], 2) + pow(y[14], 2)) < 0.69999999999999996) ? (
   1.0/(sqrt(pow(y[15], 2) + pow(y[14], 2)) + 0.29999999999999999)
)
: (
   1.0
)) + (y[15]*y[22] - y[14]*y[23] - y[21]*y[22] + y[20]*y[23])*((sqrt(pow(y[15], 2) + pow(y[14], 2)) < 0.69999999999999996) ? (
   -1.0*y[15]*pow(pow(y[15], 2) + pow(y[14], 2), -0.5)/pow(sqrt(pow(y[15], 2) + pow(y[14], 2)) + 0.29999999999999999, 2)
)
: (
   0
))); 
data[1035] = p[34]*(2.0*y[14]*u[3] - 2.0*y[20]*u[3] + y[23]*((sqrt(pow(y[15], 2) + pow(y[14], 2)) < 0.69999999999999996) ? (
   1.0/(sqrt(pow(y[15], 2) + pow(y[14], 2)) + 0.29999999999999999)
)
: (
   1.0
))); 
data[1036] = p[34]*(2.0*y[15]*u[3] - 2.0*y[21]*u[3] - y[22]*((sqrt(pow(y[15], 2) + pow(y[14], 2)) < 0.69999999999999996) ? (
   1.0/(sqrt(pow(y[15], 2) + pow(y[14], 2)) + 0.29999999999999999)
)
: (
   1.0
))); 
data[1037] = p[34]*(y[15] - y[21])*((sqrt(pow(y[15], 2) + pow(y[14], 2)) < 0.69999999999999996) ? (
   1.0/(sqrt(pow(y[15], 2) + pow(y[14], 2)) + 0.29999999999999999)
)
: (
   1.0
)); 
data[1038] = p[34]*(-y[14] + y[20])*((sqrt(pow(y[15], 2) + pow(y[14], 2)) < 0.69999999999999996) ? (
   1.0/(sqrt(pow(y[15], 2) + pow(y[14], 2)) + 0.29999999999999999)
)
: (
   1.0
)); 
data[1070] = p[34]*(-2.0*y[16]*u[7] + 2.0*y[20]*u[7] - y[25]*((sqrt(pow(y[17], 2) + pow(y[16], 2)) < 0.69999999999999996) ? (
   1.0/(sqrt(pow(y[17], 2) + pow(y[16], 2)) + 0.29999999999999999)
)
: (
   1.0
)) + (y[17]*y[24] - y[16]*y[25] - y[21]*y[24] + y[20]*y[25])*((sqrt(pow(y[17], 2) + pow(y[16], 2)) < 0.69999999999999996) ? (
   -1.0*y[16]*pow(pow(y[17], 2) + pow(y[16], 2), -0.5)/pow(sqrt(pow(y[17], 2) + pow(y[16], 2)) + 0.29999999999999999, 2)
)
: (
   0
))); 
data[1071] = p[34]*(-2.0*y[17]*u[7] + 2.0*y[21]*u[7] + y[24]*((sqrt(pow(y[17], 2) + pow(y[16], 2)) < 0.69999999999999996) ? (
   1.0/(sqrt(pow(y[17], 2) + pow(y[16], 2)) + 0.29999999999999999)
)
: (
   1.0
)) + (y[17]*y[24] - y[16]*y[25] - y[21]*y[24] + y[20]*y[25])*((sqrt(pow(y[17], 2) + pow(y[16], 2)) < 0.69999999999999996) ? (
   -1.0*y[17]*pow(pow(y[17], 2) + pow(y[16], 2), -0.5)/pow(sqrt(pow(y[17], 2) + pow(y[16], 2)) + 0.29999999999999999, 2)
)
: (
   0
))); 
data[1074] = p[34]*(2.0*y[16]*u[7] - 2.0*y[20]*u[7] + y[25]*((sqrt(pow(y[17], 2) + pow(y[16], 2)) < 0.69999999999999996) ? (
   1.0/(sqrt(pow(y[17], 2) + pow(y[16], 2)) + 0.29999999999999999)
)
: (
   1.0
))); 
data[1075] = p[34]*(2.0*y[17]*u[7] - 2.0*y[21]*u[7] - y[24]*((sqrt(pow(y[17], 2) + pow(y[16], 2)) < 0.69999999999999996) ? (
   1.0/(sqrt(pow(y[17], 2) + pow(y[16], 2)) + 0.29999999999999999)
)
: (
   1.0
))); 
data[1078] = p[34]*(y[17] - y[21])*((sqrt(pow(y[17], 2) + pow(y[16], 2)) < 0.69999999999999996) ? (
   1.0/(sqrt(pow(y[17], 2) + pow(y[16], 2)) + 0.29999999999999999)
)
: (
   1.0
)); 
data[1079] = p[34]*(-y[16] + y[20])*((sqrt(pow(y[17], 2) + pow(y[16], 2)) < 0.69999999999999996) ? (
   1.0/(sqrt(pow(y[17], 2) + pow(y[16], 2)) + 0.29999999999999999)
)
: (
   1.0
)); 
data[1111] = p[34]*(-2.0*y[18]*u[11] + 2.0*y[20]*u[11] - y[27]*((sqrt(pow(y[19], 2) + pow(y[18], 2)) < 0.69999999999999996) ? (
   1.0/(sqrt(pow(y[19], 2) + pow(y[18], 2)) + 0.29999999999999999)
)
: (
   1.0
)) + (y[19]*y[26] - y[18]*y[27] - y[21]*y[26] + y[20]*y[27])*((sqrt(pow(y[19], 2) + pow(y[18], 2)) < 0.69999999999999996) ? (
   -1.0*y[18]*pow(pow(y[19], 2) + pow(y[18], 2), -0.5)/pow(sqrt(pow(y[19], 2) + pow(y[18], 2)) + 0.29999999999999999, 2)
)
: (
   0
))); 
data[1112] = p[34]*(-2.0*y[19]*u[11] + 2.0*y[21]*u[11] + y[26]*((sqrt(pow(y[19], 2) + pow(y[18], 2)) < 0.69999999999999996) ? (
   1.0/(sqrt(pow(y[19], 2) + pow(y[18], 2)) + 0.29999999999999999)
)
: (
   1.0
)) + (y[19]*y[26] - y[18]*y[27] - y[21]*y[26] + y[20]*y[27])*((sqrt(pow(y[19], 2) + pow(y[18], 2)) < 0.69999999999999996) ? (
   -1.0*y[19]*pow(pow(y[19], 2) + pow(y[18], 2), -0.5)/pow(sqrt(pow(y[19], 2) + pow(y[18], 2)) + 0.29999999999999999, 2)
)
: (
   0
))); 
data[1113] = p[34]*(2.0*y[18]*u[11] - 2.0*y[20]*u[11] + y[27]*((sqrt(pow(y[19], 2) + pow(y[18], 2)) < 0.69999999999999996) ? (
   1.0/(sqrt(pow(y[19], 2) + pow(y[18], 2)) + 0.29999999999999999)
)
: (
   1.0
))); 
data[1114] = p[34]*(2.0*y[19]*u[11] - 2.0*y[21]*u[11] - y[26]*((sqrt(pow(y[19], 2) + pow(y[18], 2)) < 0.69999999999999996) ? (
   1.0/(sqrt(pow(y[19], 2) + pow(y[18], 2)) + 0.29999999999999999)
)
: (
   1.0
))); 
data[1119] = p[34]*(y[19] - y[21])*((sqrt(pow(y[19], 2) + pow(y[18], 2)) < 0.69999999999999996) ? (
   1.0/(sqrt(pow(y[19], 2) + pow(y[18], 2)) + 0.29999999999999999)
)
: (
   1.0
)); 
data[1120] = p[34]*(-y[18] + y[20])*((sqrt(pow(y[19], 2) + pow(y[18], 2)) < 0.69999999999999996) ? (
   1.0/(sqrt(pow(y[19], 2) + pow(y[18], 2)) + 0.29999999999999999)
)
: (
   1.0
)); 

}

void de_jac_run_num_eval(double *data,double *x,double *y,double *u,double *p,double Dt){

data[37] = -1; 
data[40] = 0.0009803921568627453; 
data[41] = 0.0039215686274509812; 
data[42] = -0.00049019607843137265; 
data[43] = -0.0019607843137254906; 
data[44] = -0.00049019607843137265; 
data[45] = -0.0019607843137254906; 
data[46] = -0.042452225675707771; 
data[47] = -0.16980890270283108; 
data[48] = 0.042452225675707771; 
data[49] = 0.16980890270283108; 
data[70] = -1; 
data[79] = -0.0039215686274509812; 
data[80] = 0.0009803921568627453; 
data[81] = 0.0019607843137254906; 
data[82] = -0.00049019607843137265; 
data[83] = 0.0019607843137254906; 
data[84] = -0.00049019607843137265; 
data[85] = 0.16980890270283108; 
data[86] = -0.042452225675707771; 
data[87] = -0.16980890270283108; 
data[88] = 0.042452225675707771; 
data[112] = -1; 
data[118] = -0.00049019607843137265; 
data[119] = -0.0019607843137254906; 
data[120] = 0.0009803921568627453; 
data[121] = 0.0039215686274509812; 
data[122] = -0.00049019607843137265; 
data[123] = -0.0019607843137254906; 
data[126] = -0.042452225675707771; 
data[127] = -0.16980890270283108; 
data[128] = 0.042452225675707771; 
data[129] = 0.16980890270283108; 
data[149] = -1; 
data[157] = 0.0019607843137254906; 
data[158] = -0.00049019607843137265; 
data[159] = -0.0039215686274509812; 
data[160] = 0.0009803921568627453; 
data[161] = 0.0019607843137254906; 
data[162] = -0.00049019607843137265; 
data[165] = 0.16980890270283108; 
data[166] = -0.042452225675707771; 
data[167] = -0.16980890270283108; 
data[168] = 0.042452225675707771; 
data[191] = -1; 
data[196] = -0.00049019607843137265; 
data[197] = -0.0019607843137254906; 
data[198] = -0.00049019607843137265; 
data[199] = -0.0019607843137254906; 
data[200] = 0.0009803921568627453; 
data[201] = 0.0039215686274509812; 
data[202] = 0.042452225675707771; 
data[203] = 0.16980890270283108; 
data[206] = -0.042452225675707771; 
data[207] = -0.16980890270283108; 
data[228] = -1; 
data[235] = 0.0019607843137254906; 
data[236] = -0.00049019607843137265; 
data[237] = 0.0019607843137254906; 
data[238] = -0.00049019607843137265; 
data[239] = -0.0039215686274509812; 
data[240] = 0.0009803921568627453; 
data[241] = -0.16980890270283108; 
data[242] = 0.042452225675707771; 
data[245] = 0.16980890270283108; 
data[246] = -0.042452225675707771; 
data[270] = -1; 
data[274] = -0.042452225675707771; 
data[275] = -0.16980890270283108; 
data[278] = 0.042452225675707771; 
data[279] = 0.16980890270283108; 
data[313] = 0.16980890270283108; 
data[314] = -0.042452225675707771; 
data[317] = -0.16980890270283108; 
data[318] = 0.042452225675707771; 
data[352] = 0.042452225675707771; 
data[353] = 0.16980890270283108; 
data[354] = -0.042452225675707771; 
data[355] = -0.16980890270283108; 
data[391] = -0.16980890270283108; 
data[392] = 0.042452225675707771; 
data[393] = 0.16980890270283108; 
data[394] = -0.042452225675707771; 
data[432] = 0.042452225675707771; 
data[433] = 0.16980890270283108; 
data[434] = -0.042452225675707771; 
data[435] = -0.16980890270283108; 
data[471] = -0.16980890270283108; 
data[472] = 0.042452225675707771; 
data[473] = 0.16980890270283108; 
data[474] = -0.042452225675707771; 
data[608] = -1; 
data[648] = -1; 
data[688] = -1; 
data[728] = -1; 
data[768] = -1; 
data[808] = -1; 
data[848] = -1; 
data[888] = -1; 
data[1154] = 1; 
data[1156] = 1; 
data[1158] = 1; 
data[1160] = 1; 
data[1194] = 1; 
data[1196] = 1; 
data[1198] = 1; 
data[1200] = 1; 
data[1210] = -1; 
data[1251] = -1; 
data[1292] = -1; 
data[1328] = -1.0; 
data[1369] = -1.0; 
data[1410] = -1.0; 
data[1480] = -1; 
data[1520] = -1; 

}



/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 8), // void()(double *, double *, double *, double *, double *, double)
/*  1 */ _CFFI_OP(_CFFI_OP_POINTER, 6), // double *
/*  2 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/*  3 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/*  4 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/*  5 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/*  6 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14), // double
/*  7 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  8 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 0), // void
};

static void _cffi_d_de_jac_run_num_eval(double * x0, double * x1, double * x2, double * x3, double * x4, double x5)
{
  de_jac_run_num_eval(x0, x1, x2, x3, x4, x5);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_de_jac_run_num_eval(PyObject *self, PyObject *args)
{
  double * x0;
  double * x1;
  double * x2;
  double * x3;
  double * x4;
  double x5;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;

  if (!PyArg_UnpackTuple(args, "de_jac_run_num_eval", 6, 6, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg3, (char **)&x3);
  if (datasize != 0) {
    x3 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg3, (char **)&x3,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg4, (char **)&x4);
  if (datasize != 0) {
    x4 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg4, (char **)&x4,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x5 = (double)_cffi_to_c_double(arg5);
  if (x5 == (double)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { de_jac_run_num_eval(x0, x1, x2, x3, x4, x5); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_de_jac_run_num_eval _cffi_d_de_jac_run_num_eval
#endif

static void _cffi_d_de_jac_run_up_eval(double * x0, double * x1, double * x2, double * x3, double * x4, double x5)
{
  de_jac_run_up_eval(x0, x1, x2, x3, x4, x5);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_de_jac_run_up_eval(PyObject *self, PyObject *args)
{
  double * x0;
  double * x1;
  double * x2;
  double * x3;
  double * x4;
  double x5;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;

  if (!PyArg_UnpackTuple(args, "de_jac_run_up_eval", 6, 6, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg3, (char **)&x3);
  if (datasize != 0) {
    x3 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg3, (char **)&x3,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg4, (char **)&x4);
  if (datasize != 0) {
    x4 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg4, (char **)&x4,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x5 = (double)_cffi_to_c_double(arg5);
  if (x5 == (double)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { de_jac_run_up_eval(x0, x1, x2, x3, x4, x5); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_de_jac_run_up_eval _cffi_d_de_jac_run_up_eval
#endif

static void _cffi_d_de_jac_run_xy_eval(double * x0, double * x1, double * x2, double * x3, double * x4, double x5)
{
  de_jac_run_xy_eval(x0, x1, x2, x3, x4, x5);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_de_jac_run_xy_eval(PyObject *self, PyObject *args)
{
  double * x0;
  double * x1;
  double * x2;
  double * x3;
  double * x4;
  double x5;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;

  if (!PyArg_UnpackTuple(args, "de_jac_run_xy_eval", 6, 6, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg3, (char **)&x3);
  if (datasize != 0) {
    x3 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg3, (char **)&x3,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg4, (char **)&x4);
  if (datasize != 0) {
    x4 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg4, (char **)&x4,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x5 = (double)_cffi_to_c_double(arg5);
  if (x5 == (double)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { de_jac_run_xy_eval(x0, x1, x2, x3, x4, x5); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_de_jac_run_xy_eval _cffi_d_de_jac_run_xy_eval
#endif

static void _cffi_d_f_run_eval(double * x0, double * x1, double * x2, double * x3, double * x4, double x5)
{
  f_run_eval(x0, x1, x2, x3, x4, x5);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_f_run_eval(PyObject *self, PyObject *args)
{
  double * x0;
  double * x1;
  double * x2;
  double * x3;
  double * x4;
  double x5;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;

  if (!PyArg_UnpackTuple(args, "f_run_eval", 6, 6, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg3, (char **)&x3);
  if (datasize != 0) {
    x3 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg3, (char **)&x3,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg4, (char **)&x4);
  if (datasize != 0) {
    x4 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg4, (char **)&x4,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x5 = (double)_cffi_to_c_double(arg5);
  if (x5 == (double)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { f_run_eval(x0, x1, x2, x3, x4, x5); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_f_run_eval _cffi_d_f_run_eval
#endif

static void _cffi_d_g_run_eval(double * x0, double * x1, double * x2, double * x3, double * x4, double x5)
{
  g_run_eval(x0, x1, x2, x3, x4, x5);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_g_run_eval(PyObject *self, PyObject *args)
{
  double * x0;
  double * x1;
  double * x2;
  double * x3;
  double * x4;
  double x5;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;

  if (!PyArg_UnpackTuple(args, "g_run_eval", 6, 6, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg3, (char **)&x3);
  if (datasize != 0) {
    x3 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg3, (char **)&x3,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg4, (char **)&x4);
  if (datasize != 0) {
    x4 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg4, (char **)&x4,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x5 = (double)_cffi_to_c_double(arg5);
  if (x5 == (double)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { g_run_eval(x0, x1, x2, x3, x4, x5); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_g_run_eval _cffi_d_g_run_eval
#endif

static void _cffi_d_h_eval(double * x0, double * x1, double * x2, double * x3, double * x4, double x5)
{
  h_eval(x0, x1, x2, x3, x4, x5);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_h_eval(PyObject *self, PyObject *args)
{
  double * x0;
  double * x1;
  double * x2;
  double * x3;
  double * x4;
  double x5;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;

  if (!PyArg_UnpackTuple(args, "h_eval", 6, 6, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg3, (char **)&x3);
  if (datasize != 0) {
    x3 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg3, (char **)&x3,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg4, (char **)&x4);
  if (datasize != 0) {
    x4 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg4, (char **)&x4,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x5 = (double)_cffi_to_c_double(arg5);
  if (x5 == (double)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { h_eval(x0, x1, x2, x3, x4, x5); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_h_eval _cffi_d_h_eval
#endif

static const struct _cffi_global_s _cffi_globals[] = {
  { "de_jac_run_num_eval", (void *)_cffi_f_de_jac_run_num_eval, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 0), (void *)_cffi_d_de_jac_run_num_eval },
  { "de_jac_run_up_eval", (void *)_cffi_f_de_jac_run_up_eval, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 0), (void *)_cffi_d_de_jac_run_up_eval },
  { "de_jac_run_xy_eval", (void *)_cffi_f_de_jac_run_xy_eval, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 0), (void *)_cffi_d_de_jac_run_xy_eval },
  { "f_run_eval", (void *)_cffi_f_f_run_eval, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 0), (void *)_cffi_d_f_run_eval },
  { "g_run_eval", (void *)_cffi_f_g_run_eval, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 0), (void *)_cffi_d_g_run_eval },
  { "h_eval", (void *)_cffi_f_h_eval, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 0), (void *)_cffi_d_h_eval },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  NULL,  /* no fields */
  NULL,  /* no struct_unions */
  NULL,  /* no enums */
  NULL,  /* no typenames */
  6,  /* num_globals */
  0,  /* num_struct_unions */
  0,  /* num_enums */
  0,  /* num_typenames */
  NULL,  /* no includes */
  9,  /* num_types */
  0,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit_cigre_eu_lv_ind_run_cffi(const void *p[])
{
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
#if PY_MAJOR_VERSION >= 3
    return NULL;
#endif
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit_cigre_eu_lv_ind_run_cffi(void) { return NULL; }
#  else
     initcigre_eu_lv_ind_run_cffi(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit_cigre_eu_lv_ind_run_cffi(void)
{
  return _cffi_init("cigre_eu_lv_ind_run_cffi", 0x2601, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
initcigre_eu_lv_ind_run_cffi(void)
{
  _cffi_init("cigre_eu_lv_ind_run_cffi", 0x2601, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
