#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   The implementation is messy (issue #350): on Windows, with _MSC_VER,
   we have to define Py_LIMITED_API even before including pyconfig.h.
   In that case, we guess what pyconfig.h will do to the macros above,
   and check our guess after the #include.

   Note that on Windows, with CPython 3.x, you need >= 3.5 and virtualenv
   version >= 16.0.0.  With older versions of either, you don't get a
   copy of PYTHON3.DLL in the virtualenv.  We can't check the version of
   CPython *before* we even include pyconfig.h.  ffi.set_source() puts
   a ``#define _CFFI_NO_LIMITED_API'' at the start of this file if it is
   running on Windows < 3.5, as an attempt at fixing it, but that's
   arguably wrong because it may not be the target version of Python.
   Still better than nothing I guess.  As another workaround, you can
   remove the definition of Py_LIMITED_API here.

   See also 'py_limited_api' in cffi/setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  ifdef _MSC_VER
#    if !defined(_DEBUG) && !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#    include <pyconfig.h>
     /* sanity-check: Py_LIMITED_API will cause crashes if any of these
        are also defined.  Normally, the Python file PC/pyconfig.h does not
        cause any of these to be defined, with the exception that _DEBUG
        causes Py_DEBUG.  Double-check that. */
#    ifdef Py_LIMITED_API
#      if defined(Py_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_DEBUG, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_TRACE_REFS)
#        error "pyconfig.h unexpectedly defines Py_TRACE_REFS, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_REF_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_REF_DEBUG, but Py_LIMITED_API is set"
#      endif
#    endif
#  else
#    include <pyconfig.h>
#    if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>

/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#if PY_MAJOR_VERSION >= 3
# define PyInt_FromLong PyLong_FromLong
#endif

#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyInt_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyInt_FromLong((long)x) :                                    \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyInt_FromLong((long)x) :                                    \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(unsigned int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

union _cffi_union_alignment_u {
    unsigned char m_char;
    unsigned short m_short;
    unsigned int m_int;
    unsigned long m_long;
    unsigned long long m_longlong;
    float m_float;
    double m_double;
    long double m_longdouble;
};

struct _cffi_freeme_s {
    struct _cffi_freeme_s *next;
    union _cffi_union_alignment_u alignment;
};

_CFFI_UNUSED_FN static int
_cffi_convert_array_argument(struct _cffi_ctypedescr *ctptr, PyObject *arg,
                             char **output_data, Py_ssize_t datasize,
                             struct _cffi_freeme_s **freeme)
{
    char *p;
    if (datasize < 0)
        return -1;

    p = *output_data;
    if (p == NULL) {
        struct _cffi_freeme_s *fp = (struct _cffi_freeme_s *)PyObject_Malloc(
            offsetof(struct _cffi_freeme_s, alignment) + (size_t)datasize);
        if (fp == NULL)
            return -1;
        fp->next = *freeme;
        *freeme = fp;
        p = *output_data = (char *)&fp->alignment;
    }
    memset((void *)p, 0, (size_t)datasize);
    return _cffi_convert_array_from_object(p, ctptr, arg);
}

_CFFI_UNUSED_FN static void
_cffi_free_array_arguments(struct _cffi_freeme_s *freeme)
{
    do {
        void *p = (void *)freeme;
        freeme = freeme->next;
        PyObject_Free(p);
    } while (freeme != NULL);
}

/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/

void f_run_eval(double *data,double *x,double *y,double *u,double *p,double Dt){

data[0] = -p[4]*x[0] - y[78] + u[6] + 1; 

}

void g_run_eval(double *data,double *x,double *y,double *u,double *p,double Dt){

data[0] = 0.33248003910113855*y[1] + 0.232643155851495*y[0] - 0.33248003910113855*y[7] - 0.232643155851495*y[6] - y[72]; 
data[1] = 0.232643155851495*y[1] - 0.33248003910113855*y[0] - 0.232643155851495*y[7] + 0.33248003910113855*y[6] - y[75]; 
data[2] = 0.33248003910113855*y[3] + 0.232643155851495*y[2] - 0.33248003910113855*y[9] - 0.232643155851495*y[8] - y[73]; 
data[3] = 0.232643155851495*y[3] - 0.33248003910113855*y[2] - 0.232643155851495*y[9] + 0.33248003910113855*y[8] - y[76]; 
data[4] = 0.33248003910113855*y[5] + 0.232643155851495*y[4] - 0.33248003910113855*y[11] - 0.232643155851495*y[10] - y[74]; 
data[5] = 0.232643155851495*y[5] - 0.33248003910113855*y[4] - 0.232643155851495*y[11] + 0.33248003910113855*y[10] - y[77]; 
data[6] = -0.33248003910113855*y[1] - 0.232643155851495*y[0] + 0.54460531291679715*y[7] + 0.38107159465267509*y[6] - 0.21212527381565857*y[13] - 0.14842843880118009*y[12]; 
data[7] = -0.232643155851495*y[1] + 0.33248003910113855*y[0] + 0.38107159465267509*y[7] - 0.54460531291679715*y[6] - 0.14842843880118009*y[13] + 0.21212527381565857*y[12]; 
data[8] = -0.33248003910113855*y[3] - 0.232643155851495*y[2] + 0.54460531291679715*y[9] + 0.38107159465267509*y[8] - 0.21212527381565857*y[15] - 0.14842843880118009*y[14]; 
data[9] = -0.232643155851495*y[3] + 0.33248003910113855*y[2] + 0.38107159465267509*y[9] - 0.54460531291679715*y[8] - 0.14842843880118009*y[15] + 0.21212527381565857*y[14]; 
data[10] = -0.33248003910113855*y[5] - 0.232643155851495*y[4] + 0.54460531291679715*y[11] + 0.38107159465267509*y[10] - 0.21212527381565857*y[17] - 0.14842843880118009*y[16]; 
data[11] = -0.232643155851495*y[5] + 0.33248003910113855*y[4] + 0.38107159465267509*y[11] - 0.54460531291679715*y[10] - 0.14842843880118009*y[17] + 0.21212527381565857*y[16]; 
data[12] = -0.21212527381565857*y[7] - 0.14842843880118009*y[6] + 2.470390074076128*y[13] + 1.7285829987599723*y[12] - 1.5370388692872305*y[19] - 1.0754978680347802*y[18] - 0.72122593097323895*y[43] - 0.50465669192401219*y[42]; 
data[13] = -0.14842843880118009*y[7] + 0.21212527381565857*y[6] + 1.7285829987599723*y[13] - 2.470390074076128*y[12] - 1.0754978680347802*y[19] + 1.5370388692872305*y[18] - 0.50465669192401219*y[43] + 0.72122593097323895*y[42]; 
data[14] = -0.21212527381565857*y[9] - 0.14842843880118009*y[8] + 2.470390074076128*y[15] + 1.7285829987599723*y[14] - 1.5370388692872305*y[21] - 1.0754978680347802*y[20] - 0.72122593097323895*y[45] - 0.50465669192401219*y[44]; 
data[15] = -0.14842843880118009*y[9] + 0.21212527381565857*y[8] + 1.7285829987599723*y[15] - 2.470390074076128*y[14] - 1.0754978680347802*y[21] + 1.5370388692872305*y[20] - 0.50465669192401219*y[45] + 0.72122593097323895*y[44]; 
data[16] = -0.21212527381565857*y[11] - 0.14842843880118009*y[10] + 2.470390074076128*y[17] + 1.7285829987599726*y[16] - 1.5370388692872305*y[23] - 1.0754978680347802*y[22] - 0.72122593097323895*y[47] - 0.50465669192401219*y[46]; 
data[17] = -0.14842843880118009*y[11] + 0.21212527381565857*y[10] + 1.7285829987599726*y[17] - 2.470390074076128*y[16] - 1.0754978680347802*y[23] + 1.5370388692872305*y[22] - 0.50465669192401219*y[47] + 0.72122593097323895*y[46]; 
data[18] = -1.5370388692872305*y[13] - 1.0754978680347802*y[12] + 3.2113133519036783*y[19] + 2.2470223314298083*y[18] - 1.6742744826164477*y[25] - 1.1715244633950284*y[24]; 
data[19] = -1.0754978680347802*y[13] + 1.5370388692872305*y[12] + 2.2470223314298083*y[19] - 3.2113133519036783*y[18] - 1.1715244633950284*y[25] + 1.6742744826164477*y[24]; 
data[20] = -1.5370388692872305*y[15] - 1.0754978680347802*y[14] + 3.2113133519036783*y[21] + 2.2470223314298083*y[20] - 1.6742744826164477*y[27] - 1.1715244633950284*y[26]; 
data[21] = -1.0754978680347802*y[15] + 1.5370388692872305*y[14] + 2.2470223314298083*y[21] - 3.2113133519036783*y[20] - 1.1715244633950284*y[27] + 1.6742744826164477*y[26]; 
data[22] = -1.5370388692872305*y[17] - 1.0754978680347802*y[16] + 3.2113133519036783*y[23] + 2.2470223314298083*y[22] - 1.6742744826164477*y[29] - 1.1715244633950284*y[28]; 
data[23] = -1.0754978680347802*y[17] + 1.5370388692872305*y[16] + 2.2470223314298083*y[23] - 3.2113133519036783*y[22] - 1.1715244633950284*y[29] + 1.6742744826164477*y[28]; 
data[24] = -1.6742744826164477*y[19] - 1.1715244633950284*y[18] + 2.283101567204247*y[25] + 1.5975333591750389*y[24] - 0.60882708458779922*y[31] - 0.42600889578001044*y[30]; 
data[25] = -1.1715244633950284*y[19] + 1.6742744826164477*y[18] + 1.5975333591750389*y[25] - 2.283101567204247*y[24] - 0.42600889578001044*y[31] + 0.60882708458779922*y[30]; 
data[26] = -1.6742744826164477*y[21] - 1.1715244633950284*y[20] + 2.283101567204247*y[27] + 1.5975333591750389*y[26] - 0.60882708458779922*y[33] - 0.42600889578001044*y[32]; 
data[27] = -1.1715244633950284*y[21] + 1.6742744826164477*y[20] + 1.5975333591750389*y[27] - 2.283101567204247*y[26] - 0.42600889578001044*y[33] + 0.60882708458779922*y[32]; 
data[28] = -1.6742744826164477*y[23] - 1.1715244633950284*y[22] + 2.283101567204247*y[29] + 1.5975333591750389*y[28] - 0.60882708458779922*y[35] - 0.42600889578001044*y[34]; 
data[29] = -1.1715244633950284*y[23] + 1.6742744826164477*y[22] + 1.5975333591750389*y[29] - 2.283101567204247*y[28] - 0.42600889578001044*y[35] + 0.60882708458779922*y[34]; 
data[30] = -0.60882708458779922*y[25] - 0.42600889578001044*y[24] + 4.5154675440261771*y[31] + 3.1595659770350766*y[30] - 3.9066404594383779*y[37] - 2.733557081255066*y[36]; 
data[31] = -0.42600889578001044*y[25] + 0.60882708458779922*y[24] + 3.1595659770350766*y[31] - 4.5154675440261771*y[30] - 2.733557081255066*y[37] + 3.9066404594383779*y[36]; 
data[32] = -0.60882708458779922*y[27] - 0.42600889578001044*y[26] + 4.5154675440261771*y[33] + 3.1595659770350766*y[32] - 3.9066404594383779*y[39] - 2.733557081255066*y[38]; 
data[33] = -0.42600889578001044*y[27] + 0.60882708458779922*y[26] + 3.1595659770350766*y[33] - 4.5154675440261771*y[32] - 2.733557081255066*y[39] + 3.9066404594383779*y[38]; 
data[34] = -0.60882708458779922*y[29] - 0.42600889578001044*y[28] + 4.5154675440261771*y[35] + 3.1595659770350766*y[34] - 3.9066404594383779*y[41] - 2.733557081255066*y[40]; 
data[35] = -0.42600889578001044*y[29] + 0.60882708458779922*y[28] + 3.1595659770350766*y[35] - 4.5154675440261771*y[34] - 2.733557081255066*y[41] + 3.9066404594383779*y[40]; 
data[36] = -3.9066404594383779*y[31] - 2.733557081255066*y[30] + 4.468073818878624*y[37] + 3.1264036079025006*y[36] - 0.56143335944024586*y[43] - 0.39284652664743452*y[42]; 
data[37] = -2.733557081255066*y[31] + 3.9066404594383779*y[30] + 3.1264036079025006*y[37] - 4.468073818878624*y[36] - 0.39284652664743452*y[43] + 0.56143335944024586*y[42]; 
data[38] = -3.9066404594383779*y[33] - 2.733557081255066*y[32] + 4.468073818878624*y[39] + 3.1264036079025006*y[38] - 0.56143335944024586*y[45] - 0.39284652664743452*y[44]; 
data[39] = -2.733557081255066*y[33] + 3.9066404594383779*y[32] + 3.1264036079025006*y[39] - 4.468073818878624*y[38] - 0.39284652664743452*y[45] + 0.56143335944024586*y[44]; 
data[40] = -3.9066404594383779*y[35] - 2.733557081255066*y[34] + 4.468073818878624*y[41] + 3.1264036079025006*y[40] - 0.56143335944024586*y[47] - 0.39284652664743452*y[46]; 
data[41] = -2.733557081255066*y[35] + 3.9066404594383779*y[34] + 3.1264036079025006*y[41] - 4.468073818878624*y[40] - 0.39284652664743452*y[47] + 0.56143335944024586*y[46]; 
data[42] = -0.72122593097323895*y[13] - 0.50465669192401219*y[12] - 0.56143335944024586*y[37] - 0.39284652664743452*y[36] + 4.2126396349922688*y[43] + 2.9476710295127462*y[42] - 2.9299803445787838*y[49] - 2.0501678109412995*y[48]; 
data[43] = -0.50465669192401219*y[13] + 0.72122593097323895*y[12] - 0.39284652664743452*y[37] + 0.56143335944024586*y[36] + 2.9476710295127462*y[43] - 4.2126396349922688*y[42] - 2.0501678109412995*y[49] + 2.9299803445787838*y[48]; 
data[44] = -0.72122593097323895*y[15] - 0.50465669192401219*y[14] - 0.56143335944024586*y[39] - 0.39284652664743452*y[38] + 4.2126396349922688*y[45] + 2.9476710295127462*y[44] - 2.9299803445787838*y[51] - 2.0501678109412995*y[50]; 
data[45] = -0.50465669192401219*y[15] + 0.72122593097323895*y[14] - 0.39284652664743452*y[39] + 0.56143335944024586*y[38] + 2.9476710295127462*y[45] - 4.2126396349922688*y[44] - 2.0501678109412995*y[51] + 2.9299803445787838*y[50]; 
data[46] = -0.72122593097323895*y[17] - 0.50465669192401219*y[16] - 0.56143335944024586*y[41] - 0.39284652664743452*y[40] + 4.2126396349922688*y[47] + 2.9476710295127462*y[46] - 2.9299803445787838*y[53] - 2.0501678109412995*y[52]; 
data[47] = -0.50465669192401219*y[17] + 0.72122593097323895*y[16] - 0.39284652664743452*y[41] + 0.56143335944024586*y[40] + 2.9476710295127462*y[47] - 4.2126396349922688*y[46] - 2.0501678109412995*y[53] + 2.9299803445787838*y[52]; 
data[48] = -2.9299803445787838*y[43] - 2.0501678109412995*y[42] + 4.1476345137543822*y[49] + 2.9021856025013202*y[48] - 1.2176541691755984*y[55] - 0.85201779156002089*y[54]; 
data[49] = -2.0501678109412995*y[43] + 2.9299803445787838*y[42] + 2.9021856025013202*y[49] - 4.1476345137543822*y[48] - 0.85201779156002089*y[55] + 1.2176541691755984*y[54]; 
data[50] = -2.9299803445787838*y[45] - 2.0501678109412995*y[44] + 4.1476345137543822*y[51] + 2.9021856025013202*y[50] - 1.2176541691755984*y[57] - 0.85201779156002089*y[56]; 
data[51] = -2.0501678109412995*y[45] + 2.9299803445787838*y[44] + 2.9021856025013202*y[51] - 4.1476345137543822*y[50] - 0.85201779156002089*y[57] + 1.2176541691755984*y[56]; 
data[52] = -2.9299803445787838*y[47] - 2.0501678109412995*y[46] + 4.1476345137543822*y[53] + 2.9021856025013202*y[52] - 1.2176541691755984*y[59] - 0.85201779156002089*y[58]; 
data[53] = -2.0501678109412995*y[47] + 2.9299803445787838*y[46] + 2.9021856025013202*y[53] - 4.1476345137543822*y[52] - 0.85201779156002089*y[59] + 1.2176541691755984*y[58]; 
data[54] = -1.2176541691755984*y[49] - 0.85201779156002089*y[48] + 4.0588472305853278*y[55] + 2.8400593052000689*y[54] - 2.8411930614097294*y[61] - 1.9880415136400482*y[60]; 
data[55] = -0.85201779156002089*y[49] + 1.2176541691755984*y[48] + 2.8400593052000689*y[55] - 4.0588472305853278*y[54] - 1.9880415136400482*y[61] + 2.8411930614097294*y[60]; 
data[56] = -1.2176541691755984*y[51] - 0.85201779156002089*y[50] + 4.0588472305853278*y[57] + 2.8400593052000689*y[56] - 2.8411930614097294*y[63] - 1.9880415136400482*y[62]; 
data[57] = -0.85201779156002089*y[51] + 1.2176541691755984*y[50] + 2.8400593052000689*y[57] - 4.0588472305853278*y[56] - 1.9880415136400482*y[63] + 2.8411930614097294*y[62]; 
data[58] = -1.2176541691755984*y[53] - 0.85201779156002089*y[52] + 4.0588472305853278*y[59] + 2.8400593052000689*y[58] - 2.8411930614097294*y[65] - 1.9880415136400482*y[64]; 
data[59] = -0.85201779156002089*y[53] + 1.2176541691755984*y[52] + 2.8400593052000689*y[59] - 4.0588472305853278*y[58] - 1.9880415136400482*y[65] + 2.8411930614097294*y[64]; 
data[60] = -2.8411930614097294*y[55] - 1.9880415136400482*y[54] + 2.8411930614097294*y[61] + 1.9880415136400482*y[60] - y[66]; 
data[61] = -1.9880415136400482*y[55] + 2.8411930614097294*y[54] + 1.9880415136400482*y[61] - 2.8411930614097294*y[60] - y[67]; 
data[62] = -2.8411930614097294*y[57] - 1.9880415136400482*y[56] + 2.8411930614097294*y[63] + 1.9880415136400482*y[62] - y[68]; 
data[63] = -1.9880415136400482*y[57] + 2.8411930614097294*y[56] + 1.9880415136400482*y[63] - 2.8411930614097294*y[62] - y[69]; 
data[64] = -2.8411930614097294*y[59] - 1.9880415136400482*y[58] + 2.8411930614097294*y[65] + 1.9880415136400482*y[64] - y[70]; 
data[65] = -1.9880415136400482*y[59] + 2.8411930614097294*y[58] + 1.9880415136400482*y[65] - 2.8411930614097294*y[64] - y[71]; 
data[66] = y[61]*y[67] + y[60]*y[66] + (1.0/3.0)*u[0]; 
data[67] = y[63]*y[69] + y[62]*y[68] + (1.0/3.0)*u[0]; 
data[68] = y[61]*y[66] - y[60]*y[67] + (1.0/3.0)*u[1]; 
data[69] = y[63]*y[68] - y[62]*y[69] + (1.0/3.0)*u[1]; 
data[70] = y[66] + y[68] + y[70]; 
data[71] = y[67] + y[69] + y[71]; 
data[72] = -p[1]*y[72] - y[0] + 1.0*p[0]*y[75] + u[2]*cos(u[5]); 
data[73] = -p[1]*y[73] - y[2] + 1.0*p[0]*y[76] + u[3]*cos(u[5] - 2.0943951023931953); 
data[74] = -p[1]*y[74] - y[4] + 1.0*p[0]*y[77] + u[4]*cos(u[5] - 4.1887902047863905); 
data[75] = -1.0*p[1]*y[75] - 1.0*y[1] - 1.0*p[0]*y[72] + 1.0*u[2]*sin(u[5]); 
data[76] = -1.0*p[1]*y[76] - 1.0*y[3] - 1.0*p[0]*y[73] + 1.0*u[3]*sin(u[5] - 2.0943951023931953); 
data[77] = -1.0*p[1]*y[77] - 1.0*y[5] - 1.0*p[0]*y[74] + 1.0*u[4]*sin(u[5] - 4.1887902047863905); 
data[78] = 1.0 - y[78]; 
data[79] = p[3]*x[0] + p[2]*(1 - y[78]) - y[79]; 

}

void h_eval(double *data,double *x,double *y,double *u,double *p,double Dt){

data[0] = sqrt(1.0*pow(y[75], 2) + pow(y[72], 2)); 
data[1] = sqrt(1.0*pow(y[76], 2) + pow(y[73], 2)); 
data[2] = sqrt(1.0*pow(y[77], 2) + pow(y[74], 2)); 
data[3] = 1.0*y[1]*y[75] + y[0]*y[72] + 1.0*y[3]*y[76] + y[2]*y[73] + 1.0*y[5]*y[77] + y[4]*y[74]; 
data[4] = 1.0*y[1]*y[72] - 1.0*y[0]*y[75] + 1.0*y[3]*y[73] - 1.0*y[2]*y[76] + 1.0*y[5]*y[74] - 1.0*y[4]*y[77]; 
data[5] = x[0]; 
data[6] = u[6]; 

}

void de_jac_run_up_eval(double *data,double *x,double *y,double *u,double *p,double Dt){

data[0] = -p[4]; 
data[5986] = -p[1]; 
data[5989] = 1.0*p[0]; 
data[6068] = -p[1]; 
data[6071] = 1.0*p[0]; 
data[6150] = -p[1]; 
data[6153] = 1.0*p[0]; 
data[6229] = -1.0*p[0]; 
data[6232] = -1.0*p[1]; 
data[6311] = -1.0*p[0]; 
data[6314] = -1.0*p[1]; 
data[6393] = -1.0*p[0]; 
data[6396] = -1.0*p[1]; 
data[6480] = p[3]; 
data[6559] = -p[2]; 

}

void de_jac_run_xy_eval(double *data,double *x,double *y,double *u,double *p,double Dt){

data[5488] = y[66]; 
data[5489] = y[67]; 
data[5494] = y[60]; 
data[5495] = y[61]; 
data[5571] = y[68]; 
data[5572] = y[69]; 
data[5577] = y[62]; 
data[5578] = y[63]; 
data[5650] = -y[67]; 
data[5651] = y[66]; 
data[5656] = y[61]; 
data[5657] = -y[60]; 
data[5733] = -y[69]; 
data[5734] = y[68]; 
data[5739] = y[63]; 
data[5740] = -y[62]; 

}

void de_jac_run_num_eval(double *data,double *x,double *y,double *u,double *p,double Dt){

data[79] = -1; 
data[82] = 0.232643155851495; 
data[83] = 0.33248003910113855; 
data[88] = -0.232643155851495; 
data[89] = -0.33248003910113855; 
data[154] = -1; 
data[163] = -0.33248003910113855; 
data[164] = 0.232643155851495; 
data[169] = 0.33248003910113855; 
data[170] = -0.232643155851495; 
data[238] = -1; 
data[246] = 0.232643155851495; 
data[247] = 0.33248003910113855; 
data[252] = -0.232643155851495; 
data[253] = -0.33248003910113855; 
data[317] = -1; 
data[327] = -0.33248003910113855; 
data[328] = 0.232643155851495; 
data[333] = 0.33248003910113855; 
data[334] = -0.232643155851495; 
data[401] = -1; 
data[410] = 0.232643155851495; 
data[411] = 0.33248003910113855; 
data[416] = -0.232643155851495; 
data[417] = -0.33248003910113855; 
data[480] = -1; 
data[491] = -0.33248003910113855; 
data[492] = 0.232643155851495; 
data[497] = 0.33248003910113855; 
data[498] = -0.232643155851495; 
data[564] = -1; 
data[568] = -0.232643155851495; 
data[569] = -0.33248003910113855; 
data[574] = 0.38107159465267509; 
data[575] = 0.54460531291679715; 
data[580] = -0.14842843880118009; 
data[581] = -0.21212527381565857; 
data[649] = 0.33248003910113855; 
data[650] = -0.232643155851495; 
data[655] = -0.54460531291679715; 
data[656] = 0.38107159465267509; 
data[661] = 0.21212527381565857; 
data[662] = -0.14842843880118009; 
data[732] = -0.232643155851495; 
data[733] = -0.33248003910113855; 
data[738] = 0.38107159465267509; 
data[739] = 0.54460531291679715; 
data[744] = -0.14842843880118009; 
data[745] = -0.21212527381565857; 
data[813] = 0.33248003910113855; 
data[814] = -0.232643155851495; 
data[819] = -0.54460531291679715; 
data[820] = 0.38107159465267509; 
data[825] = 0.21212527381565857; 
data[826] = -0.14842843880118009; 
data[896] = -0.232643155851495; 
data[897] = -0.33248003910113855; 
data[902] = 0.38107159465267509; 
data[903] = 0.54460531291679715; 
data[908] = -0.14842843880118009; 
data[909] = -0.21212527381565857; 
data[977] = 0.33248003910113855; 
data[978] = -0.232643155851495; 
data[983] = -0.54460531291679715; 
data[984] = 0.38107159465267509; 
data[989] = 0.21212527381565857; 
data[990] = -0.14842843880118009; 
data[1060] = -0.14842843880118009; 
data[1061] = -0.21212527381565857; 
data[1066] = 1.7285829987599723; 
data[1067] = 2.470390074076128; 
data[1072] = -1.0754978680347802; 
data[1073] = -1.5370388692872305; 
data[1096] = -0.50465669192401219; 
data[1097] = -0.72122593097323895; 
data[1141] = 0.21212527381565857; 
data[1142] = -0.14842843880118009; 
data[1147] = -2.470390074076128; 
data[1148] = 1.7285829987599723; 
data[1153] = 1.5370388692872305; 
data[1154] = -1.0754978680347802; 
data[1177] = 0.72122593097323895; 
data[1178] = -0.50465669192401219; 
data[1224] = -0.14842843880118009; 
data[1225] = -0.21212527381565857; 
data[1230] = 1.7285829987599723; 
data[1231] = 2.470390074076128; 
data[1236] = -1.0754978680347802; 
data[1237] = -1.5370388692872305; 
data[1260] = -0.50465669192401219; 
data[1261] = -0.72122593097323895; 
data[1305] = 0.21212527381565857; 
data[1306] = -0.14842843880118009; 
data[1311] = -2.470390074076128; 
data[1312] = 1.7285829987599723; 
data[1317] = 1.5370388692872305; 
data[1318] = -1.0754978680347802; 
data[1341] = 0.72122593097323895; 
data[1342] = -0.50465669192401219; 
data[1388] = -0.14842843880118009; 
data[1389] = -0.21212527381565857; 
data[1394] = 1.7285829987599726; 
data[1395] = 2.470390074076128; 
data[1400] = -1.0754978680347802; 
data[1401] = -1.5370388692872305; 
data[1424] = -0.50465669192401219; 
data[1425] = -0.72122593097323895; 
data[1469] = 0.21212527381565857; 
data[1470] = -0.14842843880118009; 
data[1475] = -2.470390074076128; 
data[1476] = 1.7285829987599726; 
data[1481] = 1.5370388692872305; 
data[1482] = -1.0754978680347802; 
data[1505] = 0.72122593097323895; 
data[1506] = -0.50465669192401219; 
data[1552] = -1.0754978680347802; 
data[1553] = -1.5370388692872305; 
data[1558] = 2.2470223314298083; 
data[1559] = 3.2113133519036783; 
data[1564] = -1.1715244633950284; 
data[1565] = -1.6742744826164477; 
data[1633] = 1.5370388692872305; 
data[1634] = -1.0754978680347802; 
data[1639] = -3.2113133519036783; 
data[1640] = 2.2470223314298083; 
data[1645] = 1.6742744826164477; 
data[1646] = -1.1715244633950284; 
data[1716] = -1.0754978680347802; 
data[1717] = -1.5370388692872305; 
data[1722] = 2.2470223314298083; 
data[1723] = 3.2113133519036783; 
data[1728] = -1.1715244633950284; 
data[1729] = -1.6742744826164477; 
data[1797] = 1.5370388692872305; 
data[1798] = -1.0754978680347802; 
data[1803] = -3.2113133519036783; 
data[1804] = 2.2470223314298083; 
data[1809] = 1.6742744826164477; 
data[1810] = -1.1715244633950284; 
data[1880] = -1.0754978680347802; 
data[1881] = -1.5370388692872305; 
data[1886] = 2.2470223314298083; 
data[1887] = 3.2113133519036783; 
data[1892] = -1.1715244633950284; 
data[1893] = -1.6742744826164477; 
data[1961] = 1.5370388692872305; 
data[1962] = -1.0754978680347802; 
data[1967] = -3.2113133519036783; 
data[1968] = 2.2470223314298083; 
data[1973] = 1.6742744826164477; 
data[1974] = -1.1715244633950284; 
data[2044] = -1.1715244633950284; 
data[2045] = -1.6742744826164477; 
data[2050] = 1.5975333591750389; 
data[2051] = 2.283101567204247; 
data[2056] = -0.42600889578001044; 
data[2057] = -0.60882708458779922; 
data[2125] = 1.6742744826164477; 
data[2126] = -1.1715244633950284; 
data[2131] = -2.283101567204247; 
data[2132] = 1.5975333591750389; 
data[2137] = 0.60882708458779922; 
data[2138] = -0.42600889578001044; 
data[2208] = -1.1715244633950284; 
data[2209] = -1.6742744826164477; 
data[2214] = 1.5975333591750389; 
data[2215] = 2.283101567204247; 
data[2220] = -0.42600889578001044; 
data[2221] = -0.60882708458779922; 
data[2289] = 1.6742744826164477; 
data[2290] = -1.1715244633950284; 
data[2295] = -2.283101567204247; 
data[2296] = 1.5975333591750389; 
data[2301] = 0.60882708458779922; 
data[2302] = -0.42600889578001044; 
data[2372] = -1.1715244633950284; 
data[2373] = -1.6742744826164477; 
data[2378] = 1.5975333591750389; 
data[2379] = 2.283101567204247; 
data[2384] = -0.42600889578001044; 
data[2385] = -0.60882708458779922; 
data[2453] = 1.6742744826164477; 
data[2454] = -1.1715244633950284; 
data[2459] = -2.283101567204247; 
data[2460] = 1.5975333591750389; 
data[2465] = 0.60882708458779922; 
data[2466] = -0.42600889578001044; 
data[2536] = -0.42600889578001044; 
data[2537] = -0.60882708458779922; 
data[2542] = 3.1595659770350766; 
data[2543] = 4.5154675440261771; 
data[2548] = -2.733557081255066; 
data[2549] = -3.9066404594383779; 
data[2617] = 0.60882708458779922; 
data[2618] = -0.42600889578001044; 
data[2623] = -4.5154675440261771; 
data[2624] = 3.1595659770350766; 
data[2629] = 3.9066404594383779; 
data[2630] = -2.733557081255066; 
data[2700] = -0.42600889578001044; 
data[2701] = -0.60882708458779922; 
data[2706] = 3.1595659770350766; 
data[2707] = 4.5154675440261771; 
data[2712] = -2.733557081255066; 
data[2713] = -3.9066404594383779; 
data[2781] = 0.60882708458779922; 
data[2782] = -0.42600889578001044; 
data[2787] = -4.5154675440261771; 
data[2788] = 3.1595659770350766; 
data[2793] = 3.9066404594383779; 
data[2794] = -2.733557081255066; 
data[2864] = -0.42600889578001044; 
data[2865] = -0.60882708458779922; 
data[2870] = 3.1595659770350766; 
data[2871] = 4.5154675440261771; 
data[2876] = -2.733557081255066; 
data[2877] = -3.9066404594383779; 
data[2945] = 0.60882708458779922; 
data[2946] = -0.42600889578001044; 
data[2951] = -4.5154675440261771; 
data[2952] = 3.1595659770350766; 
data[2957] = 3.9066404594383779; 
data[2958] = -2.733557081255066; 
data[3028] = -2.733557081255066; 
data[3029] = -3.9066404594383779; 
data[3034] = 3.1264036079025006; 
data[3035] = 4.468073818878624; 
data[3040] = -0.39284652664743452; 
data[3041] = -0.56143335944024586; 
data[3109] = 3.9066404594383779; 
data[3110] = -2.733557081255066; 
data[3115] = -4.468073818878624; 
data[3116] = 3.1264036079025006; 
data[3121] = 0.56143335944024586; 
data[3122] = -0.39284652664743452; 
data[3192] = -2.733557081255066; 
data[3193] = -3.9066404594383779; 
data[3198] = 3.1264036079025006; 
data[3199] = 4.468073818878624; 
data[3204] = -0.39284652664743452; 
data[3205] = -0.56143335944024586; 
data[3273] = 3.9066404594383779; 
data[3274] = -2.733557081255066; 
data[3279] = -4.468073818878624; 
data[3280] = 3.1264036079025006; 
data[3285] = 0.56143335944024586; 
data[3286] = -0.39284652664743452; 
data[3356] = -2.733557081255066; 
data[3357] = -3.9066404594383779; 
data[3362] = 3.1264036079025006; 
data[3363] = 4.468073818878624; 
data[3368] = -0.39284652664743452; 
data[3369] = -0.56143335944024586; 
data[3437] = 3.9066404594383779; 
data[3438] = -2.733557081255066; 
data[3443] = -4.468073818878624; 
data[3444] = 3.1264036079025006; 
data[3449] = 0.56143335944024586; 
data[3450] = -0.39284652664743452; 
data[3496] = -0.50465669192401219; 
data[3497] = -0.72122593097323895; 
data[3520] = -0.39284652664743452; 
data[3521] = -0.56143335944024586; 
data[3526] = 2.9476710295127462; 
data[3527] = 4.2126396349922688; 
data[3532] = -2.0501678109412995; 
data[3533] = -2.9299803445787838; 
data[3577] = 0.72122593097323895; 
data[3578] = -0.50465669192401219; 
data[3601] = 0.56143335944024586; 
data[3602] = -0.39284652664743452; 
data[3607] = -4.2126396349922688; 
data[3608] = 2.9476710295127462; 
data[3613] = 2.9299803445787838; 
data[3614] = -2.0501678109412995; 
data[3660] = -0.50465669192401219; 
data[3661] = -0.72122593097323895; 
data[3684] = -0.39284652664743452; 
data[3685] = -0.56143335944024586; 
data[3690] = 2.9476710295127462; 
data[3691] = 4.2126396349922688; 
data[3696] = -2.0501678109412995; 
data[3697] = -2.9299803445787838; 
data[3741] = 0.72122593097323895; 
data[3742] = -0.50465669192401219; 
data[3765] = 0.56143335944024586; 
data[3766] = -0.39284652664743452; 
data[3771] = -4.2126396349922688; 
data[3772] = 2.9476710295127462; 
data[3777] = 2.9299803445787838; 
data[3778] = -2.0501678109412995; 
data[3824] = -0.50465669192401219; 
data[3825] = -0.72122593097323895; 
data[3848] = -0.39284652664743452; 
data[3849] = -0.56143335944024586; 
data[3854] = 2.9476710295127462; 
data[3855] = 4.2126396349922688; 
data[3860] = -2.0501678109412995; 
data[3861] = -2.9299803445787838; 
data[3905] = 0.72122593097323895; 
data[3906] = -0.50465669192401219; 
data[3929] = 0.56143335944024586; 
data[3930] = -0.39284652664743452; 
data[3935] = -4.2126396349922688; 
data[3936] = 2.9476710295127462; 
data[3941] = 2.9299803445787838; 
data[3942] = -2.0501678109412995; 
data[4012] = -2.0501678109412995; 
data[4013] = -2.9299803445787838; 
data[4018] = 2.9021856025013202; 
data[4019] = 4.1476345137543822; 
data[4024] = -0.85201779156002089; 
data[4025] = -1.2176541691755984; 
data[4093] = 2.9299803445787838; 
data[4094] = -2.0501678109412995; 
data[4099] = -4.1476345137543822; 
data[4100] = 2.9021856025013202; 
data[4105] = 1.2176541691755984; 
data[4106] = -0.85201779156002089; 
data[4176] = -2.0501678109412995; 
data[4177] = -2.9299803445787838; 
data[4182] = 2.9021856025013202; 
data[4183] = 4.1476345137543822; 
data[4188] = -0.85201779156002089; 
data[4189] = -1.2176541691755984; 
data[4257] = 2.9299803445787838; 
data[4258] = -2.0501678109412995; 
data[4263] = -4.1476345137543822; 
data[4264] = 2.9021856025013202; 
data[4269] = 1.2176541691755984; 
data[4270] = -0.85201779156002089; 
data[4340] = -2.0501678109412995; 
data[4341] = -2.9299803445787838; 
data[4346] = 2.9021856025013202; 
data[4347] = 4.1476345137543822; 
data[4352] = -0.85201779156002089; 
data[4353] = -1.2176541691755984; 
data[4421] = 2.9299803445787838; 
data[4422] = -2.0501678109412995; 
data[4427] = -4.1476345137543822; 
data[4428] = 2.9021856025013202; 
data[4433] = 1.2176541691755984; 
data[4434] = -0.85201779156002089; 
data[4504] = -0.85201779156002089; 
data[4505] = -1.2176541691755984; 
data[4510] = 2.8400593052000689; 
data[4511] = 4.0588472305853278; 
data[4516] = -1.9880415136400482; 
data[4517] = -2.8411930614097294; 
data[4585] = 1.2176541691755984; 
data[4586] = -0.85201779156002089; 
data[4591] = -4.0588472305853278; 
data[4592] = 2.8400593052000689; 
data[4597] = 2.8411930614097294; 
data[4598] = -1.9880415136400482; 
data[4668] = -0.85201779156002089; 
data[4669] = -1.2176541691755984; 
data[4674] = 2.8400593052000689; 
data[4675] = 4.0588472305853278; 
data[4680] = -1.9880415136400482; 
data[4681] = -2.8411930614097294; 
data[4749] = 1.2176541691755984; 
data[4750] = -0.85201779156002089; 
data[4755] = -4.0588472305853278; 
data[4756] = 2.8400593052000689; 
data[4761] = 2.8411930614097294; 
data[4762] = -1.9880415136400482; 
data[4832] = -0.85201779156002089; 
data[4833] = -1.2176541691755984; 
data[4838] = 2.8400593052000689; 
data[4839] = 4.0588472305853278; 
data[4844] = -1.9880415136400482; 
data[4845] = -2.8411930614097294; 
data[4913] = 1.2176541691755984; 
data[4914] = -0.85201779156002089; 
data[4919] = -4.0588472305853278; 
data[4920] = 2.8400593052000689; 
data[4925] = 2.8411930614097294; 
data[4926] = -1.9880415136400482; 
data[4996] = -1.9880415136400482; 
data[4997] = -2.8411930614097294; 
data[5002] = 1.9880415136400482; 
data[5003] = 2.8411930614097294; 
data[5008] = -1; 
data[5077] = 2.8411930614097294; 
data[5078] = -1.9880415136400482; 
data[5083] = -2.8411930614097294; 
data[5084] = 1.9880415136400482; 
data[5090] = -1; 
data[5160] = -1.9880415136400482; 
data[5161] = -2.8411930614097294; 
data[5166] = 1.9880415136400482; 
data[5167] = 2.8411930614097294; 
data[5172] = -1; 
data[5241] = 2.8411930614097294; 
data[5242] = -1.9880415136400482; 
data[5247] = -2.8411930614097294; 
data[5248] = 1.9880415136400482; 
data[5254] = -1; 
data[5324] = -1.9880415136400482; 
data[5325] = -2.8411930614097294; 
data[5330] = 1.9880415136400482; 
data[5331] = 2.8411930614097294; 
data[5336] = -1; 
data[5405] = 2.8411930614097294; 
data[5406] = -1.9880415136400482; 
data[5411] = -2.8411930614097294; 
data[5412] = 1.9880415136400482; 
data[5418] = -1; 
data[5818] = 1; 
data[5820] = 1; 
data[5822] = 1; 
data[5900] = 1; 
data[5902] = 1; 
data[5904] = 1; 
data[5914] = -1; 
data[5997] = -1; 
data[6080] = -1; 
data[6158] = -1.0; 
data[6241] = -1.0; 
data[6324] = -1.0; 
data[6478] = -1; 
data[6560] = -1; 

}



/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 8), // void()(double *, double *, double *, double *, double *, double)
/*  1 */ _CFFI_OP(_CFFI_OP_POINTER, 6), // double *
/*  2 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/*  3 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/*  4 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/*  5 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/*  6 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14), // double
/*  7 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  8 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 0), // void
};

static void _cffi_d_de_jac_run_num_eval(double * x0, double * x1, double * x2, double * x3, double * x4, double x5)
{
  de_jac_run_num_eval(x0, x1, x2, x3, x4, x5);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_de_jac_run_num_eval(PyObject *self, PyObject *args)
{
  double * x0;
  double * x1;
  double * x2;
  double * x3;
  double * x4;
  double x5;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;

  if (!PyArg_UnpackTuple(args, "de_jac_run_num_eval", 6, 6, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg3, (char **)&x3);
  if (datasize != 0) {
    x3 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg3, (char **)&x3,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg4, (char **)&x4);
  if (datasize != 0) {
    x4 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg4, (char **)&x4,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x5 = (double)_cffi_to_c_double(arg5);
  if (x5 == (double)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { de_jac_run_num_eval(x0, x1, x2, x3, x4, x5); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_de_jac_run_num_eval _cffi_d_de_jac_run_num_eval
#endif

static void _cffi_d_de_jac_run_up_eval(double * x0, double * x1, double * x2, double * x3, double * x4, double x5)
{
  de_jac_run_up_eval(x0, x1, x2, x3, x4, x5);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_de_jac_run_up_eval(PyObject *self, PyObject *args)
{
  double * x0;
  double * x1;
  double * x2;
  double * x3;
  double * x4;
  double x5;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;

  if (!PyArg_UnpackTuple(args, "de_jac_run_up_eval", 6, 6, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg3, (char **)&x3);
  if (datasize != 0) {
    x3 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg3, (char **)&x3,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg4, (char **)&x4);
  if (datasize != 0) {
    x4 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg4, (char **)&x4,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x5 = (double)_cffi_to_c_double(arg5);
  if (x5 == (double)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { de_jac_run_up_eval(x0, x1, x2, x3, x4, x5); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_de_jac_run_up_eval _cffi_d_de_jac_run_up_eval
#endif

static void _cffi_d_de_jac_run_xy_eval(double * x0, double * x1, double * x2, double * x3, double * x4, double x5)
{
  de_jac_run_xy_eval(x0, x1, x2, x3, x4, x5);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_de_jac_run_xy_eval(PyObject *self, PyObject *args)
{
  double * x0;
  double * x1;
  double * x2;
  double * x3;
  double * x4;
  double x5;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;

  if (!PyArg_UnpackTuple(args, "de_jac_run_xy_eval", 6, 6, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg3, (char **)&x3);
  if (datasize != 0) {
    x3 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg3, (char **)&x3,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg4, (char **)&x4);
  if (datasize != 0) {
    x4 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg4, (char **)&x4,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x5 = (double)_cffi_to_c_double(arg5);
  if (x5 == (double)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { de_jac_run_xy_eval(x0, x1, x2, x3, x4, x5); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_de_jac_run_xy_eval _cffi_d_de_jac_run_xy_eval
#endif

static void _cffi_d_f_run_eval(double * x0, double * x1, double * x2, double * x3, double * x4, double x5)
{
  f_run_eval(x0, x1, x2, x3, x4, x5);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_f_run_eval(PyObject *self, PyObject *args)
{
  double * x0;
  double * x1;
  double * x2;
  double * x3;
  double * x4;
  double x5;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;

  if (!PyArg_UnpackTuple(args, "f_run_eval", 6, 6, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg3, (char **)&x3);
  if (datasize != 0) {
    x3 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg3, (char **)&x3,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg4, (char **)&x4);
  if (datasize != 0) {
    x4 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg4, (char **)&x4,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x5 = (double)_cffi_to_c_double(arg5);
  if (x5 == (double)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { f_run_eval(x0, x1, x2, x3, x4, x5); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_f_run_eval _cffi_d_f_run_eval
#endif

static void _cffi_d_g_run_eval(double * x0, double * x1, double * x2, double * x3, double * x4, double x5)
{
  g_run_eval(x0, x1, x2, x3, x4, x5);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_g_run_eval(PyObject *self, PyObject *args)
{
  double * x0;
  double * x1;
  double * x2;
  double * x3;
  double * x4;
  double x5;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;

  if (!PyArg_UnpackTuple(args, "g_run_eval", 6, 6, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg3, (char **)&x3);
  if (datasize != 0) {
    x3 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg3, (char **)&x3,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg4, (char **)&x4);
  if (datasize != 0) {
    x4 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg4, (char **)&x4,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x5 = (double)_cffi_to_c_double(arg5);
  if (x5 == (double)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { g_run_eval(x0, x1, x2, x3, x4, x5); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_g_run_eval _cffi_d_g_run_eval
#endif

static void _cffi_d_h_eval(double * x0, double * x1, double * x2, double * x3, double * x4, double x5)
{
  h_eval(x0, x1, x2, x3, x4, x5);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_h_eval(PyObject *self, PyObject *args)
{
  double * x0;
  double * x1;
  double * x2;
  double * x3;
  double * x4;
  double x5;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;

  if (!PyArg_UnpackTuple(args, "h_eval", 6, 6, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg3, (char **)&x3);
  if (datasize != 0) {
    x3 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg3, (char **)&x3,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg4, (char **)&x4);
  if (datasize != 0) {
    x4 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg4, (char **)&x4,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x5 = (double)_cffi_to_c_double(arg5);
  if (x5 == (double)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { h_eval(x0, x1, x2, x3, x4, x5); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_h_eval _cffi_d_h_eval
#endif

static const struct _cffi_global_s _cffi_globals[] = {
  { "de_jac_run_num_eval", (void *)_cffi_f_de_jac_run_num_eval, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 0), (void *)_cffi_d_de_jac_run_num_eval },
  { "de_jac_run_up_eval", (void *)_cffi_f_de_jac_run_up_eval, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 0), (void *)_cffi_d_de_jac_run_up_eval },
  { "de_jac_run_xy_eval", (void *)_cffi_f_de_jac_run_xy_eval, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 0), (void *)_cffi_d_de_jac_run_xy_eval },
  { "f_run_eval", (void *)_cffi_f_f_run_eval, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 0), (void *)_cffi_d_f_run_eval },
  { "g_run_eval", (void *)_cffi_f_g_run_eval, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 0), (void *)_cffi_d_g_run_eval },
  { "h_eval", (void *)_cffi_f_h_eval, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 0), (void *)_cffi_d_h_eval },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  NULL,  /* no fields */
  NULL,  /* no struct_unions */
  NULL,  /* no enums */
  NULL,  /* no typenames */
  6,  /* num_globals */
  0,  /* num_struct_unions */
  0,  /* num_enums */
  0,  /* num_typenames */
  NULL,  /* no includes */
  9,  /* num_types */
  0,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit_cigre_eu_mv_run_cffi(const void *p[])
{
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
#if PY_MAJOR_VERSION >= 3
    return NULL;
#endif
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit_cigre_eu_mv_run_cffi(void) { return NULL; }
#  else
     initcigre_eu_mv_run_cffi(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit_cigre_eu_mv_run_cffi(void)
{
  return _cffi_init("cigre_eu_mv_run_cffi", 0x2601, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
initcigre_eu_mv_run_cffi(void)
{
  _cffi_init("cigre_eu_mv_run_cffi", 0x2601, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
