#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   The implementation is messy (issue #350): on Windows, with _MSC_VER,
   we have to define Py_LIMITED_API even before including pyconfig.h.
   In that case, we guess what pyconfig.h will do to the macros above,
   and check our guess after the #include.

   Note that on Windows, with CPython 3.x, you need >= 3.5 and virtualenv
   version >= 16.0.0.  With older versions of either, you don't get a
   copy of PYTHON3.DLL in the virtualenv.  We can't check the version of
   CPython *before* we even include pyconfig.h.  ffi.set_source() puts
   a ``#define _CFFI_NO_LIMITED_API'' at the start of this file if it is
   running on Windows < 3.5, as an attempt at fixing it, but that's
   arguably wrong because it may not be the target version of Python.
   Still better than nothing I guess.  As another workaround, you can
   remove the definition of Py_LIMITED_API here.

   See also 'py_limited_api' in cffi/setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  ifdef _MSC_VER
#    if !defined(_DEBUG) && !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#    include <pyconfig.h>
     /* sanity-check: Py_LIMITED_API will cause crashes if any of these
        are also defined.  Normally, the Python file PC/pyconfig.h does not
        cause any of these to be defined, with the exception that _DEBUG
        causes Py_DEBUG.  Double-check that. */
#    ifdef Py_LIMITED_API
#      if defined(Py_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_DEBUG, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_TRACE_REFS)
#        error "pyconfig.h unexpectedly defines Py_TRACE_REFS, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_REF_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_REF_DEBUG, but Py_LIMITED_API is set"
#      endif
#    endif
#  else
#    include <pyconfig.h>
#    if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>

/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#if PY_MAJOR_VERSION >= 3
# define PyInt_FromLong PyLong_FromLong
#endif

#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyInt_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyInt_FromLong((long)x) :                                    \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyInt_FromLong((long)x) :                                    \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(unsigned int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

union _cffi_union_alignment_u {
    unsigned char m_char;
    unsigned short m_short;
    unsigned int m_int;
    unsigned long m_long;
    unsigned long long m_longlong;
    float m_float;
    double m_double;
    long double m_longdouble;
};

struct _cffi_freeme_s {
    struct _cffi_freeme_s *next;
    union _cffi_union_alignment_u alignment;
};

_CFFI_UNUSED_FN static int
_cffi_convert_array_argument(struct _cffi_ctypedescr *ctptr, PyObject *arg,
                             char **output_data, Py_ssize_t datasize,
                             struct _cffi_freeme_s **freeme)
{
    char *p;
    if (datasize < 0)
        return -1;

    p = *output_data;
    if (p == NULL) {
        struct _cffi_freeme_s *fp = (struct _cffi_freeme_s *)PyObject_Malloc(
            offsetof(struct _cffi_freeme_s, alignment) + (size_t)datasize);
        if (fp == NULL)
            return -1;
        fp->next = *freeme;
        *freeme = fp;
        p = *output_data = (char *)&fp->alignment;
    }
    memset((void *)p, 0, (size_t)datasize);
    return _cffi_convert_array_from_object(p, ctptr, arg);
}

_CFFI_UNUSED_FN static void
_cffi_free_array_arguments(struct _cffi_freeme_s *freeme)
{
    do {
        void *p = (void *)freeme;
        freeme = freeme->next;
        PyObject_Free(p);
    } while (freeme != NULL);
}

/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/

void de_jac_trap_up_eval(double *data,double *x,double *y,double *u,double *p,double Dt){

data[0] = 0.5*Dt*p[4] + 1; 
data[103] = 0.5*Dt; 
data[10282] = -p[1]; 
data[10285] = 1.0*p[0]; 
data[10388] = -p[1]; 
data[10391] = 1.0*p[0]; 
data[10494] = -p[1]; 
data[10497] = 1.0*p[0]; 
data[10597] = -1.0*p[0]; 
data[10600] = -1.0*p[1]; 
data[10703] = -1.0*p[0]; 
data[10706] = -1.0*p[1]; 
data[10809] = -1.0*p[0]; 
data[10812] = -1.0*p[1]; 
data[10920] = p[3]; 
data[11023] = -p[2]; 

}

void de_jac_trap_xy_eval(double *data,double *x,double *y,double *u,double *p,double Dt){

data[9622] = y[90]; 
data[9623] = y[91]; 
data[9646] = y[66]; 
data[9647] = y[67]; 
data[9729] = y[92]; 
data[9730] = y[93]; 
data[9753] = y[68]; 
data[9754] = y[69]; 
data[9832] = -y[91]; 
data[9833] = y[90]; 
data[9856] = y[67]; 
data[9857] = -y[66]; 
data[9939] = -y[93]; 
data[9940] = y[92]; 
data[9963] = y[69]; 
data[9964] = -y[68]; 

}

void de_jac_trap_num_eval(double *data,double *x,double *y,double *u,double *p,double Dt){

data[106] = 0.00064819316156214564; 
data[107] = 0.0025927726462485826; 
data[108] = -0.00032409658078107282; 
data[109] = -0.0012963863231242913; 
data[110] = -0.00032409658078107282; 
data[111] = -0.0012963863231242913; 
data[112] = -0.0030874345945969294; 
data[113] = -0.012349738378387718; 
data[114] = 0.0030874345945969294; 
data[115] = 0.012349738378387718; 
data[211] = -0.0025927726462485826; 
data[212] = 0.00064819316156214564; 
data[213] = 0.0012963863231242913; 
data[214] = -0.00032409658078107282; 
data[215] = 0.0012963863231242913; 
data[216] = -0.00032409658078107282; 
data[217] = 0.012349738378387718; 
data[218] = -0.0030874345945969294; 
data[219] = -0.012349738378387718; 
data[220] = 0.0030874345945969294; 
data[316] = -0.00032409658078107282; 
data[317] = -0.0012963863231242913; 
data[318] = 0.00064819316156214564; 
data[319] = 0.0025927726462485826; 
data[320] = -0.00032409658078107282; 
data[321] = -0.0012963863231242913; 
data[324] = -0.0030874345945969294; 
data[325] = -0.012349738378387718; 
data[326] = 0.0030874345945969294; 
data[327] = 0.012349738378387718; 
data[421] = 0.0012963863231242913; 
data[422] = -0.00032409658078107282; 
data[423] = -0.0025927726462485826; 
data[424] = 0.00064819316156214564; 
data[425] = 0.0012963863231242913; 
data[426] = -0.00032409658078107282; 
data[429] = 0.012349738378387718; 
data[430] = -0.0030874345945969294; 
data[431] = -0.012349738378387718; 
data[432] = 0.0030874345945969294; 
data[526] = -0.00032409658078107282; 
data[527] = -0.0012963863231242913; 
data[528] = -0.00032409658078107282; 
data[529] = -0.0012963863231242913; 
data[530] = 0.00064819316156214564; 
data[531] = 0.0025927726462485826; 
data[532] = 0.0030874345945969294; 
data[533] = 0.012349738378387718; 
data[536] = -0.0030874345945969294; 
data[537] = -0.012349738378387718; 
data[631] = 0.0012963863231242913; 
data[632] = -0.00032409658078107282; 
data[633] = 0.0012963863231242913; 
data[634] = -0.00032409658078107282; 
data[635] = -0.0025927726462485826; 
data[636] = 0.00064819316156214564; 
data[637] = -0.012349738378387718; 
data[638] = 0.0030874345945969294; 
data[641] = 0.012349738378387718; 
data[642] = -0.0030874345945969294; 
data[736] = -0.0030874345945969294; 
data[737] = -0.012349738378387718; 
data[740] = 0.0030874345945969294; 
data[741] = 0.012349738378387718; 
data[742] = 0.26205492055737734; 
data[743] = 0.45012709792466798; 
data[748] = -0.232643155851495; 
data[749] = -0.33248003910113855; 
data[832] = -1; 
data[841] = 0.012349738378387718; 
data[842] = -0.0030874345945969294; 
data[845] = -0.012349738378387718; 
data[846] = 0.0030874345945969294; 
data[847] = -0.45012709792466798; 
data[848] = 0.26205492055737734; 
data[853] = 0.33248003910113855; 
data[854] = -0.232643155851495; 
data[940] = -1; 
data[946] = 0.0030874345945969294; 
data[947] = 0.012349738378387718; 
data[948] = -0.0030874345945969294; 
data[949] = -0.012349738378387718; 
data[954] = 0.26205492055737734; 
data[955] = 0.45012709792466798; 
data[960] = -0.232643155851495; 
data[961] = -0.33248003910113855; 
data[1043] = -1; 
data[1051] = -0.012349738378387718; 
data[1052] = 0.0030874345945969294; 
data[1053] = 0.012349738378387718; 
data[1054] = -0.0030874345945969294; 
data[1059] = -0.45012709792466798; 
data[1060] = 0.26205492055737734; 
data[1065] = 0.33248003910113855; 
data[1066] = -0.232643155851495; 
data[1151] = -1; 
data[1158] = 0.0030874345945969294; 
data[1159] = 0.012349738378387718; 
data[1160] = -0.0030874345945969294; 
data[1161] = -0.012349738378387718; 
data[1166] = 0.26205492055737734; 
data[1167] = 0.45012709792466798; 
data[1172] = -0.232643155851495; 
data[1173] = -0.33248003910113855; 
data[1254] = -1; 
data[1263] = -0.012349738378387718; 
data[1264] = 0.0030874345945969294; 
data[1265] = 0.012349738378387718; 
data[1266] = -0.0030874345945969294; 
data[1271] = -0.45012709792466798; 
data[1272] = 0.26205492055737734; 
data[1277] = 0.33248003910113855; 
data[1278] = -0.232643155851495; 
data[1362] = -1; 
data[1372] = -0.232643155851495; 
data[1373] = -0.33248003910113855; 
data[1378] = 0.38107159465267509; 
data[1379] = 0.54460531291679715; 
data[1384] = -0.14842843880118009; 
data[1385] = -0.21212527381565857; 
data[1477] = 0.33248003910113855; 
data[1478] = -0.232643155851495; 
data[1483] = -0.54460531291679715; 
data[1484] = 0.38107159465267509; 
data[1489] = 0.21212527381565857; 
data[1490] = -0.14842843880118009; 
data[1584] = -0.232643155851495; 
data[1585] = -0.33248003910113855; 
data[1590] = 0.38107159465267509; 
data[1591] = 0.54460531291679715; 
data[1596] = -0.14842843880118009; 
data[1597] = -0.21212527381565857; 
data[1689] = 0.33248003910113855; 
data[1690] = -0.232643155851495; 
data[1695] = -0.54460531291679715; 
data[1696] = 0.38107159465267509; 
data[1701] = 0.21212527381565857; 
data[1702] = -0.14842843880118009; 
data[1796] = -0.232643155851495; 
data[1797] = -0.33248003910113855; 
data[1802] = 0.38107159465267509; 
data[1803] = 0.54460531291679715; 
data[1808] = -0.14842843880118009; 
data[1809] = -0.21212527381565857; 
data[1901] = 0.33248003910113855; 
data[1902] = -0.232643155851495; 
data[1907] = -0.54460531291679715; 
data[1908] = 0.38107159465267509; 
data[1913] = 0.21212527381565857; 
data[1914] = -0.14842843880118009; 
data[2008] = -0.14842843880118009; 
data[2009] = -0.21212527381565857; 
data[2014] = 1.7285829987599723; 
data[2015] = 2.470390074076128; 
data[2020] = -1.0754978680347802; 
data[2021] = -1.5370388692872305; 
data[2044] = -0.50465669192401219; 
data[2045] = -0.72122593097323895; 
data[2113] = 0.21212527381565857; 
data[2114] = -0.14842843880118009; 
data[2119] = -2.470390074076128; 
data[2120] = 1.7285829987599723; 
data[2125] = 1.5370388692872305; 
data[2126] = -1.0754978680347802; 
data[2149] = 0.72122593097323895; 
data[2150] = -0.50465669192401219; 
data[2220] = -0.14842843880118009; 
data[2221] = -0.21212527381565857; 
data[2226] = 1.7285829987599723; 
data[2227] = 2.470390074076128; 
data[2232] = -1.0754978680347802; 
data[2233] = -1.5370388692872305; 
data[2256] = -0.50465669192401219; 
data[2257] = -0.72122593097323895; 
data[2325] = 0.21212527381565857; 
data[2326] = -0.14842843880118009; 
data[2331] = -2.470390074076128; 
data[2332] = 1.7285829987599723; 
data[2337] = 1.5370388692872305; 
data[2338] = -1.0754978680347802; 
data[2361] = 0.72122593097323895; 
data[2362] = -0.50465669192401219; 
data[2432] = -0.14842843880118009; 
data[2433] = -0.21212527381565857; 
data[2438] = 1.7285829987599726; 
data[2439] = 2.470390074076128; 
data[2444] = -1.0754978680347802; 
data[2445] = -1.5370388692872305; 
data[2468] = -0.50465669192401219; 
data[2469] = -0.72122593097323895; 
data[2537] = 0.21212527381565857; 
data[2538] = -0.14842843880118009; 
data[2543] = -2.470390074076128; 
data[2544] = 1.7285829987599726; 
data[2549] = 1.5370388692872305; 
data[2550] = -1.0754978680347802; 
data[2573] = 0.72122593097323895; 
data[2574] = -0.50465669192401219; 
data[2644] = -1.0754978680347802; 
data[2645] = -1.5370388692872305; 
data[2650] = 2.2470223314298083; 
data[2651] = 3.2113133519036783; 
data[2656] = -1.1715244633950284; 
data[2657] = -1.6742744826164477; 
data[2749] = 1.5370388692872305; 
data[2750] = -1.0754978680347802; 
data[2755] = -3.2113133519036783; 
data[2756] = 2.2470223314298083; 
data[2761] = 1.6742744826164477; 
data[2762] = -1.1715244633950284; 
data[2856] = -1.0754978680347802; 
data[2857] = -1.5370388692872305; 
data[2862] = 2.2470223314298083; 
data[2863] = 3.2113133519036783; 
data[2868] = -1.1715244633950284; 
data[2869] = -1.6742744826164477; 
data[2961] = 1.5370388692872305; 
data[2962] = -1.0754978680347802; 
data[2967] = -3.2113133519036783; 
data[2968] = 2.2470223314298083; 
data[2973] = 1.6742744826164477; 
data[2974] = -1.1715244633950284; 
data[3068] = -1.0754978680347802; 
data[3069] = -1.5370388692872305; 
data[3074] = 2.2470223314298083; 
data[3075] = 3.2113133519036783; 
data[3080] = -1.1715244633950284; 
data[3081] = -1.6742744826164477; 
data[3173] = 1.5370388692872305; 
data[3174] = -1.0754978680347802; 
data[3179] = -3.2113133519036783; 
data[3180] = 2.2470223314298083; 
data[3185] = 1.6742744826164477; 
data[3186] = -1.1715244633950284; 
data[3280] = -1.1715244633950284; 
data[3281] = -1.6742744826164477; 
data[3286] = 1.5975333591750389; 
data[3287] = 2.283101567204247; 
data[3292] = -0.42600889578001044; 
data[3293] = -0.60882708458779922; 
data[3385] = 1.6742744826164477; 
data[3386] = -1.1715244633950284; 
data[3391] = -2.283101567204247; 
data[3392] = 1.5975333591750389; 
data[3397] = 0.60882708458779922; 
data[3398] = -0.42600889578001044; 
data[3492] = -1.1715244633950284; 
data[3493] = -1.6742744826164477; 
data[3498] = 1.5975333591750389; 
data[3499] = 2.283101567204247; 
data[3504] = -0.42600889578001044; 
data[3505] = -0.60882708458779922; 
data[3597] = 1.6742744826164477; 
data[3598] = -1.1715244633950284; 
data[3603] = -2.283101567204247; 
data[3604] = 1.5975333591750389; 
data[3609] = 0.60882708458779922; 
data[3610] = -0.42600889578001044; 
data[3704] = -1.1715244633950284; 
data[3705] = -1.6742744826164477; 
data[3710] = 1.5975333591750389; 
data[3711] = 2.283101567204247; 
data[3716] = -0.42600889578001044; 
data[3717] = -0.60882708458779922; 
data[3809] = 1.6742744826164477; 
data[3810] = -1.1715244633950284; 
data[3815] = -2.283101567204247; 
data[3816] = 1.5975333591750389; 
data[3821] = 0.60882708458779922; 
data[3822] = -0.42600889578001044; 
data[3916] = -0.42600889578001044; 
data[3917] = -0.60882708458779922; 
data[3922] = 3.1595659770350766; 
data[3923] = 4.5154675440261771; 
data[3928] = -2.733557081255066; 
data[3929] = -3.9066404594383779; 
data[4021] = 0.60882708458779922; 
data[4022] = -0.42600889578001044; 
data[4027] = -4.5154675440261771; 
data[4028] = 3.1595659770350766; 
data[4033] = 3.9066404594383779; 
data[4034] = -2.733557081255066; 
data[4128] = -0.42600889578001044; 
data[4129] = -0.60882708458779922; 
data[4134] = 3.1595659770350766; 
data[4135] = 4.5154675440261771; 
data[4140] = -2.733557081255066; 
data[4141] = -3.9066404594383779; 
data[4233] = 0.60882708458779922; 
data[4234] = -0.42600889578001044; 
data[4239] = -4.5154675440261771; 
data[4240] = 3.1595659770350766; 
data[4245] = 3.9066404594383779; 
data[4246] = -2.733557081255066; 
data[4340] = -0.42600889578001044; 
data[4341] = -0.60882708458779922; 
data[4346] = 3.1595659770350766; 
data[4347] = 4.5154675440261771; 
data[4352] = -2.733557081255066; 
data[4353] = -3.9066404594383779; 
data[4445] = 0.60882708458779922; 
data[4446] = -0.42600889578001044; 
data[4451] = -4.5154675440261771; 
data[4452] = 3.1595659770350766; 
data[4457] = 3.9066404594383779; 
data[4458] = -2.733557081255066; 
data[4552] = -2.733557081255066; 
data[4553] = -3.9066404594383779; 
data[4558] = 3.1264036079025006; 
data[4559] = 4.468073818878624; 
data[4564] = -0.39284652664743452; 
data[4565] = -0.56143335944024586; 
data[4657] = 3.9066404594383779; 
data[4658] = -2.733557081255066; 
data[4663] = -4.468073818878624; 
data[4664] = 3.1264036079025006; 
data[4669] = 0.56143335944024586; 
data[4670] = -0.39284652664743452; 
data[4764] = -2.733557081255066; 
data[4765] = -3.9066404594383779; 
data[4770] = 3.1264036079025006; 
data[4771] = 4.468073818878624; 
data[4776] = -0.39284652664743452; 
data[4777] = -0.56143335944024586; 
data[4869] = 3.9066404594383779; 
data[4870] = -2.733557081255066; 
data[4875] = -4.468073818878624; 
data[4876] = 3.1264036079025006; 
data[4881] = 0.56143335944024586; 
data[4882] = -0.39284652664743452; 
data[4976] = -2.733557081255066; 
data[4977] = -3.9066404594383779; 
data[4982] = 3.1264036079025006; 
data[4983] = 4.468073818878624; 
data[4988] = -0.39284652664743452; 
data[4989] = -0.56143335944024586; 
data[5081] = 3.9066404594383779; 
data[5082] = -2.733557081255066; 
data[5087] = -4.468073818878624; 
data[5088] = 3.1264036079025006; 
data[5093] = 0.56143335944024586; 
data[5094] = -0.39284652664743452; 
data[5164] = -0.50465669192401219; 
data[5165] = -0.72122593097323895; 
data[5188] = -0.39284652664743452; 
data[5189] = -0.56143335944024586; 
data[5194] = 2.9476710295127462; 
data[5195] = 4.2126396349922688; 
data[5200] = -2.0501678109412995; 
data[5201] = -2.9299803445787838; 
data[5269] = 0.72122593097323895; 
data[5270] = -0.50465669192401219; 
data[5293] = 0.56143335944024586; 
data[5294] = -0.39284652664743452; 
data[5299] = -4.2126396349922688; 
data[5300] = 2.9476710295127462; 
data[5305] = 2.9299803445787838; 
data[5306] = -2.0501678109412995; 
data[5376] = -0.50465669192401219; 
data[5377] = -0.72122593097323895; 
data[5400] = -0.39284652664743452; 
data[5401] = -0.56143335944024586; 
data[5406] = 2.9476710295127462; 
data[5407] = 4.2126396349922688; 
data[5412] = -2.0501678109412995; 
data[5413] = -2.9299803445787838; 
data[5481] = 0.72122593097323895; 
data[5482] = -0.50465669192401219; 
data[5505] = 0.56143335944024586; 
data[5506] = -0.39284652664743452; 
data[5511] = -4.2126396349922688; 
data[5512] = 2.9476710295127462; 
data[5517] = 2.9299803445787838; 
data[5518] = -2.0501678109412995; 
data[5588] = -0.50465669192401219; 
data[5589] = -0.72122593097323895; 
data[5612] = -0.39284652664743452; 
data[5613] = -0.56143335944024586; 
data[5618] = 2.9476710295127462; 
data[5619] = 4.2126396349922688; 
data[5624] = -2.0501678109412995; 
data[5625] = -2.9299803445787838; 
data[5693] = 0.72122593097323895; 
data[5694] = -0.50465669192401219; 
data[5717] = 0.56143335944024586; 
data[5718] = -0.39284652664743452; 
data[5723] = -4.2126396349922688; 
data[5724] = 2.9476710295127462; 
data[5729] = 2.9299803445787838; 
data[5730] = -2.0501678109412995; 
data[5824] = -2.0501678109412995; 
data[5825] = -2.9299803445787838; 
data[5830] = 2.9021856025013202; 
data[5831] = 4.1476345137543822; 
data[5836] = -0.85201779156002089; 
data[5837] = -1.2176541691755984; 
data[5929] = 2.9299803445787838; 
data[5930] = -2.0501678109412995; 
data[5935] = -4.1476345137543822; 
data[5936] = 2.9021856025013202; 
data[5941] = 1.2176541691755984; 
data[5942] = -0.85201779156002089; 
data[6036] = -2.0501678109412995; 
data[6037] = -2.9299803445787838; 
data[6042] = 2.9021856025013202; 
data[6043] = 4.1476345137543822; 
data[6048] = -0.85201779156002089; 
data[6049] = -1.2176541691755984; 
data[6141] = 2.9299803445787838; 
data[6142] = -2.0501678109412995; 
data[6147] = -4.1476345137543822; 
data[6148] = 2.9021856025013202; 
data[6153] = 1.2176541691755984; 
data[6154] = -0.85201779156002089; 
data[6248] = -2.0501678109412995; 
data[6249] = -2.9299803445787838; 
data[6254] = 2.9021856025013202; 
data[6255] = 4.1476345137543822; 
data[6260] = -0.85201779156002089; 
data[6261] = -1.2176541691755984; 
data[6353] = 2.9299803445787838; 
data[6354] = -2.0501678109412995; 
data[6359] = -4.1476345137543822; 
data[6360] = 2.9021856025013202; 
data[6365] = 1.2176541691755984; 
data[6366] = -0.85201779156002089; 
data[6460] = -0.85201779156002089; 
data[6461] = -1.2176541691755984; 
data[6466] = 2.8400593052000689; 
data[6467] = 4.0588472305853278; 
data[6472] = -1.9880415136400482; 
data[6473] = -2.8411930614097294; 
data[6565] = 1.2176541691755984; 
data[6566] = -0.85201779156002089; 
data[6571] = -4.0588472305853278; 
data[6572] = 2.8400593052000689; 
data[6577] = 2.8411930614097294; 
data[6578] = -1.9880415136400482; 
data[6672] = -0.85201779156002089; 
data[6673] = -1.2176541691755984; 
data[6678] = 2.8400593052000689; 
data[6679] = 4.0588472305853278; 
data[6684] = -1.9880415136400482; 
data[6685] = -2.8411930614097294; 
data[6777] = 1.2176541691755984; 
data[6778] = -0.85201779156002089; 
data[6783] = -4.0588472305853278; 
data[6784] = 2.8400593052000689; 
data[6789] = 2.8411930614097294; 
data[6790] = -1.9880415136400482; 
data[6884] = -0.85201779156002089; 
data[6885] = -1.2176541691755984; 
data[6890] = 2.8400593052000689; 
data[6891] = 4.0588472305853278; 
data[6896] = -1.9880415136400482; 
data[6897] = -2.8411930614097294; 
data[6989] = 1.2176541691755984; 
data[6990] = -0.85201779156002089; 
data[6995] = -4.0588472305853278; 
data[6996] = 2.8400593052000689; 
data[7001] = 2.8411930614097294; 
data[7002] = -1.9880415136400482; 
data[7096] = -1.9880415136400482; 
data[7097] = -2.8411930614097294; 
data[7102] = 1.9880415136400482; 
data[7103] = 2.8411930614097294; 
data[7126] = -1; 
data[7201] = 2.8411930614097294; 
data[7202] = -1.9880415136400482; 
data[7207] = -2.8411930614097294; 
data[7208] = 1.9880415136400482; 
data[7232] = -1; 
data[7308] = -1.9880415136400482; 
data[7309] = -2.8411930614097294; 
data[7314] = 1.9880415136400482; 
data[7315] = 2.8411930614097294; 
data[7338] = -1; 
data[7413] = 2.8411930614097294; 
data[7414] = -1.9880415136400482; 
data[7419] = -2.8411930614097294; 
data[7420] = 1.9880415136400482; 
data[7444] = -1; 
data[7520] = -1.9880415136400482; 
data[7521] = -2.8411930614097294; 
data[7526] = 1.9880415136400482; 
data[7527] = 2.8411930614097294; 
data[7550] = -1; 
data[7625] = 2.8411930614097294; 
data[7626] = -1.9880415136400482; 
data[7631] = -2.8411930614097294; 
data[7632] = 1.9880415136400482; 
data[7656] = -1; 
data[7738] = 1.9880415136400482; 
data[7739] = 2.8411930614097294; 
data[7744] = -1.9880415136400482; 
data[7745] = -2.8411930614097294; 
data[7843] = -2.8411930614097294; 
data[7844] = 1.9880415136400482; 
data[7849] = 2.8411930614097294; 
data[7850] = -1.9880415136400482; 
data[7950] = 1.9880415136400482; 
data[7951] = 2.8411930614097294; 
data[7956] = -1.9880415136400482; 
data[7957] = -2.8411930614097294; 
data[8055] = -2.8411930614097294; 
data[8056] = 1.9880415136400482; 
data[8061] = 2.8411930614097294; 
data[8062] = -1.9880415136400482; 
data[8162] = 1.9880415136400482; 
data[8163] = 2.8411930614097294; 
data[8168] = -1.9880415136400482; 
data[8169] = -2.8411930614097294; 
data[8267] = -2.8411930614097294; 
data[8268] = 1.9880415136400482; 
data[8273] = 2.8411930614097294; 
data[8274] = -1.9880415136400482; 
data[8368] = -1.9880415136400482; 
data[8369] = -2.8411930614097294; 
data[8374] = 3.9760830272800964; 
data[8375] = 5.6823861228194588; 
data[8380] = -1.9880415136400482; 
data[8381] = -2.8411930614097294; 
data[8473] = 2.8411930614097294; 
data[8474] = -1.9880415136400482; 
data[8479] = -5.6823861228194588; 
data[8480] = 3.9760830272800964; 
data[8485] = 2.8411930614097294; 
data[8486] = -1.9880415136400482; 
data[8580] = -1.9880415136400482; 
data[8581] = -2.8411930614097294; 
data[8586] = 3.9760830272800964; 
data[8587] = 5.6823861228194588; 
data[8592] = -1.9880415136400482; 
data[8593] = -2.8411930614097294; 
data[8685] = 2.8411930614097294; 
data[8686] = -1.9880415136400482; 
data[8691] = -5.6823861228194588; 
data[8692] = 3.9760830272800964; 
data[8697] = 2.8411930614097294; 
data[8698] = -1.9880415136400482; 
data[8792] = -1.9880415136400482; 
data[8793] = -2.8411930614097294; 
data[8798] = 3.9760830272800964; 
data[8799] = 5.6823861228194588; 
data[8804] = -1.9880415136400482; 
data[8805] = -2.8411930614097294; 
data[8897] = 2.8411930614097294; 
data[8898] = -1.9880415136400482; 
data[8903] = -5.6823861228194588; 
data[8904] = 3.9760830272800964; 
data[8909] = 2.8411930614097294; 
data[8910] = -1.9880415136400482; 
data[9004] = -1.9880415136400482; 
data[9005] = -2.8411930614097294; 
data[9010] = 1.9880415136400482; 
data[9011] = 2.8411930614097294; 
data[9109] = 2.8411930614097294; 
data[9110] = -1.9880415136400482; 
data[9115] = -2.8411930614097294; 
data[9116] = 1.9880415136400482; 
data[9216] = -1.9880415136400482; 
data[9217] = -2.8411930614097294; 
data[9222] = 1.9880415136400482; 
data[9223] = 2.8411930614097294; 
data[9321] = 2.8411930614097294; 
data[9322] = -1.9880415136400482; 
data[9327] = -2.8411930614097294; 
data[9328] = 1.9880415136400482; 
data[9428] = -1.9880415136400482; 
data[9429] = -2.8411930614097294; 
data[9434] = 1.9880415136400482; 
data[9435] = 2.8411930614097294; 
data[9533] = 2.8411930614097294; 
data[9534] = -1.9880415136400482; 
data[9539] = -2.8411930614097294; 
data[9540] = 1.9880415136400482; 
data[10066] = 1; 
data[10068] = 1; 
data[10070] = 1; 
data[10172] = 1; 
data[10174] = 1; 
data[10176] = 1; 
data[10192] = -1; 
data[10299] = -1; 
data[10406] = -1; 
data[10508] = -1.0; 
data[10615] = -1.0; 
data[10722] = -1.0; 
data[10918] = -1; 
data[11024] = -1; 

}



/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 8), // void()(double *, double *, double *, double *, double *, double)
/*  1 */ _CFFI_OP(_CFFI_OP_POINTER, 6), // double *
/*  2 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/*  3 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/*  4 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/*  5 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/*  6 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14), // double
/*  7 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  8 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 0), // void
};

static void _cffi_d_de_jac_trap_num_eval(double * x0, double * x1, double * x2, double * x3, double * x4, double x5)
{
  de_jac_trap_num_eval(x0, x1, x2, x3, x4, x5);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_de_jac_trap_num_eval(PyObject *self, PyObject *args)
{
  double * x0;
  double * x1;
  double * x2;
  double * x3;
  double * x4;
  double x5;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;

  if (!PyArg_UnpackTuple(args, "de_jac_trap_num_eval", 6, 6, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg3, (char **)&x3);
  if (datasize != 0) {
    x3 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg3, (char **)&x3,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg4, (char **)&x4);
  if (datasize != 0) {
    x4 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg4, (char **)&x4,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x5 = (double)_cffi_to_c_double(arg5);
  if (x5 == (double)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { de_jac_trap_num_eval(x0, x1, x2, x3, x4, x5); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_de_jac_trap_num_eval _cffi_d_de_jac_trap_num_eval
#endif

static void _cffi_d_de_jac_trap_up_eval(double * x0, double * x1, double * x2, double * x3, double * x4, double x5)
{
  de_jac_trap_up_eval(x0, x1, x2, x3, x4, x5);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_de_jac_trap_up_eval(PyObject *self, PyObject *args)
{
  double * x0;
  double * x1;
  double * x2;
  double * x3;
  double * x4;
  double x5;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;

  if (!PyArg_UnpackTuple(args, "de_jac_trap_up_eval", 6, 6, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg3, (char **)&x3);
  if (datasize != 0) {
    x3 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg3, (char **)&x3,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg4, (char **)&x4);
  if (datasize != 0) {
    x4 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg4, (char **)&x4,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x5 = (double)_cffi_to_c_double(arg5);
  if (x5 == (double)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { de_jac_trap_up_eval(x0, x1, x2, x3, x4, x5); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_de_jac_trap_up_eval _cffi_d_de_jac_trap_up_eval
#endif

static void _cffi_d_de_jac_trap_xy_eval(double * x0, double * x1, double * x2, double * x3, double * x4, double x5)
{
  de_jac_trap_xy_eval(x0, x1, x2, x3, x4, x5);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_de_jac_trap_xy_eval(PyObject *self, PyObject *args)
{
  double * x0;
  double * x1;
  double * x2;
  double * x3;
  double * x4;
  double x5;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;

  if (!PyArg_UnpackTuple(args, "de_jac_trap_xy_eval", 6, 6, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg3, (char **)&x3);
  if (datasize != 0) {
    x3 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg3, (char **)&x3,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg4, (char **)&x4);
  if (datasize != 0) {
    x4 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg4, (char **)&x4,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x5 = (double)_cffi_to_c_double(arg5);
  if (x5 == (double)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { de_jac_trap_xy_eval(x0, x1, x2, x3, x4, x5); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_de_jac_trap_xy_eval _cffi_d_de_jac_trap_xy_eval
#endif

static const struct _cffi_global_s _cffi_globals[] = {
  { "de_jac_trap_num_eval", (void *)_cffi_f_de_jac_trap_num_eval, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 0), (void *)_cffi_d_de_jac_trap_num_eval },
  { "de_jac_trap_up_eval", (void *)_cffi_f_de_jac_trap_up_eval, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 0), (void *)_cffi_d_de_jac_trap_up_eval },
  { "de_jac_trap_xy_eval", (void *)_cffi_f_de_jac_trap_xy_eval, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 0), (void *)_cffi_d_de_jac_trap_xy_eval },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  NULL,  /* no fields */
  NULL,  /* no struct_unions */
  NULL,  /* no enums */
  NULL,  /* no typenames */
  3,  /* num_globals */
  0,  /* num_struct_unions */
  0,  /* num_enums */
  0,  /* num_typenames */
  NULL,  /* no includes */
  9,  /* num_types */
  0,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit_cigre_eu_mv_trap_cffi(const void *p[])
{
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
#if PY_MAJOR_VERSION >= 3
    return NULL;
#endif
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit_cigre_eu_mv_trap_cffi(void) { return NULL; }
#  else
     initcigre_eu_mv_trap_cffi(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit_cigre_eu_mv_trap_cffi(void)
{
  return _cffi_init("cigre_eu_mv_trap_cffi", 0x2601, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
initcigre_eu_mv_trap_cffi(void)
{
  _cffi_init("cigre_eu_mv_trap_cffi", 0x2601, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
