#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   The implementation is messy (issue #350): on Windows, with _MSC_VER,
   we have to define Py_LIMITED_API even before including pyconfig.h.
   In that case, we guess what pyconfig.h will do to the macros above,
   and check our guess after the #include.

   Note that on Windows, with CPython 3.x, you need >= 3.5 and virtualenv
   version >= 16.0.0.  With older versions of either, you don't get a
   copy of PYTHON3.DLL in the virtualenv.  We can't check the version of
   CPython *before* we even include pyconfig.h.  ffi.set_source() puts
   a ``#define _CFFI_NO_LIMITED_API'' at the start of this file if it is
   running on Windows < 3.5, as an attempt at fixing it, but that's
   arguably wrong because it may not be the target version of Python.
   Still better than nothing I guess.  As another workaround, you can
   remove the definition of Py_LIMITED_API here.

   See also 'py_limited_api' in cffi/setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  ifdef _MSC_VER
#    if !defined(_DEBUG) && !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#    include <pyconfig.h>
     /* sanity-check: Py_LIMITED_API will cause crashes if any of these
        are also defined.  Normally, the Python file PC/pyconfig.h does not
        cause any of these to be defined, with the exception that _DEBUG
        causes Py_DEBUG.  Double-check that. */
#    ifdef Py_LIMITED_API
#      if defined(Py_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_DEBUG, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_TRACE_REFS)
#        error "pyconfig.h unexpectedly defines Py_TRACE_REFS, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_REF_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_REF_DEBUG, but Py_LIMITED_API is set"
#      endif
#    endif
#  else
#    include <pyconfig.h>
#    if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>

/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#if PY_MAJOR_VERSION >= 3
# define PyInt_FromLong PyLong_FromLong
#endif

#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyInt_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyInt_FromLong((long)x) :                                    \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyInt_FromLong((long)x) :                                    \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(unsigned int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

union _cffi_union_alignment_u {
    unsigned char m_char;
    unsigned short m_short;
    unsigned int m_int;
    unsigned long m_long;
    unsigned long long m_longlong;
    float m_float;
    double m_double;
    long double m_longdouble;
};

struct _cffi_freeme_s {
    struct _cffi_freeme_s *next;
    union _cffi_union_alignment_u alignment;
};

_CFFI_UNUSED_FN static int
_cffi_convert_array_argument(struct _cffi_ctypedescr *ctptr, PyObject *arg,
                             char **output_data, Py_ssize_t datasize,
                             struct _cffi_freeme_s **freeme)
{
    char *p;
    if (datasize < 0)
        return -1;

    p = *output_data;
    if (p == NULL) {
        struct _cffi_freeme_s *fp = (struct _cffi_freeme_s *)PyObject_Malloc(
            offsetof(struct _cffi_freeme_s, alignment) + (size_t)datasize);
        if (fp == NULL)
            return -1;
        fp->next = *freeme;
        *freeme = fp;
        p = *output_data = (char *)&fp->alignment;
    }
    memset((void *)p, 0, (size_t)datasize);
    return _cffi_convert_array_from_object(p, ctptr, arg);
}

_CFFI_UNUSED_FN static void
_cffi_free_array_arguments(struct _cffi_freeme_s *freeme)
{
    do {
        void *p = (void *)freeme;
        freeme = freeme->next;
        PyObject_Free(p);
    } while (freeme != NULL);
}

/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/

void de_jac_trap_up_eval(double *data,double *x,double *y,double *u,double *p,double Dt){

data[0] = 0.5*Dt*p[4] + 1; 
data[73] = 0.5*Dt; 
data[5092] = -p[1]; 
data[5095] = 1.0*p[0]; 
data[5168] = -p[1]; 
data[5171] = 1.0*p[0]; 
data[5244] = -p[1]; 
data[5247] = 1.0*p[0]; 
data[5317] = -1.0*p[0]; 
data[5320] = -1.0*p[1]; 
data[5393] = -1.0*p[0]; 
data[5396] = -1.0*p[1]; 
data[5469] = -1.0*p[0]; 
data[5472] = -1.0*p[1]; 
data[5550] = p[3]; 
data[5623] = -p[2]; 

}

void de_jac_trap_xy_eval(double *data,double *x,double *y,double *u,double *p,double Dt){


}

void de_jac_trap_num_eval(double *data,double *x,double *y,double *u,double *p,double Dt){

data[76] = 0.232643155851495; 
data[77] = 0.33248003910113855; 
data[82] = -0.232643155851495; 
data[83] = -0.33248003910113855; 
data[142] = -1; 
data[151] = -0.33248003910113855; 
data[152] = 0.232643155851495; 
data[157] = 0.33248003910113855; 
data[158] = -0.232643155851495; 
data[220] = -1; 
data[228] = 0.232643155851495; 
data[229] = 0.33248003910113855; 
data[234] = -0.232643155851495; 
data[235] = -0.33248003910113855; 
data[293] = -1; 
data[303] = -0.33248003910113855; 
data[304] = 0.232643155851495; 
data[309] = 0.33248003910113855; 
data[310] = -0.232643155851495; 
data[371] = -1; 
data[380] = 0.232643155851495; 
data[381] = 0.33248003910113855; 
data[386] = -0.232643155851495; 
data[387] = -0.33248003910113855; 
data[444] = -1; 
data[455] = -0.33248003910113855; 
data[456] = 0.232643155851495; 
data[461] = 0.33248003910113855; 
data[462] = -0.232643155851495; 
data[522] = -1; 
data[526] = -0.232643155851495; 
data[527] = -0.33248003910113855; 
data[532] = 0.38107159465267509; 
data[533] = 0.54460531291679715; 
data[538] = -0.14842843880118009; 
data[539] = -0.21212527381565857; 
data[601] = 0.33248003910113855; 
data[602] = -0.232643155851495; 
data[607] = -0.54460531291679715; 
data[608] = 0.38107159465267509; 
data[613] = 0.21212527381565857; 
data[614] = -0.14842843880118009; 
data[678] = -0.232643155851495; 
data[679] = -0.33248003910113855; 
data[684] = 0.38107159465267509; 
data[685] = 0.54460531291679715; 
data[690] = -0.14842843880118009; 
data[691] = -0.21212527381565857; 
data[753] = 0.33248003910113855; 
data[754] = -0.232643155851495; 
data[759] = -0.54460531291679715; 
data[760] = 0.38107159465267509; 
data[765] = 0.21212527381565857; 
data[766] = -0.14842843880118009; 
data[830] = -0.232643155851495; 
data[831] = -0.33248003910113855; 
data[836] = 0.38107159465267509; 
data[837] = 0.54460531291679715; 
data[842] = -0.14842843880118009; 
data[843] = -0.21212527381565857; 
data[905] = 0.33248003910113855; 
data[906] = -0.232643155851495; 
data[911] = -0.54460531291679715; 
data[912] = 0.38107159465267509; 
data[917] = 0.21212527381565857; 
data[918] = -0.14842843880118009; 
data[982] = -0.14842843880118009; 
data[983] = -0.21212527381565857; 
data[988] = 1.7285829987599723; 
data[989] = 2.470390074076128; 
data[994] = -1.0754978680347802; 
data[995] = -1.5370388692872305; 
data[1018] = -0.50465669192401219; 
data[1019] = -0.72122593097323895; 
data[1057] = 0.21212527381565857; 
data[1058] = -0.14842843880118009; 
data[1063] = -2.470390074076128; 
data[1064] = 1.7285829987599723; 
data[1069] = 1.5370388692872305; 
data[1070] = -1.0754978680347802; 
data[1093] = 0.72122593097323895; 
data[1094] = -0.50465669192401219; 
data[1134] = -0.14842843880118009; 
data[1135] = -0.21212527381565857; 
data[1140] = 1.7285829987599723; 
data[1141] = 2.470390074076128; 
data[1146] = -1.0754978680347802; 
data[1147] = -1.5370388692872305; 
data[1170] = -0.50465669192401219; 
data[1171] = -0.72122593097323895; 
data[1209] = 0.21212527381565857; 
data[1210] = -0.14842843880118009; 
data[1215] = -2.470390074076128; 
data[1216] = 1.7285829987599723; 
data[1221] = 1.5370388692872305; 
data[1222] = -1.0754978680347802; 
data[1245] = 0.72122593097323895; 
data[1246] = -0.50465669192401219; 
data[1286] = -0.14842843880118009; 
data[1287] = -0.21212527381565857; 
data[1292] = 1.7285829987599726; 
data[1293] = 2.470390074076128; 
data[1298] = -1.0754978680347802; 
data[1299] = -1.5370388692872305; 
data[1322] = -0.50465669192401219; 
data[1323] = -0.72122593097323895; 
data[1361] = 0.21212527381565857; 
data[1362] = -0.14842843880118009; 
data[1367] = -2.470390074076128; 
data[1368] = 1.7285829987599726; 
data[1373] = 1.5370388692872305; 
data[1374] = -1.0754978680347802; 
data[1397] = 0.72122593097323895; 
data[1398] = -0.50465669192401219; 
data[1438] = -1.0754978680347802; 
data[1439] = -1.5370388692872305; 
data[1444] = 2.2470223314298083; 
data[1445] = 3.2113133519036783; 
data[1450] = -1.1715244633950284; 
data[1451] = -1.6742744826164477; 
data[1513] = 1.5370388692872305; 
data[1514] = -1.0754978680347802; 
data[1519] = -3.2113133519036783; 
data[1520] = 2.2470223314298083; 
data[1525] = 1.6742744826164477; 
data[1526] = -1.1715244633950284; 
data[1590] = -1.0754978680347802; 
data[1591] = -1.5370388692872305; 
data[1596] = 2.2470223314298083; 
data[1597] = 3.2113133519036783; 
data[1602] = -1.1715244633950284; 
data[1603] = -1.6742744826164477; 
data[1665] = 1.5370388692872305; 
data[1666] = -1.0754978680347802; 
data[1671] = -3.2113133519036783; 
data[1672] = 2.2470223314298083; 
data[1677] = 1.6742744826164477; 
data[1678] = -1.1715244633950284; 
data[1742] = -1.0754978680347802; 
data[1743] = -1.5370388692872305; 
data[1748] = 2.2470223314298083; 
data[1749] = 3.2113133519036783; 
data[1754] = -1.1715244633950284; 
data[1755] = -1.6742744826164477; 
data[1817] = 1.5370388692872305; 
data[1818] = -1.0754978680347802; 
data[1823] = -3.2113133519036783; 
data[1824] = 2.2470223314298083; 
data[1829] = 1.6742744826164477; 
data[1830] = -1.1715244633950284; 
data[1894] = -1.1715244633950284; 
data[1895] = -1.6742744826164477; 
data[1900] = 1.5975333591750389; 
data[1901] = 2.283101567204247; 
data[1906] = -0.42600889578001044; 
data[1907] = -0.60882708458779922; 
data[1969] = 1.6742744826164477; 
data[1970] = -1.1715244633950284; 
data[1975] = -2.283101567204247; 
data[1976] = 1.5975333591750389; 
data[1981] = 0.60882708458779922; 
data[1982] = -0.42600889578001044; 
data[2046] = -1.1715244633950284; 
data[2047] = -1.6742744826164477; 
data[2052] = 1.5975333591750389; 
data[2053] = 2.283101567204247; 
data[2058] = -0.42600889578001044; 
data[2059] = -0.60882708458779922; 
data[2121] = 1.6742744826164477; 
data[2122] = -1.1715244633950284; 
data[2127] = -2.283101567204247; 
data[2128] = 1.5975333591750389; 
data[2133] = 0.60882708458779922; 
data[2134] = -0.42600889578001044; 
data[2198] = -1.1715244633950284; 
data[2199] = -1.6742744826164477; 
data[2204] = 1.5975333591750389; 
data[2205] = 2.283101567204247; 
data[2210] = -0.42600889578001044; 
data[2211] = -0.60882708458779922; 
data[2273] = 1.6742744826164477; 
data[2274] = -1.1715244633950284; 
data[2279] = -2.283101567204247; 
data[2280] = 1.5975333591750389; 
data[2285] = 0.60882708458779922; 
data[2286] = -0.42600889578001044; 
data[2350] = -0.42600889578001044; 
data[2351] = -0.60882708458779922; 
data[2356] = 3.1595659770350766; 
data[2357] = 4.5154675440261771; 
data[2362] = -2.733557081255066; 
data[2363] = -3.9066404594383779; 
data[2425] = 0.60882708458779922; 
data[2426] = -0.42600889578001044; 
data[2431] = -4.5154675440261771; 
data[2432] = 3.1595659770350766; 
data[2437] = 3.9066404594383779; 
data[2438] = -2.733557081255066; 
data[2502] = -0.42600889578001044; 
data[2503] = -0.60882708458779922; 
data[2508] = 3.1595659770350766; 
data[2509] = 4.5154675440261771; 
data[2514] = -2.733557081255066; 
data[2515] = -3.9066404594383779; 
data[2577] = 0.60882708458779922; 
data[2578] = -0.42600889578001044; 
data[2583] = -4.5154675440261771; 
data[2584] = 3.1595659770350766; 
data[2589] = 3.9066404594383779; 
data[2590] = -2.733557081255066; 
data[2654] = -0.42600889578001044; 
data[2655] = -0.60882708458779922; 
data[2660] = 3.1595659770350766; 
data[2661] = 4.5154675440261771; 
data[2666] = -2.733557081255066; 
data[2667] = -3.9066404594383779; 
data[2729] = 0.60882708458779922; 
data[2730] = -0.42600889578001044; 
data[2735] = -4.5154675440261771; 
data[2736] = 3.1595659770350766; 
data[2741] = 3.9066404594383779; 
data[2742] = -2.733557081255066; 
data[2806] = -2.733557081255066; 
data[2807] = -3.9066404594383779; 
data[2812] = 3.1264036079025006; 
data[2813] = 4.468073818878624; 
data[2818] = -0.39284652664743452; 
data[2819] = -0.56143335944024586; 
data[2881] = 3.9066404594383779; 
data[2882] = -2.733557081255066; 
data[2887] = -4.468073818878624; 
data[2888] = 3.1264036079025006; 
data[2893] = 0.56143335944024586; 
data[2894] = -0.39284652664743452; 
data[2958] = -2.733557081255066; 
data[2959] = -3.9066404594383779; 
data[2964] = 3.1264036079025006; 
data[2965] = 4.468073818878624; 
data[2970] = -0.39284652664743452; 
data[2971] = -0.56143335944024586; 
data[3033] = 3.9066404594383779; 
data[3034] = -2.733557081255066; 
data[3039] = -4.468073818878624; 
data[3040] = 3.1264036079025006; 
data[3045] = 0.56143335944024586; 
data[3046] = -0.39284652664743452; 
data[3110] = -2.733557081255066; 
data[3111] = -3.9066404594383779; 
data[3116] = 3.1264036079025006; 
data[3117] = 4.468073818878624; 
data[3122] = -0.39284652664743452; 
data[3123] = -0.56143335944024586; 
data[3185] = 3.9066404594383779; 
data[3186] = -2.733557081255066; 
data[3191] = -4.468073818878624; 
data[3192] = 3.1264036079025006; 
data[3197] = 0.56143335944024586; 
data[3198] = -0.39284652664743452; 
data[3238] = -0.50465669192401219; 
data[3239] = -0.72122593097323895; 
data[3262] = -0.39284652664743452; 
data[3263] = -0.56143335944024586; 
data[3268] = 2.9476710295127462; 
data[3269] = 4.2126396349922688; 
data[3274] = -2.0501678109412995; 
data[3275] = -2.9299803445787838; 
data[3313] = 0.72122593097323895; 
data[3314] = -0.50465669192401219; 
data[3337] = 0.56143335944024586; 
data[3338] = -0.39284652664743452; 
data[3343] = -4.2126396349922688; 
data[3344] = 2.9476710295127462; 
data[3349] = 2.9299803445787838; 
data[3350] = -2.0501678109412995; 
data[3390] = -0.50465669192401219; 
data[3391] = -0.72122593097323895; 
data[3414] = -0.39284652664743452; 
data[3415] = -0.56143335944024586; 
data[3420] = 2.9476710295127462; 
data[3421] = 4.2126396349922688; 
data[3426] = -2.0501678109412995; 
data[3427] = -2.9299803445787838; 
data[3465] = 0.72122593097323895; 
data[3466] = -0.50465669192401219; 
data[3489] = 0.56143335944024586; 
data[3490] = -0.39284652664743452; 
data[3495] = -4.2126396349922688; 
data[3496] = 2.9476710295127462; 
data[3501] = 2.9299803445787838; 
data[3502] = -2.0501678109412995; 
data[3542] = -0.50465669192401219; 
data[3543] = -0.72122593097323895; 
data[3566] = -0.39284652664743452; 
data[3567] = -0.56143335944024586; 
data[3572] = 2.9476710295127462; 
data[3573] = 4.2126396349922688; 
data[3578] = -2.0501678109412995; 
data[3579] = -2.9299803445787838; 
data[3617] = 0.72122593097323895; 
data[3618] = -0.50465669192401219; 
data[3641] = 0.56143335944024586; 
data[3642] = -0.39284652664743452; 
data[3647] = -4.2126396349922688; 
data[3648] = 2.9476710295127462; 
data[3653] = 2.9299803445787838; 
data[3654] = -2.0501678109412995; 
data[3718] = -2.0501678109412995; 
data[3719] = -2.9299803445787838; 
data[3724] = 2.9021856025013202; 
data[3725] = 4.1476345137543822; 
data[3730] = -0.85201779156002089; 
data[3731] = -1.2176541691755984; 
data[3793] = 2.9299803445787838; 
data[3794] = -2.0501678109412995; 
data[3799] = -4.1476345137543822; 
data[3800] = 2.9021856025013202; 
data[3805] = 1.2176541691755984; 
data[3806] = -0.85201779156002089; 
data[3870] = -2.0501678109412995; 
data[3871] = -2.9299803445787838; 
data[3876] = 2.9021856025013202; 
data[3877] = 4.1476345137543822; 
data[3882] = -0.85201779156002089; 
data[3883] = -1.2176541691755984; 
data[3945] = 2.9299803445787838; 
data[3946] = -2.0501678109412995; 
data[3951] = -4.1476345137543822; 
data[3952] = 2.9021856025013202; 
data[3957] = 1.2176541691755984; 
data[3958] = -0.85201779156002089; 
data[4022] = -2.0501678109412995; 
data[4023] = -2.9299803445787838; 
data[4028] = 2.9021856025013202; 
data[4029] = 4.1476345137543822; 
data[4034] = -0.85201779156002089; 
data[4035] = -1.2176541691755984; 
data[4097] = 2.9299803445787838; 
data[4098] = -2.0501678109412995; 
data[4103] = -4.1476345137543822; 
data[4104] = 2.9021856025013202; 
data[4109] = 1.2176541691755984; 
data[4110] = -0.85201779156002089; 
data[4174] = -0.85201779156002089; 
data[4175] = -1.2176541691755984; 
data[4180] = 2.8400593052000689; 
data[4181] = 4.0588472305853278; 
data[4186] = -1.9880415136400482; 
data[4187] = -2.8411930614097294; 
data[4249] = 1.2176541691755984; 
data[4250] = -0.85201779156002089; 
data[4255] = -4.0588472305853278; 
data[4256] = 2.8400593052000689; 
data[4261] = 2.8411930614097294; 
data[4262] = -1.9880415136400482; 
data[4326] = -0.85201779156002089; 
data[4327] = -1.2176541691755984; 
data[4332] = 2.8400593052000689; 
data[4333] = 4.0588472305853278; 
data[4338] = -1.9880415136400482; 
data[4339] = -2.8411930614097294; 
data[4401] = 1.2176541691755984; 
data[4402] = -0.85201779156002089; 
data[4407] = -4.0588472305853278; 
data[4408] = 2.8400593052000689; 
data[4413] = 2.8411930614097294; 
data[4414] = -1.9880415136400482; 
data[4478] = -0.85201779156002089; 
data[4479] = -1.2176541691755984; 
data[4484] = 2.8400593052000689; 
data[4485] = 4.0588472305853278; 
data[4490] = -1.9880415136400482; 
data[4491] = -2.8411930614097294; 
data[4553] = 1.2176541691755984; 
data[4554] = -0.85201779156002089; 
data[4559] = -4.0588472305853278; 
data[4560] = 2.8400593052000689; 
data[4565] = 2.8411930614097294; 
data[4566] = -1.9880415136400482; 
data[4630] = -1.9880415136400482; 
data[4631] = -2.8411930614097294; 
data[4636] = 1.9880415136400482; 
data[4637] = 2.8411930614097294; 
data[4705] = 2.8411930614097294; 
data[4706] = -1.9880415136400482; 
data[4711] = -2.8411930614097294; 
data[4712] = 1.9880415136400482; 
data[4782] = -1.9880415136400482; 
data[4783] = -2.8411930614097294; 
data[4788] = 1.9880415136400482; 
data[4789] = 2.8411930614097294; 
data[4857] = 2.8411930614097294; 
data[4858] = -1.9880415136400482; 
data[4863] = -2.8411930614097294; 
data[4864] = 1.9880415136400482; 
data[4934] = -1.9880415136400482; 
data[4935] = -2.8411930614097294; 
data[4940] = 1.9880415136400482; 
data[4941] = 2.8411930614097294; 
data[5009] = 2.8411930614097294; 
data[5010] = -1.9880415136400482; 
data[5015] = -2.8411930614097294; 
data[5016] = 1.9880415136400482; 
data[5026] = -1; 
data[5103] = -1; 
data[5180] = -1; 
data[5252] = -1.0; 
data[5329] = -1.0; 
data[5406] = -1.0; 
data[5548] = -1; 
data[5624] = -1; 

}



/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 8), // void()(double *, double *, double *, double *, double *, double)
/*  1 */ _CFFI_OP(_CFFI_OP_POINTER, 6), // double *
/*  2 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/*  3 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/*  4 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/*  5 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/*  6 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14), // double
/*  7 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  8 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 0), // void
};

static void _cffi_d_de_jac_trap_num_eval(double * x0, double * x1, double * x2, double * x3, double * x4, double x5)
{
  de_jac_trap_num_eval(x0, x1, x2, x3, x4, x5);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_de_jac_trap_num_eval(PyObject *self, PyObject *args)
{
  double * x0;
  double * x1;
  double * x2;
  double * x3;
  double * x4;
  double x5;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;

  if (!PyArg_UnpackTuple(args, "de_jac_trap_num_eval", 6, 6, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg3, (char **)&x3);
  if (datasize != 0) {
    x3 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg3, (char **)&x3,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg4, (char **)&x4);
  if (datasize != 0) {
    x4 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg4, (char **)&x4,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x5 = (double)_cffi_to_c_double(arg5);
  if (x5 == (double)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { de_jac_trap_num_eval(x0, x1, x2, x3, x4, x5); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_de_jac_trap_num_eval _cffi_d_de_jac_trap_num_eval
#endif

static void _cffi_d_de_jac_trap_up_eval(double * x0, double * x1, double * x2, double * x3, double * x4, double x5)
{
  de_jac_trap_up_eval(x0, x1, x2, x3, x4, x5);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_de_jac_trap_up_eval(PyObject *self, PyObject *args)
{
  double * x0;
  double * x1;
  double * x2;
  double * x3;
  double * x4;
  double x5;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;

  if (!PyArg_UnpackTuple(args, "de_jac_trap_up_eval", 6, 6, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg3, (char **)&x3);
  if (datasize != 0) {
    x3 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg3, (char **)&x3,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg4, (char **)&x4);
  if (datasize != 0) {
    x4 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg4, (char **)&x4,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x5 = (double)_cffi_to_c_double(arg5);
  if (x5 == (double)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { de_jac_trap_up_eval(x0, x1, x2, x3, x4, x5); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_de_jac_trap_up_eval _cffi_d_de_jac_trap_up_eval
#endif

static void _cffi_d_de_jac_trap_xy_eval(double * x0, double * x1, double * x2, double * x3, double * x4, double x5)
{
  de_jac_trap_xy_eval(x0, x1, x2, x3, x4, x5);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_de_jac_trap_xy_eval(PyObject *self, PyObject *args)
{
  double * x0;
  double * x1;
  double * x2;
  double * x3;
  double * x4;
  double x5;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;

  if (!PyArg_UnpackTuple(args, "de_jac_trap_xy_eval", 6, 6, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg3, (char **)&x3);
  if (datasize != 0) {
    x3 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg3, (char **)&x3,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg4, (char **)&x4);
  if (datasize != 0) {
    x4 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg4, (char **)&x4,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x5 = (double)_cffi_to_c_double(arg5);
  if (x5 == (double)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { de_jac_trap_xy_eval(x0, x1, x2, x3, x4, x5); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_de_jac_trap_xy_eval _cffi_d_de_jac_trap_xy_eval
#endif

static const struct _cffi_global_s _cffi_globals[] = {
  { "de_jac_trap_num_eval", (void *)_cffi_f_de_jac_trap_num_eval, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 0), (void *)_cffi_d_de_jac_trap_num_eval },
  { "de_jac_trap_up_eval", (void *)_cffi_f_de_jac_trap_up_eval, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 0), (void *)_cffi_d_de_jac_trap_up_eval },
  { "de_jac_trap_xy_eval", (void *)_cffi_f_de_jac_trap_xy_eval, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 0), (void *)_cffi_d_de_jac_trap_xy_eval },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  NULL,  /* no fields */
  NULL,  /* no struct_unions */
  NULL,  /* no enums */
  NULL,  /* no typenames */
  3,  /* num_globals */
  0,  /* num_struct_unions */
  0,  /* num_enums */
  0,  /* num_typenames */
  NULL,  /* no includes */
  9,  /* num_types */
  0,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit_temp_trap_cffi(const void *p[])
{
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
#if PY_MAJOR_VERSION >= 3
    return NULL;
#endif
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit_temp_trap_cffi(void) { return NULL; }
#  else
     inittemp_trap_cffi(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit_temp_trap_cffi(void)
{
  return _cffi_init("temp_trap_cffi", 0x2601, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
inittemp_trap_cffi(void)
{
  _cffi_init("temp_trap_cffi", 0x2601, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
