#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   The implementation is messy (issue #350): on Windows, with _MSC_VER,
   we have to define Py_LIMITED_API even before including pyconfig.h.
   In that case, we guess what pyconfig.h will do to the macros above,
   and check our guess after the #include.

   Note that on Windows, with CPython 3.x, you need >= 3.5 and virtualenv
   version >= 16.0.0.  With older versions of either, you don't get a
   copy of PYTHON3.DLL in the virtualenv.  We can't check the version of
   CPython *before* we even include pyconfig.h.  ffi.set_source() puts
   a ``#define _CFFI_NO_LIMITED_API'' at the start of this file if it is
   running on Windows < 3.5, as an attempt at fixing it, but that's
   arguably wrong because it may not be the target version of Python.
   Still better than nothing I guess.  As another workaround, you can
   remove the definition of Py_LIMITED_API here.

   See also 'py_limited_api' in cffi/setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  ifdef _MSC_VER
#    if !defined(_DEBUG) && !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#    include <pyconfig.h>
     /* sanity-check: Py_LIMITED_API will cause crashes if any of these
        are also defined.  Normally, the Python file PC/pyconfig.h does not
        cause any of these to be defined, with the exception that _DEBUG
        causes Py_DEBUG.  Double-check that. */
#    ifdef Py_LIMITED_API
#      if defined(Py_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_DEBUG, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_TRACE_REFS)
#        error "pyconfig.h unexpectedly defines Py_TRACE_REFS, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_REF_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_REF_DEBUG, but Py_LIMITED_API is set"
#      endif
#    endif
#  else
#    include <pyconfig.h>
#    if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>

/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#if PY_MAJOR_VERSION >= 3
# define PyInt_FromLong PyLong_FromLong
#endif

#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyInt_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyInt_FromLong((long)x) :                                    \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyInt_FromLong((long)x) :                                    \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(unsigned int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

union _cffi_union_alignment_u {
    unsigned char m_char;
    unsigned short m_short;
    unsigned int m_int;
    unsigned long m_long;
    unsigned long long m_longlong;
    float m_float;
    double m_double;
    long double m_longdouble;
};

struct _cffi_freeme_s {
    struct _cffi_freeme_s *next;
    union _cffi_union_alignment_u alignment;
};

_CFFI_UNUSED_FN static int
_cffi_convert_array_argument(struct _cffi_ctypedescr *ctptr, PyObject *arg,
                             char **output_data, Py_ssize_t datasize,
                             struct _cffi_freeme_s **freeme)
{
    char *p;
    if (datasize < 0)
        return -1;

    p = *output_data;
    if (p == NULL) {
        struct _cffi_freeme_s *fp = (struct _cffi_freeme_s *)PyObject_Malloc(
            offsetof(struct _cffi_freeme_s, alignment) + (size_t)datasize);
        if (fp == NULL)
            return -1;
        fp->next = *freeme;
        *freeme = fp;
        p = *output_data = (char *)&fp->alignment;
    }
    memset((void *)p, 0, (size_t)datasize);
    return _cffi_convert_array_from_object(p, ctptr, arg);
}

_CFFI_UNUSED_FN static void
_cffi_free_array_arguments(struct _cffi_freeme_s *freeme)
{
    do {
        void *p = (void *)freeme;
        freeme = freeme->next;
        PyObject_Free(p);
    } while (freeme != NULL);
}

/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/

void f_ini_eval(double *data,double *x,double *y,double *u,double *p,double Dt){

data[0] = -p[4]*x[0] - y[48] + u[10] + 1; 

}

void g_ini_eval(double *data,double *x,double *y,double *u,double *p,double Dt){

data[0] = 0.032409658078107279*y[1] + 0.0081024145195268196*y[0] - 0.016204829039053639*y[3] - 0.0040512072597634098*y[2] - 0.016204829039053639*y[5] - 0.0040512072597634098*y[4] - 0.15437172972984647*y[7] - 0.038592932432461619*y[6] + 0.15437172972984647*y[9] + 0.038592932432461619*y[8] - y[42]; 
data[1] = 0.0081024145195268196*y[1] - 0.032409658078107279*y[0] - 0.0040512072597634098*y[3] + 0.016204829039053639*y[2] - 0.0040512072597634098*y[5] + 0.016204829039053639*y[4] - 0.038592932432461619*y[7] + 0.15437172972984647*y[6] + 0.038592932432461619*y[9] - 0.15437172972984647*y[8] - y[45]; 
data[2] = -0.016204829039053639*y[1] - 0.0040512072597634098*y[0] + 0.032409658078107279*y[3] + 0.0081024145195268196*y[2] - 0.016204829039053639*y[5] - 0.0040512072597634098*y[4] - 0.15437172972984647*y[9] - 0.038592932432461619*y[8] + 0.15437172972984647*y[11] + 0.038592932432461619*y[10] - y[43]; 
data[3] = -0.0040512072597634098*y[1] + 0.016204829039053639*y[0] + 0.0081024145195268196*y[3] - 0.032409658078107279*y[2] - 0.0040512072597634098*y[5] + 0.016204829039053639*y[4] - 0.038592932432461619*y[9] + 0.15437172972984647*y[8] + 0.038592932432461619*y[11] - 0.15437172972984647*y[10] - y[46]; 
data[4] = -0.016204829039053639*y[1] - 0.0040512072597634098*y[0] - 0.016204829039053639*y[3] - 0.0040512072597634098*y[2] + 0.032409658078107279*y[5] + 0.0081024145195268196*y[4] + 0.15437172972984647*y[7] + 0.038592932432461619*y[6] - 0.15437172972984647*y[11] - 0.038592932432461619*y[10] - y[44]; 
data[5] = -0.0040512072597634098*y[1] + 0.016204829039053639*y[0] - 0.0040512072597634098*y[3] + 0.016204829039053639*y[2] + 0.0081024145195268196*y[5] - 0.032409658078107279*y[4] + 0.038592932432461619*y[7] - 0.15437172972984647*y[6] - 0.038592932432461619*y[11] + 0.15437172972984647*y[10] - y[47]; 
data[6] = -0.15437172972984647*y[1] - 0.038592932432461619*y[0] + 0.15437172972984647*y[5] + 0.038592932432461619*y[4] + 1.6605272941255305*y[7] + 0.63231623916238322*y[6] - 0.18993905883141271*y[13] - 0.26466918033885378*y[12] - y[24]; 
data[7] = -0.038592932432461619*y[1] + 0.15437172972984647*y[0] + 0.038592932432461619*y[5] - 0.15437172972984647*y[4] + 0.63231623916238322*y[7] - 1.6605272941255305*y[6] - 0.26466918033885378*y[13] + 0.18993905883141271*y[12] - y[25]; 
data[8] = 0.15437172972984647*y[1] + 0.038592932432461619*y[0] - 0.15437172972984647*y[3] - 0.038592932432461619*y[2] + 1.6605272941255305*y[9] + 0.63231623916238322*y[8] - 0.18993905883141271*y[15] - 0.26466918033885378*y[14] - y[26]; 
data[9] = 0.038592932432461619*y[1] - 0.15437172972984647*y[0] - 0.038592932432461619*y[3] + 0.15437172972984647*y[2] + 0.63231623916238322*y[9] - 1.6605272941255305*y[8] - 0.26466918033885378*y[15] + 0.18993905883141271*y[14] - y[27]; 
data[10] = 0.15437172972984647*y[3] + 0.038592932432461619*y[2] - 0.15437172972984647*y[5] - 0.038592932432461619*y[4] + 1.6605272941255305*y[11] + 0.63231623916238322*y[10] - 0.18993905883141271*y[17] - 0.26466918033885378*y[16] - y[28]; 
data[11] = 0.038592932432461619*y[3] - 0.15437172972984647*y[2] - 0.038592932432461619*y[5] + 0.15437172972984647*y[4] + 0.63231623916238322*y[11] - 1.6605272941255305*y[10] - 0.26466918033885378*y[17] + 0.18993905883141271*y[16] - y[29]; 
data[12] = -0.18993905883141271*y[7] - 0.26466918033885378*y[6] + 0.50057517845870636*y[13] + 0.69752278965557457*y[12] - 0.31063611962729365*y[19] - 0.43285360931672079*y[18] - y[30]; 
data[13] = -0.26466918033885378*y[7] + 0.18993905883141271*y[6] + 0.69752278965557457*y[13] - 0.50057517845870636*y[12] - 0.43285360931672079*y[19] + 0.31063611962729365*y[18] - y[31]; 
data[14] = -0.18993905883141271*y[9] - 0.26466918033885378*y[8] + 0.50057517845870636*y[15] + 0.69752278965557457*y[14] - 0.31063611962729365*y[21] - 0.43285360931672079*y[20] - y[32]; 
data[15] = -0.26466918033885378*y[9] + 0.18993905883141271*y[8] + 0.69752278965557457*y[15] - 0.50057517845870636*y[14] - 0.43285360931672079*y[21] + 0.31063611962729365*y[20] - y[33]; 
data[16] = -0.18993905883141271*y[11] - 0.26466918033885378*y[10] + 0.50057517845870636*y[17] + 0.69752278965557457*y[16] - 0.31063611962729365*y[23] - 0.43285360931672079*y[22] - y[34]; 
data[17] = -0.26466918033885378*y[11] + 0.18993905883141271*y[10] + 0.69752278965557457*y[17] - 0.50057517845870636*y[16] - 0.43285360931672079*y[23] + 0.31063611962729365*y[22] - y[35]; 
data[18] = -0.31063611962729365*y[13] - 0.43285360931672079*y[12] + 0.31063611962729365*y[19] + 0.43285360931672079*y[18] - y[36]; 
data[19] = -0.43285360931672079*y[13] + 0.31063611962729365*y[12] + 0.43285360931672079*y[19] - 0.31063611962729365*y[18] - y[37]; 
data[20] = -0.31063611962729365*y[15] - 0.43285360931672079*y[14] + 0.31063611962729365*y[21] + 0.43285360931672079*y[20] - y[38]; 
data[21] = -0.43285360931672079*y[15] + 0.31063611962729365*y[14] + 0.43285360931672079*y[21] - 0.31063611962729365*y[20] - y[39]; 
data[22] = -0.31063611962729365*y[17] - 0.43285360931672079*y[16] + 0.31063611962729365*y[23] + 0.43285360931672079*y[22] - y[40]; 
data[23] = -0.43285360931672079*y[17] + 0.31063611962729365*y[16] + 0.43285360931672079*y[23] - 0.31063611962729365*y[22] - y[41]; 
data[24] = y[7]*y[25] + y[6]*y[24] + (1.0/3.0)*u[0]; 
data[25] = y[9]*y[27] + y[8]*y[26] + (1.0/3.0)*u[0]; 
data[26] = y[7]*y[24] - y[6]*y[25] + (1.0/3.0)*u[1]; 
data[27] = y[9]*y[26] - y[8]*y[27] + (1.0/3.0)*u[1]; 
data[28] = y[24] + y[26] + y[28]; 
data[29] = y[25] + y[27] + y[29]; 
data[30] = y[13]*y[31] + y[12]*y[30] + (1.0/3.0)*u[2]; 
data[31] = y[15]*y[33] + y[14]*y[32] + (1.0/3.0)*u[2]; 
data[32] = y[13]*y[30] - y[12]*y[31] + (1.0/3.0)*u[3]; 
data[33] = y[15]*y[32] - y[14]*y[33] + (1.0/3.0)*u[3]; 
data[34] = y[30] + y[32] + y[34]; 
data[35] = y[31] + y[33] + y[35]; 
data[36] = y[19]*y[37] + y[18]*y[36] + (1.0/3.0)*u[4]; 
data[37] = y[21]*y[39] + y[20]*y[38] + (1.0/3.0)*u[4]; 
data[38] = y[19]*y[36] - y[18]*y[37] + (1.0/3.0)*u[5]; 
data[39] = y[21]*y[38] - y[20]*y[39] + (1.0/3.0)*u[5]; 
data[40] = y[36] + y[38] + y[40]; 
data[41] = y[37] + y[39] + y[41]; 
data[42] = -p[1]*y[42] - y[0] + 1.0*p[0]*y[45] + u[6]*cos(u[9]); 
data[43] = -p[1]*y[43] - y[2] + 1.0*p[0]*y[46] + u[7]*cos(u[9] - 2.0943951023931953); 
data[44] = -p[1]*y[44] - y[4] + 1.0*p[0]*y[47] + u[8]*cos(u[9] - 4.1887902047863905); 
data[45] = -1.0*p[1]*y[45] - 1.0*y[1] - 1.0*p[0]*y[42] + 1.0*u[6]*sin(u[9]); 
data[46] = -1.0*p[1]*y[46] - 1.0*y[3] - 1.0*p[0]*y[43] + 1.0*u[7]*sin(u[9] - 2.0943951023931953); 
data[47] = -1.0*p[1]*y[47] - 1.0*y[5] - 1.0*p[0]*y[44] + 1.0*u[8]*sin(u[9] - 4.1887902047863905); 
data[48] = 1.0 - y[48]; 
data[49] = p[3]*x[0] + p[2]*(1 - y[48]) - y[49]; 

}

void h_eval(double *data,double *x,double *y,double *u,double *p,double Dt){

data[0] = 0.032409658078107279*y[1] + 0.0081024145195268196*y[0] - 0.016204829039053639*y[3] - 0.0040512072597634098*y[2] - 0.016204829039053639*y[5] - 0.0040512072597634098*y[4] - 0.15437172972984647*y[7] - 0.038592932432461619*y[6] + 0.15437172972984647*y[9] + 0.038592932432461619*y[8]; 
data[1] = 0.0081024145195268196*y[1] - 0.032409658078107279*y[0] - 0.0040512072597634098*y[3] + 0.016204829039053639*y[2] - 0.0040512072597634098*y[5] + 0.016204829039053639*y[4] - 0.038592932432461619*y[7] + 0.15437172972984647*y[6] + 0.038592932432461619*y[9] - 0.15437172972984647*y[8]; 
data[2] = -0.016204829039053639*y[1] - 0.0040512072597634098*y[0] + 0.032409658078107279*y[3] + 0.0081024145195268196*y[2] - 0.016204829039053639*y[5] - 0.0040512072597634098*y[4] - 0.15437172972984647*y[9] - 0.038592932432461619*y[8] + 0.15437172972984647*y[11] + 0.038592932432461619*y[10]; 
data[3] = -0.0040512072597634098*y[1] + 0.016204829039053639*y[0] + 0.0081024145195268196*y[3] - 0.032409658078107279*y[2] - 0.0040512072597634098*y[5] + 0.016204829039053639*y[4] - 0.038592932432461619*y[9] + 0.15437172972984647*y[8] + 0.038592932432461619*y[11] - 0.15437172972984647*y[10]; 
data[4] = -0.016204829039053639*y[1] - 0.0040512072597634098*y[0] - 0.016204829039053639*y[3] - 0.0040512072597634098*y[2] + 0.032409658078107279*y[5] + 0.0081024145195268196*y[4] + 0.15437172972984647*y[7] + 0.038592932432461619*y[6] - 0.15437172972984647*y[11] - 0.038592932432461619*y[10]; 
data[5] = -0.0040512072597634098*y[1] + 0.016204829039053639*y[0] - 0.0040512072597634098*y[3] + 0.016204829039053639*y[2] + 0.0081024145195268196*y[5] - 0.032409658078107279*y[4] + 0.038592932432461619*y[7] - 0.15437172972984647*y[6] - 0.038592932432461619*y[11] + 0.15437172972984647*y[10]; 
data[6] = -0.15437172972984647*y[1] - 0.038592932432461619*y[0] + 0.15437172972984647*y[5] + 0.038592932432461619*y[4] + 1.4705882352941178*y[7] + 0.36764705882352944*y[6]; 
data[7] = -0.038592932432461619*y[1] + 0.15437172972984647*y[0] + 0.038592932432461619*y[5] - 0.15437172972984647*y[4] + 0.36764705882352944*y[7] - 1.4705882352941178*y[6]; 
data[8] = 0.15437172972984647*y[1] + 0.038592932432461619*y[0] - 0.15437172972984647*y[3] - 0.038592932432461619*y[2] + 1.4705882352941178*y[9] + 0.36764705882352944*y[8]; 
data[9] = 0.038592932432461619*y[1] - 0.15437172972984647*y[0] - 0.038592932432461619*y[3] + 0.15437172972984647*y[2] + 0.36764705882352944*y[9] - 1.4705882352941178*y[8]; 
data[10] = 0.15437172972984647*y[3] + 0.038592932432461619*y[2] - 0.15437172972984647*y[5] - 0.038592932432461619*y[4] + 1.4705882352941178*y[11] + 0.36764705882352944*y[10]; 
data[11] = 0.038592932432461619*y[3] - 0.15437172972984647*y[2] - 0.038592932432461619*y[5] + 0.15437172972984647*y[4] + 0.36764705882352944*y[11] - 1.4705882352941178*y[10]; 
data[12] = sqrt(1.0*pow(y[45], 2) + pow(y[42], 2)); 
data[13] = sqrt(1.0*pow(y[46], 2) + pow(y[43], 2)); 
data[14] = sqrt(1.0*pow(y[47], 2) + pow(y[44], 2)); 
data[15] = 1.0*y[1]*y[45] + y[0]*y[42] + 1.0*y[3]*y[46] + y[2]*y[43] + 1.0*y[5]*y[47] + y[4]*y[44]; 
data[16] = 1.0*y[1]*y[42] - 1.0*y[0]*y[45] + 1.0*y[3]*y[43] - 1.0*y[2]*y[46] + 1.0*y[5]*y[44] - 1.0*y[4]*y[47]; 
data[17] = x[0]; 
data[18] = u[10]; 

}

void de_jac_ini_up_eval(double *data,double *x,double *y,double *u,double *p,double Dt){

data[0] = -p[4]; 
data[2236] = -p[1]; 
data[2239] = 1.0*p[0]; 
data[2288] = -p[1]; 
data[2291] = 1.0*p[0]; 
data[2340] = -p[1]; 
data[2343] = 1.0*p[0]; 
data[2389] = -1.0*p[0]; 
data[2392] = -1.0*p[1]; 
data[2441] = -1.0*p[0]; 
data[2444] = -1.0*p[1]; 
data[2493] = -1.0*p[0]; 
data[2496] = -1.0*p[1]; 
data[2550] = p[3]; 
data[2599] = -p[2]; 

}

void de_jac_ini_xy_eval(double *data,double *x,double *y,double *u,double *p,double Dt){

data[1282] = y[24]; 
data[1283] = y[25]; 
data[1300] = y[6]; 
data[1301] = y[7]; 
data[1335] = y[26]; 
data[1336] = y[27]; 
data[1353] = y[8]; 
data[1354] = y[9]; 
data[1384] = -y[25]; 
data[1385] = y[24]; 
data[1402] = y[7]; 
data[1403] = -y[6]; 
data[1437] = -y[27]; 
data[1438] = y[26]; 
data[1455] = y[9]; 
data[1456] = -y[8]; 
data[1594] = y[30]; 
data[1595] = y[31]; 
data[1612] = y[12]; 
data[1613] = y[13]; 
data[1647] = y[32]; 
data[1648] = y[33]; 
data[1665] = y[14]; 
data[1666] = y[15]; 
data[1696] = -y[31]; 
data[1697] = y[30]; 
data[1714] = y[13]; 
data[1715] = -y[12]; 
data[1749] = -y[33]; 
data[1750] = y[32]; 
data[1767] = y[15]; 
data[1768] = -y[14]; 
data[1906] = y[36]; 
data[1907] = y[37]; 
data[1924] = y[18]; 
data[1925] = y[19]; 
data[1959] = y[38]; 
data[1960] = y[39]; 
data[1977] = y[20]; 
data[1978] = y[21]; 
data[2008] = -y[37]; 
data[2009] = y[36]; 
data[2026] = y[19]; 
data[2027] = -y[18]; 
data[2061] = -y[39]; 
data[2062] = y[38]; 
data[2079] = y[21]; 
data[2080] = -y[20]; 

}

void de_jac_ini_num_eval(double *data,double *x,double *y,double *u,double *p,double Dt){

data[49] = -1; 
data[52] = 0.0081024145195268196; 
data[53] = 0.032409658078107279; 
data[54] = -0.0040512072597634098; 
data[55] = -0.016204829039053639; 
data[56] = -0.0040512072597634098; 
data[57] = -0.016204829039053639; 
data[58] = -0.038592932432461619; 
data[59] = -0.15437172972984647; 
data[60] = 0.038592932432461619; 
data[61] = 0.15437172972984647; 
data[94] = -1; 
data[103] = -0.032409658078107279; 
data[104] = 0.0081024145195268196; 
data[105] = 0.016204829039053639; 
data[106] = -0.0040512072597634098; 
data[107] = 0.016204829039053639; 
data[108] = -0.0040512072597634098; 
data[109] = 0.15437172972984647; 
data[110] = -0.038592932432461619; 
data[111] = -0.15437172972984647; 
data[112] = 0.038592932432461619; 
data[148] = -1; 
data[154] = -0.0040512072597634098; 
data[155] = -0.016204829039053639; 
data[156] = 0.0081024145195268196; 
data[157] = 0.032409658078107279; 
data[158] = -0.0040512072597634098; 
data[159] = -0.016204829039053639; 
data[162] = -0.038592932432461619; 
data[163] = -0.15437172972984647; 
data[164] = 0.038592932432461619; 
data[165] = 0.15437172972984647; 
data[197] = -1; 
data[205] = 0.016204829039053639; 
data[206] = -0.0040512072597634098; 
data[207] = -0.032409658078107279; 
data[208] = 0.0081024145195268196; 
data[209] = 0.016204829039053639; 
data[210] = -0.0040512072597634098; 
data[213] = 0.15437172972984647; 
data[214] = -0.038592932432461619; 
data[215] = -0.15437172972984647; 
data[216] = 0.038592932432461619; 
data[251] = -1; 
data[256] = -0.0040512072597634098; 
data[257] = -0.016204829039053639; 
data[258] = -0.0040512072597634098; 
data[259] = -0.016204829039053639; 
data[260] = 0.0081024145195268196; 
data[261] = 0.032409658078107279; 
data[262] = 0.038592932432461619; 
data[263] = 0.15437172972984647; 
data[266] = -0.038592932432461619; 
data[267] = -0.15437172972984647; 
data[300] = -1; 
data[307] = 0.016204829039053639; 
data[308] = -0.0040512072597634098; 
data[309] = 0.016204829039053639; 
data[310] = -0.0040512072597634098; 
data[311] = -0.032409658078107279; 
data[312] = 0.0081024145195268196; 
data[313] = -0.15437172972984647; 
data[314] = 0.038592932432461619; 
data[317] = 0.15437172972984647; 
data[318] = -0.038592932432461619; 
data[354] = -1; 
data[358] = -0.038592932432461619; 
data[359] = -0.15437172972984647; 
data[362] = 0.038592932432461619; 
data[363] = 0.15437172972984647; 
data[364] = 0.63231623916238322; 
data[365] = 1.6605272941255305; 
data[370] = -0.26466918033885378; 
data[371] = -0.18993905883141271; 
data[382] = -1; 
data[409] = 0.15437172972984647; 
data[410] = -0.038592932432461619; 
data[413] = -0.15437172972984647; 
data[414] = 0.038592932432461619; 
data[415] = -1.6605272941255305; 
data[416] = 0.63231623916238322; 
data[421] = 0.18993905883141271; 
data[422] = -0.26466918033885378; 
data[434] = -1; 
data[460] = 0.038592932432461619; 
data[461] = 0.15437172972984647; 
data[462] = -0.038592932432461619; 
data[463] = -0.15437172972984647; 
data[468] = 0.63231623916238322; 
data[469] = 1.6605272941255305; 
data[474] = -0.26466918033885378; 
data[475] = -0.18993905883141271; 
data[486] = -1; 
data[511] = -0.15437172972984647; 
data[512] = 0.038592932432461619; 
data[513] = 0.15437172972984647; 
data[514] = -0.038592932432461619; 
data[519] = -1.6605272941255305; 
data[520] = 0.63231623916238322; 
data[525] = 0.18993905883141271; 
data[526] = -0.26466918033885378; 
data[538] = -1; 
data[564] = 0.038592932432461619; 
data[565] = 0.15437172972984647; 
data[566] = -0.038592932432461619; 
data[567] = -0.15437172972984647; 
data[572] = 0.63231623916238322; 
data[573] = 1.6605272941255305; 
data[578] = -0.26466918033885378; 
data[579] = -0.18993905883141271; 
data[590] = -1; 
data[615] = -0.15437172972984647; 
data[616] = 0.038592932432461619; 
data[617] = 0.15437172972984647; 
data[618] = -0.038592932432461619; 
data[623] = -1.6605272941255305; 
data[624] = 0.63231623916238322; 
data[629] = 0.18993905883141271; 
data[630] = -0.26466918033885378; 
data[642] = -1; 
data[670] = -0.26466918033885378; 
data[671] = -0.18993905883141271; 
data[676] = 0.69752278965557457; 
data[677] = 0.50057517845870636; 
data[682] = -0.43285360931672079; 
data[683] = -0.31063611962729365; 
data[694] = -1; 
data[721] = 0.18993905883141271; 
data[722] = -0.26466918033885378; 
data[727] = -0.50057517845870636; 
data[728] = 0.69752278965557457; 
data[733] = 0.31063611962729365; 
data[734] = -0.43285360931672079; 
data[746] = -1; 
data[774] = -0.26466918033885378; 
data[775] = -0.18993905883141271; 
data[780] = 0.69752278965557457; 
data[781] = 0.50057517845870636; 
data[786] = -0.43285360931672079; 
data[787] = -0.31063611962729365; 
data[798] = -1; 
data[825] = 0.18993905883141271; 
data[826] = -0.26466918033885378; 
data[831] = -0.50057517845870636; 
data[832] = 0.69752278965557457; 
data[837] = 0.31063611962729365; 
data[838] = -0.43285360931672079; 
data[850] = -1; 
data[878] = -0.26466918033885378; 
data[879] = -0.18993905883141271; 
data[884] = 0.69752278965557457; 
data[885] = 0.50057517845870636; 
data[890] = -0.43285360931672079; 
data[891] = -0.31063611962729365; 
data[902] = -1; 
data[929] = 0.18993905883141271; 
data[930] = -0.26466918033885378; 
data[935] = -0.50057517845870636; 
data[936] = 0.69752278965557457; 
data[941] = 0.31063611962729365; 
data[942] = -0.43285360931672079; 
data[954] = -1; 
data[982] = -0.43285360931672079; 
data[983] = -0.31063611962729365; 
data[988] = 0.43285360931672079; 
data[989] = 0.31063611962729365; 
data[1006] = -1; 
data[1033] = 0.31063611962729365; 
data[1034] = -0.43285360931672079; 
data[1039] = -0.31063611962729365; 
data[1040] = 0.43285360931672079; 
data[1058] = -1; 
data[1086] = -0.43285360931672079; 
data[1087] = -0.31063611962729365; 
data[1092] = 0.43285360931672079; 
data[1093] = 0.31063611962729365; 
data[1110] = -1; 
data[1137] = 0.31063611962729365; 
data[1138] = -0.43285360931672079; 
data[1143] = -0.31063611962729365; 
data[1144] = 0.43285360931672079; 
data[1162] = -1; 
data[1190] = -0.43285360931672079; 
data[1191] = -0.31063611962729365; 
data[1196] = 0.43285360931672079; 
data[1197] = 0.31063611962729365; 
data[1214] = -1; 
data[1241] = 0.31063611962729365; 
data[1242] = -0.43285360931672079; 
data[1247] = -0.31063611962729365; 
data[1248] = 0.43285360931672079; 
data[1266] = -1; 
data[1504] = 1; 
data[1506] = 1; 
data[1508] = 1; 
data[1556] = 1; 
data[1558] = 1; 
data[1560] = 1; 
data[1816] = 1; 
data[1818] = 1; 
data[1820] = 1; 
data[1868] = 1; 
data[1870] = 1; 
data[1872] = 1; 
data[2128] = 1; 
data[2130] = 1; 
data[2132] = 1; 
data[2180] = 1; 
data[2182] = 1; 
data[2184] = 1; 
data[2194] = -1; 
data[2247] = -1; 
data[2300] = -1; 
data[2348] = -1.0; 
data[2401] = -1.0; 
data[2454] = -1.0; 
data[2548] = -1; 
data[2600] = -1; 

}



/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 8), // void()(double *, double *, double *, double *, double *, double)
/*  1 */ _CFFI_OP(_CFFI_OP_POINTER, 6), // double *
/*  2 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/*  3 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/*  4 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/*  5 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/*  6 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14), // double
/*  7 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  8 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 0), // void
};

static void _cffi_d_de_jac_ini_num_eval(double * x0, double * x1, double * x2, double * x3, double * x4, double x5)
{
  de_jac_ini_num_eval(x0, x1, x2, x3, x4, x5);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_de_jac_ini_num_eval(PyObject *self, PyObject *args)
{
  double * x0;
  double * x1;
  double * x2;
  double * x3;
  double * x4;
  double x5;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;

  if (!PyArg_UnpackTuple(args, "de_jac_ini_num_eval", 6, 6, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg3, (char **)&x3);
  if (datasize != 0) {
    x3 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg3, (char **)&x3,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg4, (char **)&x4);
  if (datasize != 0) {
    x4 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg4, (char **)&x4,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x5 = (double)_cffi_to_c_double(arg5);
  if (x5 == (double)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { de_jac_ini_num_eval(x0, x1, x2, x3, x4, x5); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_de_jac_ini_num_eval _cffi_d_de_jac_ini_num_eval
#endif

static void _cffi_d_de_jac_ini_up_eval(double * x0, double * x1, double * x2, double * x3, double * x4, double x5)
{
  de_jac_ini_up_eval(x0, x1, x2, x3, x4, x5);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_de_jac_ini_up_eval(PyObject *self, PyObject *args)
{
  double * x0;
  double * x1;
  double * x2;
  double * x3;
  double * x4;
  double x5;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;

  if (!PyArg_UnpackTuple(args, "de_jac_ini_up_eval", 6, 6, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg3, (char **)&x3);
  if (datasize != 0) {
    x3 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg3, (char **)&x3,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg4, (char **)&x4);
  if (datasize != 0) {
    x4 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg4, (char **)&x4,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x5 = (double)_cffi_to_c_double(arg5);
  if (x5 == (double)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { de_jac_ini_up_eval(x0, x1, x2, x3, x4, x5); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_de_jac_ini_up_eval _cffi_d_de_jac_ini_up_eval
#endif

static void _cffi_d_de_jac_ini_xy_eval(double * x0, double * x1, double * x2, double * x3, double * x4, double x5)
{
  de_jac_ini_xy_eval(x0, x1, x2, x3, x4, x5);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_de_jac_ini_xy_eval(PyObject *self, PyObject *args)
{
  double * x0;
  double * x1;
  double * x2;
  double * x3;
  double * x4;
  double x5;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;

  if (!PyArg_UnpackTuple(args, "de_jac_ini_xy_eval", 6, 6, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg3, (char **)&x3);
  if (datasize != 0) {
    x3 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg3, (char **)&x3,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg4, (char **)&x4);
  if (datasize != 0) {
    x4 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg4, (char **)&x4,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x5 = (double)_cffi_to_c_double(arg5);
  if (x5 == (double)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { de_jac_ini_xy_eval(x0, x1, x2, x3, x4, x5); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_de_jac_ini_xy_eval _cffi_d_de_jac_ini_xy_eval
#endif

static void _cffi_d_f_ini_eval(double * x0, double * x1, double * x2, double * x3, double * x4, double x5)
{
  f_ini_eval(x0, x1, x2, x3, x4, x5);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_f_ini_eval(PyObject *self, PyObject *args)
{
  double * x0;
  double * x1;
  double * x2;
  double * x3;
  double * x4;
  double x5;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;

  if (!PyArg_UnpackTuple(args, "f_ini_eval", 6, 6, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg3, (char **)&x3);
  if (datasize != 0) {
    x3 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg3, (char **)&x3,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg4, (char **)&x4);
  if (datasize != 0) {
    x4 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg4, (char **)&x4,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x5 = (double)_cffi_to_c_double(arg5);
  if (x5 == (double)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { f_ini_eval(x0, x1, x2, x3, x4, x5); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_f_ini_eval _cffi_d_f_ini_eval
#endif

static void _cffi_d_g_ini_eval(double * x0, double * x1, double * x2, double * x3, double * x4, double x5)
{
  g_ini_eval(x0, x1, x2, x3, x4, x5);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_g_ini_eval(PyObject *self, PyObject *args)
{
  double * x0;
  double * x1;
  double * x2;
  double * x3;
  double * x4;
  double x5;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;

  if (!PyArg_UnpackTuple(args, "g_ini_eval", 6, 6, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg3, (char **)&x3);
  if (datasize != 0) {
    x3 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg3, (char **)&x3,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg4, (char **)&x4);
  if (datasize != 0) {
    x4 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg4, (char **)&x4,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x5 = (double)_cffi_to_c_double(arg5);
  if (x5 == (double)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { g_ini_eval(x0, x1, x2, x3, x4, x5); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_g_ini_eval _cffi_d_g_ini_eval
#endif

static void _cffi_d_h_eval(double * x0, double * x1, double * x2, double * x3, double * x4, double x5)
{
  h_eval(x0, x1, x2, x3, x4, x5);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_h_eval(PyObject *self, PyObject *args)
{
  double * x0;
  double * x1;
  double * x2;
  double * x3;
  double * x4;
  double x5;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;

  if (!PyArg_UnpackTuple(args, "h_eval", 6, 6, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg3, (char **)&x3);
  if (datasize != 0) {
    x3 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg3, (char **)&x3,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg4, (char **)&x4);
  if (datasize != 0) {
    x4 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg4, (char **)&x4,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x5 = (double)_cffi_to_c_double(arg5);
  if (x5 == (double)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { h_eval(x0, x1, x2, x3, x4, x5); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_h_eval _cffi_d_h_eval
#endif

static const struct _cffi_global_s _cffi_globals[] = {
  { "de_jac_ini_num_eval", (void *)_cffi_f_de_jac_ini_num_eval, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 0), (void *)_cffi_d_de_jac_ini_num_eval },
  { "de_jac_ini_up_eval", (void *)_cffi_f_de_jac_ini_up_eval, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 0), (void *)_cffi_d_de_jac_ini_up_eval },
  { "de_jac_ini_xy_eval", (void *)_cffi_f_de_jac_ini_xy_eval, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 0), (void *)_cffi_d_de_jac_ini_xy_eval },
  { "f_ini_eval", (void *)_cffi_f_f_ini_eval, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 0), (void *)_cffi_d_f_ini_eval },
  { "g_ini_eval", (void *)_cffi_f_g_ini_eval, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 0), (void *)_cffi_d_g_ini_eval },
  { "h_eval", (void *)_cffi_f_h_eval, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 0), (void *)_cffi_d_h_eval },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  NULL,  /* no fields */
  NULL,  /* no struct_unions */
  NULL,  /* no enums */
  NULL,  /* no typenames */
  6,  /* num_globals */
  0,  /* num_struct_unions */
  0,  /* num_enums */
  0,  /* num_typenames */
  NULL,  /* no includes */
  9,  /* num_types */
  0,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit_cigre_eu_mv_f2_ini_cffi(const void *p[])
{
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
#if PY_MAJOR_VERSION >= 3
    return NULL;
#endif
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit_cigre_eu_mv_f2_ini_cffi(void) { return NULL; }
#  else
     initcigre_eu_mv_f2_ini_cffi(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit_cigre_eu_mv_f2_ini_cffi(void)
{
  return _cffi_init("cigre_eu_mv_f2_ini_cffi", 0x2601, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
initcigre_eu_mv_f2_ini_cffi(void)
{
  _cffi_init("cigre_eu_mv_f2_ini_cffi", 0x2601, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
